### ISSUE TITLE
Limiting character input of xeditable input field

### ISSUE THREAD

**Issue by mparisi76** [vitalets/angular-xeditable#101]
Hi, I would like to set that maximum number of characters in an editable text input. How would I accomplish this?

Thanks.

**Comment by lorenscott** [comment]
This did not work for me.  Using X-editable.

**Comment by eugef** [comment]
`e-maxlength` works fine, here is jsFIddle http://jsfiddle.net/NfPcH/9468/ 
You can also try `e-ng-maxlength` though

**Comment by lorenscott** [comment]
@eugef It was e-style that I was testing.  My intent was to not limit the max-length (in characters), but to set the physicial width (in pixels) of the input elements.

**Comment by geostima** [comment]
e-maxlength works on a editable-text field but NOT on a editable-number field, be aware of that. (in case that is the reason why it wasn't working for you and you did not specify correctly).

**Comment by NessfertIndia** [comment]
How to make it work for textarea? Any alternate ways? I am already using a validation on sumission like 
  $(item).editable({
                type: 'textarea',
                url: '/Project/POSTComment',
                title: 'POST Comment',
                validate: function (value) {
                    if ($.trim(value) == '') {
                        return 'This field is required';
                    }
                    else if (value.length > 490) {
                        return 'Max length is 490';
                    }
                },
                success: function (response) {



But looking for some better ways which UI prevents user from adding more characters

**Comment by ckosloski** [comment]
Did you try `e-maxlength=490`?  It should work on [textarea](http://www.w3schools.com/tags/att_textarea_maxlength.asp).

**Comment by NessfertIndia** [comment]
Yes but its not working for me .  Can u share some jsFiddle samples to see the difference from my approach

**Comment by ckosloski** [comment]
See the [fiddle](http://jsfiddle.net/ckosloski/Loo99pme/1/)

**Comment by maxxrdrgz** [comment]
Is there any way to set maxlength not using angular? I'm the BS3 build.

**Comment by maxxrdrgz** [comment]
Figured it out, you can use the tpl option of a textarea to change the html template like so:

`
$('.class').editable({
    type:'textarea',
    tpl: '<textarea maxlength="5"></textarea>'
});
`

**Comment by ckosloski** [comment]
Thanks for sharing your code
