### ISSUE TITLE
wysihtml5 support

### ISSUE THREAD

**Issue by snebjorn** [vitalets/angular-xeditable#104]
Hi, I would like to request support for [wysihtml5](http://xing.github.io/wysihtml5/) just like the [jQuery version](http://vitalets.github.io/x-editable/docs.html#wysihtml5).

Thanks. :)

**Comment by ckosloski** [comment]
Since wysihtml5 isn't supported anymore should this be closed?

**Comment by ckosloski** [comment]
@eugef I think this can be closed.
