### ISSUE TITLE
Update model on change event, instead of on blur or on save?

### ISSUE THREAD

**Issue by d-H-** [vitalets/angular-xeditable#105]
Inside of an editable number or an editable text, is there any way to update the data model every time the input value is changed?  I'd like to keep my model in sync with every keystroke, rather than waiting for a blur event, or for a press of the save button.

At the moment I'm using the line below, which of course only updates `model` when the field is blurred.

`<a href="#" editable-number="model" buttons="no" blur="submit"></a>`

Any idea how I could make it update with every change?  Can this be done with `angular-xeditable` as it is now, or would a new feature need to be implemented?

**Comment by rankun203** [comment]
And another question, how to update the editable value when the model changes?

**Comment by getkitchendeal** [comment]
+1.Would be nice if i could pass the parameter to instantly update the model(like default behavior in angular)  i used e-ng-click='myfunction ($data)'

**Comment by getkitchendeal** [comment]
Fiddle: [(https://codedump.io/share/VuLCMjxQZKD3/1/angular-x-editable-show-some-form-control-onchange)]

e-ng-change only works for select. Check the link above to see it in action. Set "status" ="status 1" However when you you try to use e-ng-change with checklist, check box, radio list then it throws an error: can't find ng-model.
e-ng-click='myfunction ($data)' -> doesn't work

Did anyone figure out the fix that will suit all controls in x editable?

**Comment by ckosloski** [comment]
I think the issue with the checklist/checkbox/radiolist is that these tags don't transfer all of the e- attributes like some of the other elements.  I believe this is a code change to transfer the ng-change to the input element and remove it from the parent element. 
The can't find ng-model error comes from the fact that the ng-change winds up on the containing span of the radio list and not on the actual input element.

**Comment by ckosloski** [comment]
@eugef `ng-change` is now supported, please close.
