### ISSUE TITLE
Rejected Promises in onbeforesave are not handled?

### ISSUE THREAD

**Issue by 000panther** [vitalets/angular-xeditable#106]
According to the Documentation, one can return a Promise in the onbeforesave handler, and xeditable will update the model or not depending on the result of the promise.
- true = Form valid, model will be updated
- string = Form invalid, model will not be updated, form stays open.

This works for me, and works fine. But what happens if the promise returned by the handler is rejected? It seems like it goes in the same case as if the returned value was true. Should it not handle the promise as failed?

For me this was also a startup issue, because from the documentation it was not clear that rejected Promises are not handled, and I was wondering why my code was not working ... 

http://plnkr.co/edit/mzCBawe6hWsIZ6nKetkY

**Comment by pihomeserver** [comment]
@hobbysoldat how did you manage that ?
I try the following code but can't get the returned message displayed in the table in case of error
```
		var deferred = $q.defer();

		if (data.db_element === '' && data.active) {
			deferred.reject('Source can not be empty for active series');
		} else {
			deferred.resolve(true);
		}

		return deferred.promise;
```

**Comment by hobbysoldat** [comment]
Puh, sorry this is a very old issue, I do not remember what I did ...

**Comment by pihomeserver** [comment]
Thanks anyway
