### ISSUE TITLE
Using xeditable in AngularUi Tab Heading

### ISSUE THREAD

**Issue by mikyladewitt** [vitalets/angular-xeditable#107]
Hello,

Is there a way to allow the xeditable fields work within an AngularUI Tab Heading? Currently, the submit does not seem to do anything. Not sure if this is an angular-ui issue or a xeditable issue.

Here is a [stackoverflow question](http://stackoverflow.com/questions/21422822/using-x-editable-within-ui-bootstrap-tab-heading-directive-in-angularjs) that details the problem and a [jsfiddle](http://jsfiddle.net/RDfTu/) from that same question.

This works great otherwise though!

**Comment by hfar** [comment]
Hello,

I have the same issue ..is there any workaround please for this?

**Comment by hfar** [comment]
Hello,

I had the same issue and in my case i was able to solve it using `blur` attribute :

    <tab-heading>
       <span editable-text="tab.name" onbeforesave="validate($data)" buttons="no" blur="submit">{{ tab.name}}</span>
     </tab-heading>

Please see the [documentation][1].

Also please see the below code in `xeditable.js`: 

    if (shown[i]._blur === 'submit') {
            toSubmit.push(shown[i]);
          }

  [1]: http://vitalets.github.io/angular-xeditable/#ref-element

**Comment by ckosloski** [comment]
Please see discussion in #563, you need to change the template of the header in order for the clicks to work correctly.

Please close.

**Comment by ckosloski** [comment]
@eugef I think this can be closed.
