### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by asmuelle** [vitalets/angular-xeditable#108]
I have a view with 3000 editable-textboxes inside a ng-repeat. When I replace the model of the ng-repeat alternately with two arrays of the same lenght, memory consumpion is increasing and after about 20 iterations chrome crashes.

It  seems that some event handlers are not unbound on $destroy.

**Comment by jrvidal** [comment]
+1

The simplest example shows a memory leak:
http://embed.plnkr.co/WE7XFvtMhrRzPtpxqcc0/preview

**Comment by ckosloski** [comment]
Is this issue fixed now that #489 has been merged?

**Comment by asmuelle** [comment]
Yes, works for me.
