### ISSUE TITLE
Add ability to set editable as enabled / disabled

### ISSUE THREAD

**Issue by Robert-Leggett** [vitalets/angular-xeditable#109]
I was previously using you other library http://vitalets.github.io/x-editable/docs.html and found it fantastic, but soon realized it was not sufficient for angular js as it did not update the ng-model and a custom directive would need to be created.

I then discovered this project which supports angular js, the only issue I am facing at the moment, is the usage of the manual enable.

In the x-editable project it was simple to enable / disable editing which is great for when you have setup security and want only certain people to have edit only access, currently this library does not support that scenario.

Can you create a similar feature where you can enable / disable edit in the same way that x-editable does it. Possible --> http://jsfiddle.net/mahbub/XRL4U/

The other project did this by using the .editable() and setting the disabled to true or false, and it could be applied on individual or group elements.

Until this is done I am considering to use x-editable with a custom directive similar to this.  As this approach with utilize that great feature of x-editable + support angular js model updates.
http://jsfiddle.net/mahbub/XRL4U/

**Comment by RavenHursT** [comment]
+1

Seems to me like this is still a very desirable feature.  Currently, what @markvp said seems to be the only way to control editable enabled/disabled functionality.  Especially when implementing a "buttonless" editable via the blur="submit" and buttons="no" attributes for editable fields directives.

Preferably it was seem logical to just tie ng-disabled into this library that would just disable/enable editable functionality based on the truthiness of the ng-disabeled value.

**Comment by RavenHursT** [comment]
The PR here: https://github.com/vitalets/angular-xeditable/pull/235 seems to be a great solution.  But it hasn't been merged yet :-1:

**Comment by vpratti** [comment]
+1

**Comment by fracz** [comment]
+1

**Comment by VitalyM** [comment]
+1

**Comment by asakalou** [comment]
+1

**Comment by RavenHursT** [comment]
Can we get this re-opened or someone to point us toward another issue where this might be getting implemented?  Seems like a lot of people would like to see this...

**Comment by Robert-Leggett** [comment]
I have reopen the issue due to the support for this to occur.

**Comment by marcosPerezRubio** [comment]
+1

**Comment by amerli** [comment]
+1

**Comment by abloch** [comment]
+1

**Comment by thim81** [comment]
+1

**Comment by Arkh1** [comment]
+1

**Comment by edalorzo** [comment]
+1

**Comment by ckosloski** [comment]
I think this can be closed due to #235
