### ISSUE TITLE
Inline edit without the "OK" and "Cancel" buttons

### ISSUE THREAD

**Issue by MaciejHadam** [vitalets/angular-xeditable#11]
Hi,
Is there an option to automatically update value in a model without confirmation step?
It would be cool to hide those 2 buttons.

**Comment by vitormicillo** [comment]
Hi there
I know this post has already been closed, but the option to hide the buttons still doesn't work.
I try this option in my code     "$.fn.editable.defaults.showbuttons = false;"
but the auto update doesn't work more.
