### ISSUE TITLE
How to restrict editing only for authenticated users?

### ISSUE THREAD

**Issue by ismarslomic** [vitalets/angular-xeditable#114]
Is it easy to enable editing only for those user/admins that are authenticated and otherwise just display the values in non-input fields (div, p, h1, etc)?

**Comment by mitcht** [comment]
It is possible to do this with built in functionality. Using the e-ng-disabled="boolean" value, one can easily enable and disable an xeditable element. Here I have shown it used on a standard text element, as well as a date time picker. https://jsfiddle.net/carcomp/dpf5jb39/1/

**Comment by hwagz** [comment]
@mitcht This did not work. e-ng-disabled did not affect the editability of the particular element at all. I saw somewhere else to use edit-disabled="boolean". This... mostly works. For whatever reason, the exact same code works just fine on an element being ng-repeat'd, and not at all outside of one. So if I have an array of string info from an API I'm iterating through it's fine, but if I have just a single text element, no dice.

**Comment by ckosloski** [comment]
Can you provide a plunker/jsfiddle showing your issue?

**Comment by hwagz** [comment]
Hmm. No I cannot. The code from my project works exactly as it should in the fiddle. I think I've identified another issue that is causing my problems that is not xedit related. 

Here's the fiddle anyway for anyone that wants to see e-ng-disabled and edit-disabled side by side. http://jsfiddle.net/dpf5jb39/12/

The ngRepeat should be
<li ng-repeat="alias in aliases track by $index"> 
        <span editable-text="aliases[$index]" e-name="aliases[$index]"e-required
Fiddle just didn't like "track by $index" for whatever reason.

**Comment by ckosloski** [comment]
The reason your track by index didn't work is because you are using an older version of angular in your fiddle.
