### ISSUE TITLE
How to enable/disable xeditable 

### ISSUE THREAD

**Issue by manojSelvam** [vitalets/angular-xeditable#115]
Is it possible to enable/diasble the xeditable feature. 
something  like: http://vitalets.github.io/x-editable/demo-bs3.html?c=inline#

**Comment by rmariuzzo** [comment]
I was surprised to see it has been added such functionality yet. I'm very interested to contribute to this feature. Currently I have a form where some part can be edited depending on user role.

**Comment by ckosloski** [comment]
I think this can be closed due to #235
