### ISSUE TITLE
weird css style after closing textbox

### ISSUE THREAD

**Issue by chino23** [vitalets/angular-xeditable#116]
When I click to edit the text, and I either change it and save or cancel it, the text is rendered in a bright grey color and much smaller. I'm using the default theme as I don't want the BS stuff.

I use this on different labels, which are themed individually. I don't want this to override anything. 

I tried playing with the xeditable.css to fix this. Funnily, the only way to get rid of this problem is to delete 

```
.editable-hide {
    display: none!important;
}
```

When this is gone, the weird font color and size is gone, but that come with the problem that the old text is not hidden while the text field is shown.

That feels odd. Is this a bug or how can I get rid of this problem?

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
@eugef There has been no follow up, please close.
