### ISSUE TITLE
 x-editable + ng-repeat issue

### ISSUE THREAD

**Issue by anand27** [vitalets/angular-xeditable#117]
I have been exploring Angular X-editable project for a while and came across this odd behavior.

Whenever I click on any one of the 3 'select' components and try to change the value from the dropdown, the method 'showStatus(..)' gets fired for other components as well that are inside the ng-repeat boundary. (which you can check through the console.)

Can you please tell me why is this happening? Am I missing something.. ?

EDITED LINK -> Fiddle : http://jsfiddle.net/hrr4M/4/

https://stackoverflow.com/questions/23478293/why-does-this-happen-in-x-editable-ng-repeat

**Comment by ckosloski** [comment]
Looks like the stackoverflow question was answered.  Please close.

**Comment by ckosloski** [comment]
@eugef I think this issue can be closed.
