### ISSUE TITLE
Call handler when user clicks outside the input

### ISSUE THREAD

**Issue by chamerling** [vitalets/angular-xeditable#118]
Hi,

Is there a way provided by xeditable to call a handler when the user clicks outside of the form (not on button).

For example:

Current behavior:
    User edits a field "test test test" and validate
    User edits the same field "Foobar" and click anywhere outside the field
    -> Edition is canceled and field is still "test test test"

Expected:
Validate data instead of cancel its when user clicks outside

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by trodi** [comment]
@ckosloski , @tlaak notes are still correct.

I expected `blur="submit"` to trigger on more than just the click event, so tabbing through xeditable elements would submit themselves. `e-ng-blur="form.$submit()"` is a workaround, but `$submit()` isn't in the documentation and isn't as clean of a solution.

The updated functionality could be limited to if the user has selected `buttons="no"` (as that's a simpler implementation).

**Comment by ckosloski** [comment]
Support for tabbing was added with pr #590.

@eugef I think this issue can be closed.
