### ISSUE TITLE
editable-bsdate and tabs

### ISSUE THREAD

**Issue by johntom** [vitalets/angular-xeditable#121]
Hi,
I have the a date control using tables on a form and when user tabs from one control to the next they would like to prevent the tab control from staying on date control when it has the focus and just move on to the next field.
Thanks,
John
 tr(ng-repeat='daily in dailies')

```
            td
                span(e-style="width:105px", editable-text='daily.CLAIM_NO', e-typeahead='c.CLAIM_NO as c.CLAIM_NO  for c in claims | filter:$viewValue | limitTo:8',
                e-name='CLAIM_NO', e-form='rowform',  e-required ,onbeforesave="checkNaClaim($data)")
                |{{daily.CLAIM_NO}}


            td
                span(e-style="width:80px",editable-bsdate="daily.WORK_DATE", e-datepicker-popup="MM/dd/yyyy", e-name='date', e-form='rowform', e-required)
                | {{ daily.WORK_DATE | date:"MM/dd/yyyy" }}

            td
                span(e-style="width:140px",editable-select='daily.SERVICE_ID', e-name='SERVICE_ID', e-form='rowform', e-ng-options='s.id as s.name for s in services')
                | {{ showService(daily) }}
```

**Comment by HariBabuThubati** [comment]
Hi I am also facing the same issue ,if you are resolve the please let me know.

**Comment by HariBabuThubati** [comment]
@johntom  : did you get any solutions ? I am adding datepicker on ng-repeat , if i have multiple rows if i click on one row the calender is pooping up in all coloumn which was date picker ,can you please help me out

**Comment by shsrivastava** [comment]
@johntom did you get any solution ? Thanks in advance

**Comment by HariBabuThubati** [comment]
e-form="tableform"  e-name ="input.deathDt" editable-date="input.deathDt" e-ng-modal="input.deathDt" e-is-open="opened[$index]" e-ng-click="open($event,$index)" e-datepicker-popup="dd-MMMM-yyyy" e-max-date="todaysDate" onbeforesave="checkEstateDate($data)">
		{{ input.deathDt | date:"MM/dd/yyyy"}}

$scope.opened = {};
		$scope.open = function($event, elementOpened) {
			$scope.tableform.$dirty = false;
			for (currentOpen in  $scope.opened) {
				if(currentOpen != elementOpened){
					$scope.opened[currentOpen] = false;
				}
			}
			$event.preventDefault();
			$event.stopPropagation();
			$scope.opened[elementOpened] = !$scope.opened[elementOpened];
		};

**Comment by HariBabuThubati** [comment]
@johntom : above is the solution

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
@eugef looks like a solution was posted, please close
