### ISSUE TITLE
Special chars iussue

### ISSUE THREAD

**Issue by brunifrancesco** [vitalets/angular-xeditable#122]
I'm using this component but I got troubles when I insert special chars like accented letters, because they got rendered bad. 
How can I work this out? 
UTF-8 charset is set. 

EDIT: I got it if the local model is empty. If the local model is yet valorized, there's no accent troubles.
Cheers,
Francesco Bruni

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
I tried using UTF-8 characters on the demo site and I don't see any issues.  Maybe you didn't properly set your page encoding to UTF-8.

**Comment by ckosloski** [comment]
@eugef There has been no follow up, please close.
