### ISSUE TITLE
Keep the form in editable state after submit

### ISSUE THREAD

**Issue by vdineva** [vitalets/angular-xeditable#124]
I have a form that in some cases I need to show in editable state after the user submits it.

My markup is:
<form name="filterForm" onhide="filterForm.$show()"> ...

My expectation was that in such case the form would be show in edit state after submission.
What actually happens is, the user submits the form, and the controls are shown in both edit and view state. 
This seems to be a bug (or is there a different way to keep the form in edit stated after submission?)

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
@eugef There has been no follow up, please close.
