### ISSUE TITLE
Create a new editable directive which uses a directive based control

### ISSUE THREAD

**Issue by haris66** [vitalets/angular-xeditable#125]
I have created a module of mine and trying to use xeditable. I have a directive for numeric textbox in my module and trying to create an xeditable directive to wrap it. I have reached to the point that I can click on control to show the popup but then my directive is not compiled to input tag  i.e. the edit panel does not show my control, in sourcecode it is still showing name of my directive.

This is the line in xediable where I think it should get compiled:
$compile(self.editorEl)($scope);

I thought it was due to dependency so I added the dependency of myApp into editable. Here is how is bootstrap angular: angular.bootstrap($app, ['myApp' ,'xeditable']);

Here is how I register xeditable: angular.module('xeditable', ['myApp'])

The code $compile(self.editorEl)($scope); does not set return value in anything. So does this mean that self.editorEl will be updated after compilation?

Am I looking at right area or do you think the error is somewhere else? No exception is being thrown.

Here is my editabl enumeric directive:
angular.module('xeditable').directive('editableNumericbox', ['editableDirectiveFactory',
  function (editableDirectiveFactory) {
      return editableDirectiveFactory({
          directiveName: 'editableNumericbox',
          inputTpl: '<senumerictextbox"></senumerictextbox>',
          addListeners: function () {
              var self = this;
              self.parent.addListeners.call(self);
              // submit textarea by ctrl+enter even with buttons
              if (self.single && self.buttons !== 'no') {
                  self.autosubmit();
              }
          },
          autosubmit: function () {
              var self = this;
              self.inputEl.bind('keydown', function (e) {
                  if ((e.ctrlKey || e.metaKey) && (e.keyCode === 13)) {
                      self.scope.$apply(function () {
                          self.scope.$form.$submit();
                      });
                  }
              });
          }
      });
  }]);

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
@eugef There has been no follow up on this issue, please close.
