### ISSUE TITLE
Change inputs same form

### ISSUE THREAD

**Issue by jllunell** [vitalets/angular-xeditable#133]
Is there a way to acess to other inputs of the same editable Forms. For example, when you change an input change another input automaticaly as a trigger? My problem is with a Editable Table Row, that when i change one input i would like to change another one, but not writting to the model yet. 

And due to the documentantion, i can't find the temporary model object where the form has the values but is wating to be saved to the real model, so i can't modify anything by code.

Thank you.

**Comment by sushil-vishwanathan** [comment]
+1
I think is a very important feature. Any idea how to implement this

**Comment by ckosloski** [comment]
I think you can use an onchange event to update other fields.

**Comment by ckosloski** [comment]
@eugef Please close this issue due to lack of response
