### ISSUE TITLE
Skipping used options

### ISSUE THREAD

**Issue by kliolios** [vitalets/angular-xeditable#134]
Hello,

I am using the editable table.  In the example there are two columns (status and group) that retrieve their options from some scope list.  Is there a way to add new rows that will not display the options used in the rows above?  So for example, since status1 and status2 have been used, then the add row would provide only status3 and status4.  If you edit set the status to status3, then adding a new row would give you only the status4 option.  

Thanks
Dino

**Comment by ckosloski** [comment]
You could probably setup a function that loops through any existing values that are used and removes them from the available list.
Or, create an AJAX call and have your backend query filter out the values already saved to the db (if items are being saved).

**Comment by ckosloski** [comment]
@eugef There has been no follow up, I think this can be closed.
