### ISSUE TITLE
Very simple example fails - editable-text needs editable-form?

### ISSUE THREAD

**Issue by Madd0g** [vitalets/angular-xeditable#138]
I'm getting this error:
     Form with editable elements should have `editable-form` attribute. \<a class="ng-scope ng-binding editable" href="#" editable-text="input.name"\>

All the examples I've seen don't set `editable-form` anywhere and I don't want to either. I'm using the latest version from bower:
    bower angular-xeditable#*       cached git://github.com/vitalets/angular-xeditable.git#0.1.8

EDIT: I do have a form wrapping the page, if I add the attribute `editable-form` to it, the error disappears but it still doesn't work on click (I haven't tried $show, but I want just a little place in my page to be editable, not the entire form).

EDIT2: This is inside an `ng-repeat`, if that matters.

Thanks

**Comment by rainery** [comment]
I had the same error , the problem ta to your html , in closing tags , indents the code , and everything opens closes , if not the error .

**Comment by gae123** [comment]
I am hitting the same issue. @rainery I do not understand you. @Madd0g did you ever figure this out?

**Comment by Madd0g** [comment]
@gae - I ended up removing the wrapping form, if I remember correctly.

NOT an acceptable solution really.

**Comment by yohendry** [comment]
@Madd0g  thanks man, u saved my day

**Comment by eugef** [comment]
Duplicates #6

**Comment by thebillkidy** [comment]
+1 @Madd0g

**Comment by artforlife** [comment]
I am getting this error on a single field of date type. What is interesting, on another page, this works fine. The error seems to have something to do with DOM structure. In particular, I am trying to edit some text within a `<span>` tag.

**Comment by ullakhan** [comment]
I am facing the below issue 
Form with editable elements should have `editable-form` attribute. <span editable-text="user.name" e-form="rowform" onbeforesave="checkName($data, user.id)" e-required="" class="ng-scope ng-binding editable"> 

Here is the scenario:

1. I have Form which has childrens item-list  like Order form has orderLine Items.
2. I want to use the xeditable to the childerItem(orderLineItems) with ngRepeat. and add the child item with AddLineItem Button.

<form name="editForm" role="form" novalidate ng-submit="vm.save()" show-validation>
    div class="form-group">
            <label class="control-label" data-translate="simplytaxaccountantApp.client.companyName" for="field_companyName">Company Name</label>
            <input type="text" class="form-control" name="companyName" id="field_companyName"
                    ng-model="vm.client.companyName"
                    />
                  
        </div>
     
         Item1
         Item2
         Item3 

when click on the Edit button it is not showing the editable row..
I suspect that the parent form is not allowing the child form to get displayed.

**Comment by ullakhan** [comment]
Hi All,

It working fine with just single form not as show in the screenshot. But the problem i have with the nesting form as mentioned earlier.
< Form >
      field 1
      field 2
  
  childItems with ng-repeat
   <table>
      xeditable form on each row
  </table>    
 
Please let me know how to hack this to achieve the required functionality.

Thanks,
Nyamath
![singleform-working](https://cloud.githubusercontent.com/assets/8574568/23104726/44d6b876-f6f9-11e6-9136-4523fe499665.png)

**Comment by ckosloski** [comment]
See if this [comment ](https://github.com/vitalets/angular-xeditable/issues/421#issuecomment-227577623) helps you.

**Comment by ullakhan** [comment]
Mentioned comment helps me to just have a single editable. But in my case I want to wrap three fields into a editable form  for each user object from users list (OrderItemList). This user grid fall inside the main form again which contains other fields too....


![sampleform](https://cloud.githubusercontent.com/assets/8574568/23121767/a45e1d32-f787-11e6-91f9-c747635f8cc3.PNG)

**Comment by ullakhan** [comment]
@ckosloski  this is what i am trying to achive..

http://jsfiddle.net/ullakhan/jynvLfoL/

Please help me in this regard. Thanks..
