### ISSUE TITLE
Xeditable fields added dynamically are not initialized as Xeditable

### ISSUE THREAD

**Issue by ansarianam02** [vitalets/angular-xeditable#139]
I am trying to add dynmic editable field in dropzone.js thumnail part ? now i know that Xeditable fields added dynamicaly are initialize . i am trying it ion angular 

Fiddle:
http://jsfiddle.net/NfPcH/2008/

After click on add Xeditable field , a new field is added but it is not getting initialize.

**Comment by ckosloski** [comment]
@eugef please close, this issue looks like it's answered.
