### ISSUE TITLE
What is the best way to select button elements in cucumber or other automated test

### ISSUE THREAD

**Issue by rdgco** [vitalets/angular-xeditable#143]
I am writing cucumber features and step definitions for a page that uses this directive.

I can set the id of the text area using the e-id attribute and access that element in the step definition by ID. 

However, there does not appear to be a way to set the id's of the save and cancel buttons to serve this purpose. 

Is there an x-path or capybara type query that could be used to select those elements and would be likely to work after future changes to the plugin?

Thanks!

**Comment by ckosloski** [comment]
Did you ever figure this out?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response
