### ISSUE TITLE
xeditabel inside modal not working

### ISSUE THREAD

**Issue by lgt** [vitalets/angular-xeditable#144]
I try to add xeditable to modal but doesn't seems to fire so on I have
<code>
var ModalInstanceCtrl = function($scope, $modalInstance) {
    $scope.product = function(obj, $event) {
        alert('asdsasadasd');
        console.log($event.target);
    };
    $scope.selected = {
        item: $scope.product[0]
    };
    $scope.user = {
        name: 'awesome user'
    };
    $scope.user = {
        name: 'awesome user',
        status: 2
    };
    $scope.statuses = [
        {value: 1, text: 'status1'},
        {value: 2, text: 'status2'},
        {value: 3, text: 'status3'},
        {value: 4, text: 'status4'}
    ];
    $scope.showStatus = function() {
        var selected = $filter('filter')($scope.statuses, {value: $scope.user.status});
        return ($scope.user.status && selected.length) ? selected[0].text : 'Not set';
    };
    $scope.ok = function() {
        $modalInstance.close();
    };
    $scope.cancel = function() {
        $modalInstance.dismiss('cancel');
    };
};</code>

and in my modal 

```
    <!-- editable element -->
            <a href="#" editable-text="user.name">{{ user.name || "empty" }}</a>
            <div id="debug" style="margin-top: 30px">
                {{ user | json }}
            </div>
```

the scope variable is there but xeditable not getting fired

**Comment by ckosloski** [comment]
Is this still an issue?  If so, can you provide a link to a plunkr/jsfiddle?

**Comment by ckosloski** [comment]
@eugef There has been no follow up on this issue, let's close it.
