### ISSUE TITLE
Add an empty option on a editable-select

### ISSUE THREAD

**Issue by jbgury** [vitalets/angular-xeditable#145]
Hello,

Thank you for this implementation. It is great !
I have an issue with the editable-select component. I would like use the possibility to define an empty option or "null" option as described in AngularsJS documentation : 
https://docs.angularjs.org/api/ng/directive/select

Do you have a workaround to use it in collaboration with the e-ng-options attribute ?

Thank a lot

**Comment by kevinhikaruevans** [comment]
+1.

Would be nice to have an attribute in the tag. Something like:
`<span e-style="min-width: 100px" editable-select="device.model_id" e-ng-options="s.id as s.name for s in models" ng-bind="getDeviceModelName(device)" e-null-option="Please select..."></span>`

**Comment by garthylou** [comment]
:+1:

**Comment by NotionCommotion** [comment]
Try using select prepend per http://vitalets.github.io/x-editable/docs.html.  I got it working with a string, but haven't yet done so with a array or object.  Ideally, the menu option text would be one thing (i.e. Select One), and the text displayed after saving could be another (i.e. Add New).

**Comment by ckosloski** [comment]
This was fixed with #463
