### ISSUE TITLE
Able to use popover style of x-editable?

### ISSUE THREAD

**Issue by k-funk** [vitalets/angular-xeditable#146]
http://vitalets.github.io/x-editable/demo-bs3.html
As in this example, there's two modes to using x-editable. Inline and popover/popup.

1: Are these possible with angular-xeditable?
2: Can they be decided in the html, on the element, per element, instead of globally?

**Comment by nikhil-bhandari** [comment]
+1

**Comment by Assada** [comment]
+1

**Comment by petrabarus** [comment]
+1

**Comment by gerzhan** [comment]
+1

**Comment by cadrogui** [comment]
+1

**Comment by Nishchit14** [comment]
+1 Please give this ASAP :+1:

**Comment by t-k-** [comment]
+1

**Comment by itzik-ilan** [comment]
+1

**Comment by igor-smyrnov** [comment]
+1

**Comment by dbrgn** [comment]
I think this is a duplicate of #81.

**Comment by ckosloski** [comment]
@eugef I think this can be closed due to #491
