### ISSUE TITLE
double ng-repeat with $index + editable-text doesn't work

### ISSUE THREAD

**Issue by adoueb** [vitalets/angular-xeditable#153]
Hello,

I'd like to have an editable text and it doesn't work.

My html is like this:

![xeditable](https://cloud.githubusercontent.com/assets/3399861/3715161/29f865f4-15d3-11e4-9cb1-998c1a875cce.png)

Could you please help me ?

Regards,
Agnes.

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
@eugef There has been no follow up on the issue, I think this can be closed.
