### ISSUE TITLE
Local Modal Scope

### ISSUE THREAD

**Issue by dirq** [vitalets/angular-xeditable#154]
How do you access the local modal within an editable-form?  For instance, I have 2 inputs of type number that act like a range.  On the lower end's ngChange I'd like to check if the high end's value.  I haven't been able to figure out how to get to the local, edited model.  Of course I can get to the original $scope but I need the values that have been changed before they are submitted.

**Comment by ckosloski** [comment]
Can this be closed?

**Comment by ckosloski** [comment]
@eugef This question appears answered, please close.
