### ISSUE TITLE
Hook for ng-change

### ISSUE THREAD

**Issue by zigszigsdk** [vitalets/angular-xeditable#156]
It would be nice if you could have something like 

    <a href="#" editable-text="newCategory" ng-change="userAddedCategory(newCategory)">New</a>
    ...
    $scope.userAddedCategory = function(newCategory)
    {
        $scope.selectedProduct.categories.push(newCategory);
    }

**Comment by getkitchendeal** [comment]
there is more thread on this issue in https://github.com/vitalets/angular-xeditable/issues/105

I think you could close this break

**Comment by ckosloski** [comment]
You can use `e-ng-change`
@eugef please close this issue.
