### ISSUE TITLE
HTML in Error Messages

### ISSUE THREAD

**Issue by jeffburton** [vitalets/angular-xeditable#160]
I found a need to embed some html tags in my error messages. The change to xeditable was very simple - add a dependency on $sce, mark the msg as trusted html in setError ($sce.trustAsHTML()), and then change the error div ng-bind to ng-bind-html. 

I only mention it as a possible enhancement and for anyone else who might need this. Also, apologies in advance if I've violated some github protocol here - I'm new to this platform.

**Comment by tekdungtralala** [comment]
+1, waiting for this

**Comment by ckosloski** [comment]
Is this still an issue?
