### ISSUE TITLE
editable-bsdate does not work with the latest ui.bootstrap

### ISSUE THREAD

**Issue by lucassus** [vitalets/angular-xeditable#164]
For some reason the datepicker popup is not beeing opened. Here is demo http://jsfiddle.net/lucassus/j6486p8q/

I forked this jsfiddle from http://jsfiddle.net/NfPcH/23/ which I found on the documentaion page and I upgraded AngularJS from `1.0.8` to `1.2.22` and ui.boostrap from `0.6.0` to `0.11.0`.

**Comment by Light241** [comment]
+1

**Comment by dtam** [comment]
+1

**Comment by sallampalli** [comment]
@lucassus : Hey , good fix, however, I am trying to get this(AngularUI datepicker) working on the editable form http://vitalets.github.io/angular-xeditable/#editable-form
And I am using AgularUIBootStrap 0.11.0, Angular 1.2.13 and Bootstrap 3.0.0 and I can't get this to work. Any thoughts ?

**Comment by hyunlim** [comment]
@lucassus solution still works with angular 1.3.x, ui-bootstrap 0.11.x, and angular-xeditable 0.1.8

**Comment by sallampalli** [comment]
@lucassus : Here is the jsFiddle of the above mentioned stack and I'm not sure why it isnt working with the solution :  http://jsfiddle.net/NfPcH/6518/

**Comment by ganapativs** [comment]
Replace line no:1552 with this code in angular bootstrap UI 0.12.0:

  var keydown = function(evt, noApply) {
        scope.keydown(evt);
      };
      var clicked = function(evt, noApply) {
        scope.clicked(evt);
      };
      element.bind('keydown', keydown);
      element.bind('click', clicked);

      scope.keydown = function(evt) {
        if (evt.which === 27) {
          evt.preventDefault();
          evt.stopPropagation();
          scope.close();
        } else if (evt.which === 40 && !scope.isOpen) {
          scope.isOpen = true;
        }
      };
      scope.clicked = function(evt) {
        scope.$apply(function(){
          scope.isOpen=!scope.isOpen;
        });
      };

Now, datepicker works with click on input element.

**Comment by hroussel** [comment]
+1

**Comment by mmilito** [comment]
+1 -- the workaround does not seem to be working for me either.

**Comment by vpratti** [comment]
Workaround does not work for me either

**Comment by ilbarzo** [comment]
same issue for me, using angular 1.3.15, ui-bootstrap 0.13.0, and angular-xeditable 0.1.8                            
```html
<span editable-bsdate="defannoimp.chiudi" e-name="chiudi" e-form="rowform" e-datepicker-popup="dd-MM-yyyy" onbeforesave="checkChiudi($data, defannoimp.anno)">
    {{ defannoimp.chiudi | date:"dd/MM/yyyy" }}
</span>
```
when edit row and click on field, calendar is not shown

**Comment by slavoroi** [comment]
Same issue for me!
Very similar to libazro code.

**Comment by asakalou** [comment]
Hello guys,
Could you please take a look at this issue http://plnkr.co/edit/6VkbN3lTqUqriPcp7VM9?p=preview
(Datepicker is not opened on calendar button click). 
I've added e-ng-click and it is called twice during calendar button click (both wrapper div and calendar button keep ng-click handler).
This issue prevents from opening picker. Please suggest what is the best way to fix this.

Versions:
xeditable: 0.1.9
angular: 1.3.16
angular-ui-bootstrap 0.12.1

**Comment by ganapativs** [comment]
@asakalou Here is the working code. 

http://plnkr.co/edit/pBnxWiqrLwOG1UNWyTJM?p=preview

I have replaced your bootstrap UI file with modified one.

**Comment by vinhboy** [comment]
@ganapativs thanks for the sample, got this working for me in `angular-ui-bootstrap 0.13.0` and `angular 1.3` without modification to `angular-ui-bootstrap`

**Comment by seksitha** [comment]
This's my solution with editalbe 0.1.8  angular 1.4.0 ui-bootstrap 0.12  after dig deep into ui-bootstrapp document:
    `<span class= "form-control" editable-bsdate="data.date" e-ng-click="opened = !opened" e-class ="form-control" e-is-open="opened" e-datepicker-popup = "dd-MM-yyyy" e-name= "date" >{{data.date}}</span>`

Note: e-class = "form-control" is optional. I add because xeditable is not include when invoked.
e-ng-click and e-is-open is used in ui-bootstrap to toggle the datepicker.
Hope this help!

**Comment by Sampath-Lokuge** [comment]
@seksitha Thanks,It works :)

**Comment by vishalbedre** [comment]
It is problem with X-editable js.

changed x-editable.js 

to  angular-xeditable - 0.1.9

http://plnkr.co/edit/pBnxWiqrLwOG1UNWyTJM?p=preview****
