### ISSUE TITLE
Set a textfield to null, save, and after cancel

### ISSUE THREAD

**Issue by fabiomello** [vitalets/angular-xeditable#170]
If i edit one textfield to null, click to save (occurs one validation error) and after click on cancel, the text appears null.

if i put anything in textfield like 'iaushiausheiuaseh' and occurs validation error, its ok. the error occurs only with null value.

**Comment by ckosloski** [comment]
Is this still an issue?  I just tested this scenario and it appears to be working correctly.

**Comment by ckosloski** [comment]
@fabiomello is this still an issue?

**Comment by fabiomello** [comment]
resolved
