### ISSUE TITLE
Typeahead in bootstrap3

### ISSUE THREAD

**Issue by blabno** [vitalets/angular-xeditable#174]
The docs is using angular-ui 0.6.0, which is based on bs2. The original x-editable docs says that Typeahead works only with bs2. This has mislead me, because i'm using angular-ui 0.11.0 (bs3 based) and i thought that Typeahead is not supported for bs3+angular-xeditable.

Just by accident I found out that Typeahead actually works with bs3 and angular-xeditable, but you must be extra careful about the order of your deps when defining app module.

You must add "xeditable" to your app deps __before__ "ui.bootstrap" like this:

```
angular.module('app',['xeditable','ui.bootstrap']);
```

otherwise, typeahead just won't work for xeditable.

**Comment by MuraliM** [comment]
Do we have any working example with typeahead with id,label pair values and showing a field in x-editable table?

Example, I want to show a product name column in the table with typeahead implementation. Once the user enters the information I need to save the Id of the product and not the name I display in the column.

**Comment by Sampath-Lokuge** [comment]
@blabno Can you share simple example with us ? I have tried it.But not working :( Thanks.

This is the : [Fiddle ](http://jsfiddle.net/sampath_lokuge/NfPcH/14612/)

**Comment by ckosloski** [comment]
This can be closed now that 0.1.2 was released.
