### ISSUE TITLE
blur attribute doesn't work properly with editable form

### ISSUE THREAD

**Issue by julienboulay** [vitalets/angular-xeditable#176]
When adding `blur="cancel"` on an editable rowform, this produces strange behaviours.
* clicking inside an editable-text will cancel editing, 
* clicking on editable-number arrows will cancel editing

An exemple on jsfiddle : http://jsfiddle.net/jboulay/bjhucxLg/

**Comment by ckosloski** [comment]
This was fixed by PR #179.  This can be closed
