### ISSUE TITLE
Allow for CTRL+ENTER to add carriage-return for editable-textarea

### ISSUE THREAD

**Issue by RavenHursT** [vitalets/angular-xeditable#184]
Currently, the behavior is to have enter have default behavior (carriage return) for textareas.  Would be nice to have an option, something like submit-on-enter="true" that would make the text-area submission more intuitive when buttons="no" is set.

If there's a way to do this currently.. would LOVE to hear it!

**Comment by maelfrize** [comment]
+1

**Comment by BenjaminConant** [comment]
I would also like this! Just came across this problem and hitting enter to submit a text area would be awesome.

**Comment by BenjaminConant** [comment]
Hey @RavenHursT and @maelfrize ... just modified my x-editable source to accommodate the request ... I will probubly make a pull request with this but just incase anyone does not want to wait around here is how I did it ... go into your x-editable source and change the xeditableTextarea directive to this. The modifications are down in the autoSubmit function where I check to see if there is a submitOnEnter attr and if there is cause submission to happen on <code>Ente </code> and new lines to happen on <code> Shift + Enter </code> This might not be the best way to do it but it works really well for me. All you need to do after making these modifications is add a <code>submit-on-enter="true"</code> attribute to your editable-textarea element. 

<pre> 
angular.module('xeditable').directive('editableTextarea', ['editableDirectiveFactory',
  function(editableDirectiveFactory) {
    return editableDirectiveFactory({
      directiveName: 'editableTextarea',
      inputTpl: '<textarea></textarea>',
      addListeners: function() {
        var self = this;
        self.parent.addListeners.call(self);
        // submit textarea by ctrl+enter even with buttons
        if (self.single && self.buttons !== 'no') {
          self.autosubmit();
        }
      },
      autosubmit: function() {
        var self = this;
        self.inputEl.bind('keydown', function(e) {
          if (self.attrs.submitOnEnter) {
            if (e.keyCode === 13 && !e.shiftKey) { 
              self.scope.$apply(function() {
                self.scope.$form.$submit();
              });
            }
          } else if ((e.ctrlKey || e.metaKey) && (e.keyCode === 13)) {
              self.scope.$apply(function() {
                self.scope.$form.$submit();
              });
          }
        });
      }
    });
}]);
</pre>

**Comment by maelfrize** [comment]
@RavenHursT Thanks for sharing your solution!

**Comment by RavenHursT** [comment]
@maelfrize, @BenjaminConant did it..

@BenjaminConant wondering if the opposite behavior might be better/worse?  Maybe allow for both.  For example.. Facebook behaves as you've mentioned, (shift+enter for new lines, enter for submission).  But a number of other apps (like gitHub and Gmail) behave in the opposite (kind've): Enter for new lines, CMD+Enter (on a Mac) for submission.

I kind've prefer the latter, but that's just me.

**Comment by nguyennam0705** [comment]
asdasd
