### ISSUE TITLE
form will just not submit

### ISSUE THREAD

**Issue by xonbugeja** [vitalets/angular-xeditable#185]
this is my last resort, i've been on this for the last couple of days, alas it might be the dumbest thing but i honest to god have no idea in the slightest why this is not working, so please forgive my ignorance in advance. 

    <div ng-repeat='task in CurrentOIDs | filter:criteria | orderBy:OrderField:ReverseSort'> 
            
            <div class='row {{!areCollapsed[task.OIDid] | selected}}' style='background-color: {{ task.Status | color }};' ng-click="checkCollapse(task.OIDid, !rowform.$visible);">
                <div style='width: 5%;' class='cell OIDid'>{{ task.OIDid }}</div>
                <div style='width: 5%;' class='cell'><span editable-select="task.Priority" e-id='priorityInput' e-name="priority" e-form="rowform" e-ng-options="p.value as p.text for p in priorities">{{task.Priority}}</span></div>
                <div style='width: 13%;' class='cell'><span editable-text='task.Topic' e-name='topic' e-form='rowform' e-required e-list="Topics">{{ task.Topic }}</span></div>
                <div style='width: 20%;' class='cell'><span editable-text='task.Category' e-id='categoryInput' e-name='category' e-form='rowform'  e-required e-list="Categories">{{ task.Category }}</span></div>
                <div style='width: 35%;' class='cell'><span editable-text='task.Task' e-id='taskInput' e-name='task' e-form='rowform'  e-required>{{task.Task}}</span></div>     
                <div style='width: 6%;' class='cell'>{{ task.Added }}</div>
                <div style='width: 6%;' class='cell'>{{ task.Target }}</div>
                <div style='width: 5%;' class='cell'><span editable-text='task.Owner' e-name='owner' e-form='rowform' e-required e-list="Owners">{{ task.Owner }}</span></div>
                <div style='width: 5%;' class='cell Status'><span editable-number='task.Status' e-min='0' e-max='100' e-name='status' e-form='rowform' e-required>{{ task.Status }}%</span></div>
            </div>
            <div collapse='areCollapsed[task.OIDid]'>
                <div style='height: 30px;' ng-show='rowform.$visible'>
                    <form editable-form name="rowform" onbeforesave='saveTask($data, task.OIDid)'>
                        <button id="saverowedit" type='submit' ng-disabled="rowform.$waiting">
                            <?php include("svg/success.svg")?>
                        </button>
                        <button id="cancelrowedit" type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()">
                            <?php include("svg/failed.svg")?>
                        </button>
                    </form>
                </div>
                <div style='height: 30px;' ng-show='!rowform.$visible'>
                  <button id='editButton' style='width: 25%;' title="Edit" ng-click="rowform.$show()"><?php include("svg/edit.svg")?></button> 
                   <button id='archiveButton' style='width: 25%;' title="Archive"><?php include("svg/archive.svg")?></button>
                   <button id='mailingButton' style='width: 25%;' title="MailingList"><?php include("svg/mail.svg")?></button>
                   <button id='historyButton' style='width: 25%;' title="History"><?php include("svg/history.svg")?></button>
                </div>
                
            </div>

and the method in my scope, 

    $scope.saveTask = function (data, id) {
                  console.log(id);
                  console.log(data);
                  angular.extend(data, $scope.CurrentOIDs[id]);
                  return true;
                };

i am on the verge of tears, i hbave no idea why this will not work, and i mean not in the very slightest, the entire thing just ignores the my saveTask method alltogether, it just doesn't care. :"(

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by Sijan117** [comment]
No,  to be honest I forgot exactly what the issue was, but am sure it was not related to xeditable itself, seeing this 2 years later I'm thinking it was probably something stupid in my code back then. Apologies for never updating the issue.

**Comment by xonbugeja** [comment]
No, to be honest I forgot exactly what the issue was, but am sure it was not related to xeditable itself, seeing this 2 years later I'm thinking it was probably something stupid in my code back then. Apologies for never updating the issue.
