### ISSUE TITLE
Manual trigger + regular trigger = doesn't work

### ISSUE THREAD

**Issue by njenia** [vitalets/angular-xeditable#186]
I need a text input field to be triggered programaticaly (from some ng-click for exampe) and also to be triggered from a click (like it does by default).
The manual way is supposed to be done using the e-form directive. The problem is that having this attribute wraps the input with a form, and this cancels the clickability of the field. This can be seen in the following code:
// bind click - if no external form defined
          if(!attrs.eForm) {
            elem.addClass('editable-click');
            elem.bind('click', function(e) {
              e.preventDefault();
              e.editable = eCtrl;
              scope.$apply(function(){
                scope.$form.$show();
              });
            });
          }

from directive.js.

It would be really nice having those two options simultaneously. Currently i'm just using jquery to manually click() the element, instead of using pure angular..

**Comment by ckosloski** [comment]
@eugef I think this can be closed.
