### ISSUE TITLE
Safari date time picker styling is out

### ISSUE THREAD

**Issue by cccastle** [vitalets/angular-xeditable#189]
When clicking on the editable date and clicking down to change the month the Done button is in the wrong position 

![image](https://cloud.githubusercontent.com/assets/7021022/4717459/30509f9a-5915-11e4-96e7-8b3c00126bbf.png)

**Comment by ckosloski** [comment]
This is working correctly with the latest version of angular-xeditable and angular-ui-bootstrap.
@eugef please close
