### ISSUE TITLE
Duplicated days in bsdate

### ISSUE THREAD

**Issue by landrade** [vitalets/angular-xeditable#190]
On October 2014, The day 18 is duplicated like the print bellow.

![screen shot 2014-10-21 at 11 56 23 am](https://cloud.githubusercontent.com/assets/776777/4719526/538d81f2-592a-11e4-9e8e-59639d057f59.png)

**Comment by ckosloski** [comment]
This is working correctly with the latest version of angular-xeditable and angular-ui-bootstrap.
@eugef please close.
