### ISSUE TITLE
Checking model state

### ISSUE THREAD

**Issue by mparisi76** [vitalets/angular-xeditable#191]
I have tried to search for a suitable answer for this but have not been successful. In my Angular app, I have an xeditable text input that I want to only perform database updates if the value has changed after the user has clicked into it and then clicked out. What's the easiest way to determine whether or not the value is dirty or clean?

**Comment by ckosloski** [comment]
It looks like you might be able to manually check the dirty flag for the input.  See this [comment](https://github.com/vitalets/angular-xeditable/issues/318#issuecomment-114530112)

**Comment by ckosloski** [comment]
@eugef please close due to lack of response
