### ISSUE TITLE
New Features: Image editable field

### ISSUE THREAD

**Issue by Fabryprog** [vitalets/angular-xeditable#194]
Hello everyone,

can you enable another field "image" to inline edit of a image field?

King regard

**Comment by tiagocedrim** [comment]
Would be fantastic

**Comment by marciogm** [comment]
Look that [editableImabe](https://github.com/marciogm/angular-xeditable/commit/9ab14233f467045b9156fd5a3b5a589d79a9215f#diff-90635473805044e26bceb2f7ffecfa82R243).

I'm not expert in angular, but i added this directive for my personal use, i need to modify some things for a better code, for example: put the handleFileSelect from controller inside the directive.
if anyone have some feedback, please, tell me.

**Comment by ckosloski** [comment]
Pull requests are welcome :)

**Comment by ckosloski** [comment]
@eugef I feel like this can be closed.  The referenced image editor is no longer supported.  Not sure if this is needed in the project.
