### ISSUE TITLE
xeditable without changing the text style

### ISSUE THREAD

**Issue by mdarveau** [vitalets/angular-xeditable#197]
Hi,

I would like to add xeditable to some elements of my page but I don't want to affect the style of the editable text. For example, I would like to allow editing of Bootstrap's panel headings with `panel-primary` class applied. With current xeditable links, this makes a blue text on blue background and is not usable.

If I comment the following from the xeditable css, it works great:

```
.editable-click, a.editable-click {
    text-decoration: none;
    color: #428bca;
    border-bottom: dashed 1px #428bca
}
```

However, I would rather not alter the original xeditable css. Is there a way to skip the color and border override that is included in angular-xeditable css? Is it simply that I should not use the default css file and customize one myself?

Thanks

**Comment by ckosloski** [comment]
Just include your own css file that overrides the xeditable css classes your want changed for your site.

**Comment by ckosloski** [comment]
@eugef This question is answered, please close.
