### ISSUE TITLE
use xeditable with a ui-bootstrap popover to help user : no update of model

### ISSUE THREAD

**Issue by kirakishin** [vitalets/angular-xeditable#198]
Hello,

i beleave in angular-xeditable !..
But i cannot find a way to display a popover when the user focus the input.
Indeed the popover works but the model cannot be updated with the added directive.

here a jsfiddle : http://jsfiddle.net/4aw81nwr/

can anyone help me please ?
thks

**Comment by ckosloski** [comment]
This works with the latest versions of angular/ui-bootstrap/bootstrap/xeditable.  Here is the [jsfiddle](http://jsfiddle.net/ckosloski/4k4m3nen/6/)
