### ISSUE TITLE
Sorting and Pagination

### ISSUE THREAD

**Issue by dirksen** [vitalets/angular-xeditable#200]
I like this library so far, but it doesn't seem to support sorting or pagination. Can it be done? Any examples?

**Comment by bbrown** [comment]
I would recommend using [Smart-Table](http://lorenzofox3.github.io/smart-table-website/) to provide the sorting and pagination. They work well together—I'm using them together right now.

**Comment by ckosloski** [comment]
@eugef This question is answered, please close.
