### ISSUE TITLE
Need xeditable Combobox

### ISSUE THREAD

**Issue by gmarshall56** [vitalets/angular-xeditable#204]
This is just a suggestion:  Create an exeditable combobox - one of those dropdown / select controls that allows you to enter a new value.  For example see  http://chakrabarty.com/pp_editable_dropdown.html#3

Thank you.
Gary

**Comment by ckosloski** [comment]
This is a good idea, but do you have a better control that could be added.  The one you linked to doesn't seem that good (to me).
There is ui-select that is supported and may do what you need: https://github.com/angular-ui/ui-select/wiki/ui-select

**Comment by piotr-dobrogost** [comment]
@ckosloski 
I was interested in this as well and it doesn't seem like ui-select allows entering new value :(

**Comment by ckosloski** [comment]
The issue with bootstrap-combobox is that is written for jquery and not angular
