### ISSUE TITLE
Call validation after focus lost

### ISSUE THREAD

**Issue by mlito** [vitalets/angular-xeditable#208]
As I found in examples : there is onbeforesave attribute used for local validation. But as I understand validator called only when button "OK" pressed. My question : How can I  cause validator to be called after edit lost focus ( and buttons are not shown ) ? 
Thanks in advance

**Comment by ckosloski** [comment]
What you need to do is set `blurElem='submit'`

**Comment by ckosloski** [comment]
@eugef This question is answered, please close.
