### ISSUE TITLE
How do you force a table cell to load in its editable view on page load as well as when it is clicked?

### ISSUE THREAD

**Issue by rjayaram** [vitalets/angular-xeditable#209]
Eg one of my table columns in my editable form is a checkbox. When I click on the row, the column display a checkbox. I want it to dispay a checkbox even when the form is just loaded.

```
<td>
    <span editable-checkbox="user.isEligible" e-type ="checkbox" e-name="isEligible" e-form="rowform">
      {{ user.isEligible || 'false' }}
    </span>

  </td>
```

**Comment by ckosloski** [comment]
Not sure if you can only display one element of a form as editable.  Is this still an issue for you?

**Comment by ckosloski** [comment]
@eugef please close due to lack of response
