### ISSUE TITLE
WYSIWYG directive - easy to add?

### ISSUE THREAD

**Issue by amish-patel** [vitalets/angular-xeditable#21]
Really nice work.

I was wondering if this can be extended to WYSIWYG.

http://vitalets.github.io/x-editable/demo.html?c=inline

I need that in one of my projects in an editable form. Is it easy to extend to few more widgets like WYSIWYG? If this is not something that you plan on doing, pointers to extending it would be appreciated.

Thanks!

**Comment by geoidesic** [comment]
@vasya10 any luck getting the textAngular styles to work?

**Comment by geoidesic** [comment]
@ashernevins Any chance you could show your code for how you removed the buttons and added them as toolbars?

**Comment by pdonorio** [comment]
+1

An editable-wysiwig should be a must :)

I worked a little with textAngular and found some limitations. Just for the record, i am testing now [ng-wysiwyg](http://psergus.github.io/ngWYSIWYG/) which - at first impression - seems to cover more options.

Thanks for the great work!

**Comment by mitcht** [comment]
Closed as being too old
