### ISSUE TITLE
Need xeditable in table with ui.select is put in a cell

### ISSUE THREAD

**Issue by anhtata** [vitalets/angular-xeditable#211]
When I worked with ng-repeat to render data in table tr . I need to edit in a cell with data is pulled from ui.select with multiple data in this select (picture, text) . I read from documents of xeditable currently only support typehead or select. It is not enough. when ui.select is appeared.

Many thanks if any guys can tell me way to reach that issue.

**Comment by JobaDiniz** [comment]
+1 for support [ui.select](https://github.com/angular-ui/ui-select)

**Comment by zhendong590** [comment]
i find a way to fix it.
you can use a [file](https://raw.githubusercontent.com/zhendong590/ui-select4xeditable/master/directive-ui-select.js) and add new elements on html like this
```html
<span
        editable-ui-select="ma.owners"
        e-form="manualRowForm"
        e-name="owners"
        name="owners"
        theme="bootstrap"
        e-ng-model="ma.owners"
        >
    <editable-ui-select-match placeholder="input names" style="width: 99px">
        {{$select.selected.nick || sc.expectConfirmor.nick}}
    </editable-ui-select-match>
    <editable-ui-select-choices repeat="user in task.allUsers" refresh="funcAsync($select.search)" refresh-delay="500">
        {{user.nick}}/{{user.realName}} - {{user.empId}}
    </editable-ui-select-choices>
</span>
```

**Comment by JobaDiniz** [comment]
Looks great. Why don't you make a pull request for this?

**Comment by zhendong590** [comment]
i will make a test on my local

**Comment by cina2012** [comment]
i a same problem.
model value is not updated.
can you help me?
tnx.

**Comment by rafa-aguilar** [comment]
I have the same problem @cina2012 :(
