### ISSUE TITLE
Integrate with Angular-strap's date and time picker

### ISSUE THREAD

**Issue by phuna** [vitalets/angular-xeditable#217]
Hi,
In my project I change date and time picker to use angular-strap's corresponding ones because I feel angular-strap is easier to use and more active development. Changes were easy and result is good so far. If you want to include it in the code, I'll make a PR. 

Best regards,

**Comment by bbrown** [comment]
This is possibly just a documentation issue. I used angular-strap via the following code (prepending 'e-' seems to act as a passthrough to the underlying input element):

`<span editable-bsdate="event.date" e-name="date" e-form="addform" ng-model="event.date" e-data-date-format="MM/dd/yyyy" e-data-date-type="number" e-data-autoclose="1" e-bs-datepicker>`

**Comment by forkwhilefork** [comment]
Wow, thanks so much bbrown! That really helped me a lot. I'm still getting the Save and Cancel buttons, though. Any idea how to disable those?

**Comment by ckosloski** [comment]
To turn off the buttons you do `buttons='no'`

**Comment by ckosloski** [comment]
@eugef This question is answered, please close.
