### ISSUE TITLE
e-max not validating/ throwing error

### ISSUE THREAD

**Issue by ghost** [vitalets/angular-xeditable#218]
Hi,

I have been trying to use e-max with editable-number, If input value exceeds the max value it has to throw error, instead it's updating with empty value.

Kindly suggest..

http://jsfiddle.net/69w42ouj/

Ajju

**Comment by robertscholz** [comment]
Please se my comment on issue #76.

**Comment by ckosloski** [comment]
@eugef since #76 was closed, this can be closed.
