### ISSUE TITLE
Checklist orderBy checked items

### ISSUE THREAD

**Issue by mackelito** [vitalets/angular-xeditable#220]
Hey!
Wondering how to go about to orderBy the editableChecklist so that checked items are at the top of the list?

Note: I have added a search field as we have really long lists :+1: 

Here is a fiddle for it:
http://jsfiddle.net/NfPcH/4765/

**Comment by ckosloski** [comment]
Take a look at this - http://stackoverflow.com/questions/39244079/how-to-order-checked-checkbox-at-the-top-of-the-list-in-angularjs
