### ISSUE TITLE
can't define form in thead using ng-repeat

### ISSUE THREAD

**Issue by jengwood** [vitalets/angular-xeditable#221]
I'm trying to do a column edit using ng-repeats to generate the columns, with the form defined in thead and some properties in the body for editing.

I had no problem defining the form object for a row edit using ng-repeat, one form for each row, but when doing it for each column it seems like the form controller doesn't get added to the scope, so the x-editable fields can't reference it using $parse(attrs.eForm)(scope);

Here's a JSfiddle showing the problem, only one item in the ng-repeat, and none of its properties are being referenced. Just one
with the form inside works, but changing to doesn't. Comments in the html pointing to the two lines.

http://jsfiddle.net/cwbk0aao/

Any help would be greatly appreciated, thanks!

**Comment by ckosloski** [comment]
I think you have the form declaration incorrect, please take a look at the form column example - http://vitalets.github.io/angular-xeditable/#editable-column

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response
