### ISSUE TITLE
inputTpl from themes.js isn't propagated

### ISSUE THREAD

**Issue by akarienta** [vitalets/angular-xeditable#223]
I found this issue and I think it is a bug. I'm trying to define my own theme, however, if I define something in object `inputTpl` in `themes.js` (in the object with my own theme) there is no propagation and this definition has no effect. Possible fix in `EditableController` `render()` function:

change this

``` javascript
//build input
self.inputEl = angular.element(self.inputTpl);

//build controls
[...]
self.controlsEl.append(self.inputEl);
```

into this

``` javascript
//build input
self.inputEl = angular.element(self.inputTpl);
self.inputThemeEl = angular.element(theme.inputTpl);
self.inputThemeEl.append(self.inputEl);

//build controls
[...]
self.controlsEl.append(self.inputThemeEl);
```

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
I just tried the fix listed above and it did not work.  Since the default theme inputTpl is blank, nothing gets displayed.

**Comment by ckosloski** [comment]
@eugef please close due to lack of response
