### ISSUE TITLE
change input type dynamically 

### ISSUE THREAD

**Issue by Revln9** [vitalets/angular-xeditable#227]
Hi ,

is there a way to change the input type depending on a random scope value?

like if the field is a string display editable-text input or if it's a number display editable-number input

**Comment by anshul0212** [comment]
same issue I am facing. I want editable-text if type is text and editable-select if type is group of strings. How can we achieve this. Any suggestions are welcome.

Thanks
Anshul

**Comment by Revln9** [comment]
Hi , custom directive is the answer , here's an example  , you need to put this inside an ng-repeat of your input fields

.directive('formspecs', function ($compile , $filter) {

var htmlrange	= '<label class="control-label">{{incat.name}}</label><a   editable-range="{{incat.value}}"  e-type="{{incat.type}}" e-max="{{incat.max}}" e-step="{{incat.estep}}"  >  </a> <span  ng-hide="range" class="pull-right"> {{incat.value}} {{incat.unit}} </span><hr> '

var htmltext	= '<label class="control-label">{{incat.name}}</label><a   editable-text="{{incat.value}}" e-type="{{incat.type}}"> </a> <span class=" pull-right "> {{incat.value}} </span><hr>'
   	var htmlnumber	= '<label class="control-label">{{incat.name}}</label><a   editable-number="{{incat.value}}" e-type="{{incat.type}}"  e-max="{{incat.max}}" e-min="{{incat.min}}" e-step="{{incat.estep}}" > </a> <span  ng-hide="numberform.$visible" class=" pull-right"> {{incat.value}} {{incat.unit}}</span><hr>'

var htmldate	= '<label class="control-label">{{incat.name}}</label><a   editable-date="{{incat.value}}" e-type="{{incat.type}}"> </a>  <span class="lead"> {{incat.value}}</span><span  ng-hide="numberform.$visible" class=" pull-right"> {{incat.value}} {{incat.unit}}</span><hr>'

var htmlselect	= '<label class="control-label">{{incat.name}}</label><a   editable-select="{{incat.value}}" e-buttons="no"  e-ng-options="s as s for s in incat.options" >    </a> <span  ng-hide="numberform.$visible" class=" pull-right"> {{incat.value}} {{incat.unit}}</span><hr> '


    var getTemplate = function(contentType) {
        var template = '';

console.log(contentType)
        switch(contentType) {
        	 case 'select':
                template = htmlselect;
                
                break;
            case 'text':
                template = htmltext;
                break;
            case 'radio':
                template = htmlradio;
                break;
            case 'range':
                template = htmlrange;
                break;
            case 'date':
                template = htmldate;
                break;
            case 'number':
                template = htmlnumber;
                break;
            case undefined:
                template = htmltext;
                
                break;    



        }

        return template;
    }

   

    var linker = function(scope, element, attrs) {


    element.html(getTemplate(scope.incat.type)).show();

    $compile(element.contents())(scope);

    }

    return {
        restrict: "EA",
        link: linker,
        scope: '=',
        replace:true,
        data:'=showStatus',
    };
});

hope it helps !

**Comment by ckosloski** [comment]
@eugef This question is answered, please close.
