### ISSUE TITLE
Attribute name "editable-form" associated with an element type "form" must be followed by the ' = ' character.

### ISSUE THREAD

**Issue by siddarthsah** [vitalets/angular-xeditable#229]
I am getting the following error:
"Attribute name "editable-form" associated with an element type "form" must be followed by the ' = ' character."

Any idea what could be the reason of this error message?
Here is the form element in my code.

I found in stackflow that people were getting this error when they don't have an editable-form attribute.
http://stackoverflow.com/questions/24996429/form-with-editable-elements-should-have-editable-form-attribute
Thanks!
-Sid

```
                        <form editable-form name="rowform" ng-show="rowform.$visible" class="form-buttons form-inline">
                          <button type="submit" ng-disabled="rowform.$waiting" class="btn btn-primary">
                            save
                          </button>
                          <button type="button" ng-disabled="rowform.$waiting" ng-click="rowform.$cancel()" class="btn btn-default">
                            cancel
                          </button>
                        </form>
```

**Comment by ckosloski** [comment]
You have to have `editable-form="rowform"`

**Comment by ckosloski** [comment]
@eugef This question is answered, please close.
