### ISSUE TITLE
Getting editable-form behavior without using form tags

### ISSUE THREAD

**Issue by Yacob** [vitalets/angular-xeditable#234]
I'm working on a page that is nested inside of a form on a master page and would like the editable-form behavior but can not use a form because nested forms cause undefined behavior.  
http://jsfiddle.net/NfPcH/5711/

**Comment by thaoula** [comment]
Hi Yacob,

I know you posted this a while ago .. but have tried making the second form an ng-form rather than a form?

Regards,
Tarek

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by Yacob** [comment]
I don't remember sorry

**Comment by ckosloski** [comment]
Can you close the issue then?

**Comment by Yacob** [comment]
Closed issue. Also with very brief testing it looks like using the inner form an ng-form fixes the problem.
