### ISSUE TITLE
How to select all text when editable text initially shown?

### ISSUE THREAD

**Issue by dlwhiteman** [vitalets/angular-xeditable#236]
I am following the table example where an edit button opens an editor on an entire row of controls.  When the editors are opened, the cursor is at the end of the text that is pre-populated by ng-model.  I would like instead for the text to be selected when the editor opens, so that when the user starts typing, the previous text is deleted.  I don't see any methods or properties for achieving this.  How can I do this?

**Comment by Madd0g** [comment]
there's an event called onshow, you can pass the $form and do stuff with $editables

I just did this `onshow="selectAll($form)"`: 

    $scope.selectAll = function (form)
    {
        var input = form.$editables[0].inputEl;
        setTimeout(function () { input.select(); }, 50);
    };

**Comment by langdonx** [comment]
It seems like this should be the default behavior, or at least an app.run configurable, not something you'd have to add to every field.

Not only does it make editing the text easier, it would also make keyboard navigation easier (especially if there was a .focus() called again back to the non-editable element on onhide).

**Comment by ckosloski** [comment]
In your `app.js` set `editableOptions.activate = 'select';`

**Comment by ckosloski** [comment]
@eugef question answered, please close
