### ISSUE TITLE
{{ }} hard-coded instead of using $interpolateProvider.startSymbol() and endSymbol()

### ISSUE THREAD

**Issue by hectoroso** [vitalets/angular-xeditable#239]
In xeditable.js there are a couple of instances where the code delimiters {{ }} are hard-coded instead of using $interpolateProvider.startSymbol() and endSymbol(), which causes the code to break for  developers that have changed the default delimiters, e.g. to [[ ]]. 

They're found in the directive `editableRange` at line 180:

    this.inputEl.after('<output>{{$data}}</output>');

and the directive `editableRadiolist` at line 200:

    '<input type="radio" ng-model="$parent.$data" value="{{'+parsed.locals.valueFn+'}}">'+

**Comment by eugef** [comment]
Fixed by #500
