### ISSUE TITLE
#IE8 : 'Error: This command is not supported' with e-type="password"

### ISSUE THREAD

**Issue by wizou** [vitalets/angular-xeditable#240]
When I try to use e-type="password" with IE8, the browser displays this error when I click on the text to edit the field:

<code>Error: This command is not supported.</code>

Here is my test code:

```<a editable-text="user.password" e-type="password" e-required>********</a>```

NB: This code works fine with Chrome, Firefox, Safari, IE9+

Thanks!

**Comment by wizou** [comment]
It seems like we can't change dynamically a type of an input in IE8 :(

By adding "password" as an allowed type in the x-editable module and by changing the attribute "editable-text" by "editable-password" all is working in IE8+, Chrome, Firefox, Safari :+1: 

```var types = 'text|email|tel|number|url|search|color|date|datetime|time|month|week|password'.split('|');```

```<a editable-password="user.password" e-required>********</a>```

**Comment by ckosloski** [comment]
Password support was fixed in 0.1.11.
