### ISSUE TITLE
A slight typo in a line of controller code on the demo site: EditableTableCtrl

### ISSUE THREAD

**Issue by ebley** [vitalets/angular-xeditable#241]
In the sub-function : app.controller('EditableTableCtrl', function($scope, $filter, $http, $q) {

When the line is saved - it should say       results.push($http.put('http://127.0.0.1:3001/api/Tblbudgetxypoints', newuser));      //you had $http.push 

For a noob - this took an hour to figure out. Learned lots about rest and strongloop - but… alas - thanks for the code so far. It has taught me a lot. Thanks for posting all that.

**Comment by ckosloski** [comment]
I think this can be closed.  I no longer see any references to $http.push in the documentation.
