### ISSUE TITLE
angular-xeditable Date is not working with (AngularUI Bootstrap 0.11.0 + Bootstrap 3)

### ISSUE THREAD

**Issue by sallampalli** [vitalets/angular-xeditable#248]
The Home page mentioned the Angular UI bootsrap version 0.11.0, but the fiddle on the home page uses 0.6.0. The date is not working with the combinationed mentioned in the homepage.

Here is a fiddle of the bug : http://jsfiddle.net/NfPcH/6510/

**Comment by cpursley** [comment]
I'm experiencing the same issue.

**Comment by phpniki** [comment]
+1 it open one time

**Comment by sebloix** [comment]
I'm having the same issue. I can't get the datepicker to open. It does work perfectly outside xeditable though...

**Comment by phpniki** [comment]
i solved the problem sample code : 
                                    <span editable-bsdate="staff.birth_issue_date" e-name="birth_issue_date" 
                                          class="form-control"
                                          e-type="text1"
                                          e-is-open="opened.$data" 
                                          e-ng-click="open($event,'$data')"                                          
                                          e-datepicker-popup-persian="{{format}}" 
                                          e-datepicker-options="dateOptions" 
                                          e-date-disabled="disabled(date, mode)" 
                                          e-close-text="بسته"
                                          e-current-text="امروز"
                                          e-clear-text="حذف"
                                          e-name="birth_issue_date" 
                                          e-ng-bootstrap-fix="staff.birth_issue_date"
                                          >{{ staff.birth_issue_date | persianDate:'yyyy/MM/dd'}}

                                    </span>

                $scope.opened = {};

                $scope.open = function($event, elementOpened) {
                    $event.preventDefault();
                    $event.stopPropagation();

                    $scope.opened[elementOpened] = !$scope.opened[elementOpened];
                };

**Comment by HariBabuThubati** [comment]
@phpniki :Thanks , I am facing an issue,date picker  in ng-repeat , if have multiple rows ,if i click on one cloumn the calnder is popping up in all remaining columns.

**Comment by vishalbedre** [comment]
It is problem with X-editable js.

changed x-editable.js

to angular-xeditable - 0.1.9

http://plnkr.co/edit/pBnxWiqrLwOG1UNWyTJM?p=preview****

**Comment by ckosloski** [comment]
What issue are you trying to show?  I am not seeing any errors in the console and I am able to select a different date in the popup.

**Comment by ckosloski** [comment]
@eugef please close.  bs-date is working with the current version of xeditable and uibootstrap
