### ISSUE TITLE
keep caret position if editable-text is an input text/textarea

### ISSUE THREAD

**Issue by enapupe** [vitalets/angular-xeditable#249]
The proposed feature diff is at https://github.com/vitalets/angular-xeditable/compare/master...enapupe:keepCaretPosition?expand=1

It persists the caret position if the source element has the property `selectionStart`, thus not breaking usability of text inputs..

needs some tweaks especially on the `onfocus` declaration, since it is being re-declared every time.

do you think this feature is able to be merged? if yes I can finish these tweaks and submit a pr.
ty

**Comment by ckosloski** [comment]
I looked at the diff posted above and it states there are no differences.  The feature appears to have been merged.  
@eugef please close.
