### ISSUE TITLE
Question about end-time

### ISSUE THREAD

**Issue by rom16rus** [vitalets/angular-xeditable#252]
I can set the e-end-time to editable-date only if i change editable-date to editable-bsdate?

**Comment by ckosloski** [comment]
editable-bsdate is the ui-bootstrap datepicker and doesn't have a time option. 
The html5 date input has been deprecated and is no longer supported.
You could try using editable-combodate for a date/time picker.

**Comment by ckosloski** [comment]
@eugef please close
