### ISSUE TITLE
Question about activate and delete text

### ISSUE THREAD

**Issue by kotmatpockuh** [vitalets/angular-xeditable#253]
I have one question.
Here is my view:

`<h3 editable-text="article.Name" class="name" onbeforesave="checkName($data)" onaftersave="updateArticleQuery()" title="Click to edit" dotdotdot data-ng-bind="article.Name" data-e-placeholder="Enter your article name">  
    <p data-ng-bind="article.Name"></p>
</h3>`

how could i: 
automatically run xeditable form on page load?
clean text (article.Name) when my xeditable is active?

why i need this:

for example i have default article name and when page load i need to do, that when user edit this name -> so that when xeditable form is active: all data from there is cleaned and only placeholder is shown (for example if new article).

is it real to do? and how?

**Comment by kotmatpockuh** [comment]
i mean how to clean $data with onshow method?

**Comment by ckosloski** [comment]
If you have a form, you can just do `theNameOfYourEditableForm.$show()`.
If you want to reset the data on the form, just reset your model.

**Comment by ckosloski** [comment]
@eugef I think it's safe to close this issue.
