### ISSUE TITLE
Repo still maintained by owner?

### ISSUE THREAD

**Issue by CEikermann** [vitalets/angular-xeditable#254]
Hey,

is the repo still active maintained by the owner? Because there are many open pull requests without any answer from the owner.

Otherwise maybe somebody could fork this repo and merge some pull requests. Would like to fix some incompatible issues with angular 1.3.9 and the date input.

Best regards

**Comment by Painyjames** [comment]
Hi there,

I asked Vitaly if he could add me as contributor, which he did yesterday.
I'm currently merging pull requests. One of this is a fix for the issue you are mentioning.
I'll try to have it done before the beginning of next week.

Cheers.

**Comment by CEikermann** [comment]
Perfect, thank you for taking the responsibility
