### ISSUE TITLE
editable-bsdate not working in editable form (see jsfiddle)

### ISSUE THREAD

**Issue by dretske** [vitalets/angular-xeditable#255]
I can't seem to get the editable-bsdate working within an editableform.

See jsfiddle below:

http://jsfiddle.net/yvanqt4a/

**Comment by stephenstroud** [comment]
I have this issue also with bootstrap 3, I found this information: 
"Date control is implemented via Angular-ui bootstrap datepicker.
Currently it has only Bootstrap 2 version, Bootstrap 3 version is in progress."
https://github.com/vitalets/angular-xeditable/blob/master/docs/demos/bsdate/desc.md

**Comment by vishalbedre** [comment]
It is problem with X-editable js.

changed x-editable.js

to angular-xeditable - 0.1.9

http://plnkr.co/edit/pBnxWiqrLwOG1UNWyTJM?p=preview****
