### ISSUE TITLE
onShow does not seem to be called with editable-form en show=true

### ISSUE THREAD

**Issue by avandendaele** [vitalets/angular-xeditable#257]
I have a `editable-search` with a `onshow` attribute to enrich the `.form-group`.
It works well in "standalone" mode. However, when it's in an `editable-form` with `shown="true"`, the `onshow` is not called at first. If I submit the form then switch back to edit mode the `onshow` is called.

**Comment by ckosloski** [comment]
I would think there is a better way to do this than using onshow.  If you are adding a class, couldn't you do an `ng-class` that inspects the `$visibility` property of the `editable-form`?

**Comment by ckosloski** [comment]
@avandendaele is this still an issue?

**Comment by avandendaele** [comment]
@ckosloski I left Angular for React more than a year ago. Finally I left web development.
Therefore I don't know. Sorry

**Comment by ckosloski** [comment]
@eugef can you please close this issue.
