### ISSUE TITLE
How to dynamic clear and disable inputs?

### ISSUE THREAD

**Issue by pitymaia** [vitalets/angular-xeditable#259]
I'm using angular xeditable form and trying to clear a TYPEAHEAD field if the user select an option in other field.
When the user select an item I clear the variable on ng-model and clear do field value on that field, than I set the variable in edit-disabled to true.

The value is erased from the input and it become disabled... but only before close de the form by clicking in "save".
The problem is that the value come back when de form closes, and when I open it again, the field are not disabled.

How to access the values xeditable use and dynamic clear the field? 
How to disable the field and make it not enable when i click in edit button and open the form again?

**Comment by ckosloski** [comment]
I would think you can use some one of onchange/onaftersave to set other values in scope.
Currently edit-disabled is not watched, so any changes to it once the form is initially rendered are not picked up.  #282 is supposed to fix that issues, but it's not yet merged to master.

**Comment by ckosloski** [comment]
@eugef this issue is fixed, please close.
