### ISSUE TITLE
Several pull requests merged

### ISSUE THREAD

**Issue by Painyjames** [vitalets/angular-xeditable#261]
So basically I've been merging pull requests.
There were many of them, so I would require of you guys to tell me if with the new version (0.1.9)  all this bugs/enhancements have been sorted out so I can start marking down issues as supported.
You can find those on the changelog:
https://github.com/vitalets/angular-xeditable/blob/master/CHANGELOG.txt

Thanks peeps!

**Comment by ayakovlevgh** [comment]
I have two little suggestions:
1. If possible, it would be better to keep a linear commit history in order to save the information about original PR author.
2. Please, don't release untested changes as patch version. (0.1.8 -> 0.1.9)

**Comment by Painyjames** [comment]
Yeah, I tried to keep them ordered but couldn't since there were plenty of merges to be done and was quite a mess to merge. Will try to do like that in the future.

About the untested changes, yes you are right there. I saw people already using this forks that I assumed that were stable enough. My bad.
