### ISSUE TITLE
blur="cancel" is broken in 0.1.9

### ISSUE THREAD

**Issue by ayakovlevgh** [vitalets/angular-xeditable#262]
Although blur is setted to "cancel" x-editable form buttons stay visible on blur. Check jsfiddle: https://jsfiddle.net/NfPcH/7191/

In version 0.1.8 everything was OK.

**Comment by Painyjames** [comment]
Yeah you are right.
I'll have a look this afternoon and see which change on the latests merges provoke that.

Thanks for noticing!

**Comment by Painyjames** [comment]
this commit was causing that issue:
https://github.com/enapupe/angular-xeditable/commit/68cbb66a442f637661ea06b9a0f4a805d907bf20

I've included the amendments to 0.1.9, you can check your fiddle again to see that is working.

Cheers!

**Comment by ayakovlevgh** [comment]
good job. Thanks.
