### ISSUE TITLE
e-form broken in 0.1.9

### ISSUE THREAD

**Issue by onemenny** [vitalets/angular-xeditable#263]
Hi

since 0.1.9 (works in 0.1.8) the e-form is broken 
ng-click="textBtnForm.$show()"
ng-hide="textBtnForm.$visible"
are not working no more...

**Comment by Painyjames** [comment]
Hi

Will have a look this evening to see which recent change leads to that.
Can you provide a fiddle that shows that issue?

Thanks!

**Comment by onemenny** [comment]
http://jsfiddle.net/onemenny/NfPcH/7240/

**Comment by Painyjames** [comment]
Found the bug.

You can see your example working on http://jsfiddle.net/NfPcH/7246/
If you are using bower for getting xeditable you might want to run
bower cache clean angular-xeditable#0.1.9 and get it again

**Comment by onemenny** [comment]
thanks - ill check later on

**Comment by pascaldubois** [comment]
I confirm cleaning the cache fixed the issue for me.

**Comment by RavenHursT** [comment]
Doesn't seem to work in 1.8 either: http://plnkr.co/edit/uvLOMJ?p=preview

**Comment by RavenHursT** [comment]
Yeah.. can't get it to work in 0.1.9 either: http://plnkr.co/edit/msqzF8?p=preview

I've gotta be doing something wrong here....

**Comment by RavenHursT** [comment]
ahhhhh..... looks like you have to handle the show method yourself if you set e-form: http://jsfiddle.net/kjfu3rnx/3/

Would be nice if this was handled for you instead of explicitly having to handle it.

**Comment by RavenHursT** [comment]
Works w/ 0.1.8 as well :-) 

http://plnkr.co/edit/R7hfW6?p=preview

**Comment by RavenHursT** [comment]
But for the exact use case I was trying to use, it doesn't seem to work. :-(  

See my issue here: https://github.com/vitalets/angular-xeditable/issues/280

**Comment by ckosloski** [comment]
is this still an issue?

**Comment by ckosloski** [comment]
@eugef please close
