### ISSUE TITLE
Radiolist not Working in 0.1.9

### ISSUE THREAD

**Issue by ChrisSoelder** [vitalets/angular-xeditable#265]
It seems that the Radiolist doesn't work anymore in the newest Release.

It looks like selected values are not properly passed to the model as you can see in this fiddle

https://jsfiddle.net/Feierteifl/rktxty2d/1/

**Comment by Painyjames** [comment]
Yes, that's what it seems.
Will have a look this evening to see what causes that.

Cheers.

**Comment by Painyjames** [comment]
Fixed.
Some commits from #158 was causing that error.
You can check your fiddle to see that is working fine now.

Thanks for noticing/your patience

**Comment by kotmatpockuh** [comment]
i see that if on page i have > 1 input and click on other, last focus din't removed, in build from 2014 october - all was ok

**Comment by sbrnunes** [comment]
I'm experiencing the same problem reported by @kotmatpockuh. I'm trying to add more than one input type radiolist into the same page and they interfere with each other. In 0.1.8, if you click on one of the inputs, the other looses focus and returns back to it's read-only mode.

Worse, if in 0.1.9 you click in more than one input, and then you click on the cancel button in one of them, both return back to read-only mode.

**Comment by ckosloski** [comment]
Is this still an issue?  In the current version, if you have multiple editable elements, clicking on a second one will close the first one.  This is correct behavior.

**Comment by ckosloski** [comment]
@eugef please close.  Radiolist works in the current release.
