### ISSUE TITLE
npm package outdated needs a npm publish

### ISSUE THREAD

**Issue by tirithen** [vitalets/angular-xeditable#270]
I installed this nice package with $ npm install angular-xeditable --save since we are looking for this functionality for a project that uses npm as package manager but the version I got is 0.0.1. Could you please run $ npm publish on the current version?

**Comment by l0rn** [comment]
+1

**Comment by tlrobinson** [comment]
+1

**Comment by okonet** [comment]
+1

**Comment by okonet** [comment]
Also `package.json` lacks `main` key...

**Comment by Rodeoclash** [comment]
+1

**Comment by zEvg** [comment]
+1
Is there any update on this ?

**Comment by pdwinkel** [comment]
+1

**Comment by the-darc** [comment]
+1

**Comment by trodi** [comment]
:+1:

**Comment by trodi** [comment]
In searching for an NPM package, I found [angular-editable-npm](https://www.npmjs.com/package/angular-xeditable-npm), which is up to date with this parent repo and thus a viable solution to this issue. Note, neither package is maintained by @vitalets.

**Comment by trodi** [comment]
npm package maintainers, would either of you be able to update to the latest release? Additionally, it would be helpful to only have one npm package and deprecate the other. Thanks.
[angular-xeditable-npm](https://www.npmjs.com/package/angular-xeditable-npm) @ShaKann
[angular-xeditable](https://www.npmjs.com/package/angular-xeditable) @PitBeast

**Comment by sgarbesi** [comment]
+1

Someone just needs to run `npm publish`

**Comment by ShaKann** [comment]
angular-xeditable-npm is updated now. For sure I agree that there should be only one package. I tried to contact owners of angular-xeditable before I created my own but without success. I tried again to send them mail, I hope we will be able to sort that out.

**Comment by vitalets** [comment]
hi @eugef 
do you have permissions to publish angular-xeditable to npm ?

**Comment by eugef** [comment]
Hi @vitalets , I don't have permissions. 
Could you add me as collaborator at npmjs.com? My login there is `eugef`

**Comment by vitalets** [comment]
Contacted with https://www.npmjs.com/~akalinovski, he provided npm publish access to @eugef.

**Comment by ShaKann** [comment]
So @eugef let me know when you will update npm pacakge angular-xeditable so I will be able to deprecate my own. I have added PR with updated package.json. Or add me as contributor on npm and I will update package.

**Comment by eugef** [comment]
new version is released to npm

**Comment by ShaKann** [comment]
I deprecated my own package. I'm glad we are able to sort that out.
