### ISSUE TITLE
OnAfterSave error not cancel local model update

### ISSUE THREAD

**Issue by xak2000** [vitalets/angular-xeditable#271]
From the docs of `onaftersave`:

> The result type of this method can be following:
> 
> anything except string: success, form will be closed
> string: error, form will not close, string will be shown as error message

It is working fine even with promise (regardless of the fact that this is not noticed in the docs). When error happens (method returns string or promise of string) then form is not closing and error message is shown. But if after that we press `Esc` key then form is closing and our local model remains updated.

It is intended behaviour? If yes then how can we use `onaftersave` that returns error in practice? For example server returns 403.

I know that I can use `onbeforesave` but with this method we need more boilerplate code if we want to `POST /user/123` to update `user.username`. As `onberoresave` can pass to our function only updated field `username` not the whole `user` object with updated `username` and we must copy existing user then change `copy.username` and only after that we can do `POST /user/123`. With `onaftersave` we can just `save(user)` (it already has `username` updated) but on error `username` should be reversed to previous value.

**Comment by ckosloski** [comment]
If you want to cancel the model update on an error, you would have to use onbeforesave instead.  The documentation does say the model is updated first with onaftersave:

> Another way to submit data on server is to define onaftersave attribute pointing to some method of scope. Useful when you need to update local model first and only then send it to server.

**Comment by ckosloski** [comment]
@eugef The question is answered, please close.

**Comment by xak2000** [comment]
Is there a case where you **don't want to cancel the model update on an error**?
I think, the answer is almost always - you want.
So, you almost always can't use `onaftersave` then?

I don't think the answer "don't use `onaftersave`, use `onbeforesave` instead" is correct answer.
Any server respond with error sooner or later.

Ideally, the directive should restore model state when user presses <kbd>Esc</kbd> (`oncancel` event) after `onaftersave` failed. It is required for optimistic UI. `onbeforesave` is intended only for pessimistic UI updates.

But I understand, this is too hard to implement. So close for now.
