### ISSUE TITLE
pure angular-style tooltip

### ISSUE THREAD

**Issue by igler** [vitalets/angular-xeditable#28]
Hi you once said that it would be nice to find some "pure angular-style tooltip" to fork in order to be able to wrap things in popups. Maybe this http://mgcrea.github.io/angular-strap/#/popover or https://github.com/angular-ui/bootstrap/tree/master/src/tooltip is helpful?

**Comment by Wesseldr** [comment]
Looks like the: "popup mode (waiting https://github.com/angular-ui/bootstrap/pull/1391)" is now merged. hope someone can give it a kick, currently to new to get the big picture of this :)

**Comment by aguirrel** [comment]
Hi guys, thanks for this great component! Somebody has some update?

**Comment by mitcht** [comment]
Closed as being too old

**Comment by aguirrel** [comment]
@mitcht Could you review why do you close it? I think being old doens't mean nobody need it.  If it was solved, tag it, if not, please leave it open.

**Comment by mitcht** [comment]
There are 226 issues. I'm trying to close a few. If they pop up again, we'll work on them. Sorry.
