### ISSUE TITLE
Cannot use dynamically generated e-form names

### ISSUE THREAD

**Issue by RavenHursT** [vitalets/angular-xeditable#280]
If I  use e-form on a single editable-text, it works just fine.  The form object is added the $scope w/ the name that I give it.

But if I try to dynamically generate the names of each form in say, a list of links, it doesn't seem to work:

http://plnkr.co/edit/nNyGSz?p=preview

I've tried in both 0.1.8 and 0.1.9

**Comment by stillnet** [comment]
Do you need to use dynamic form names? I have many editable forms inside an ng-repeat, each form has the same name and it works fine.

**Comment by RavenHursT** [comment]
Having unique form names in a view seems very desirable.. otherwise, how else do you perform operations on specific forms in your controller if you cannot referent the form via ($scope.[formName])?

**Comment by stillnet** [comment]
If you do need to access the forms (I haven't needed to until a recent requirement) you can do it like this:
  $('#my-form-element").data().$formController.$show();

**Comment by RavenHursT** [comment]
Yeah.. there's a number of work arounds. I can't remember the specific use case that I was was trying to solve in our app when I generated this issue, but I remember finding a work around as well.  

But that doesn't negate the fact that there's an inconsistency here in regards to how e-form is behaving w/ just a static single item, and how it's behaving in the context of ng-repeat.

**Comment by ckosloski** [comment]
I guess I don't understand what the issue is here.  Is it that the names don't get dynamically generated?   Or that the forms don't work with dynamically generated forms?

**Comment by ckosloski** [comment]
Apparently there is an attribute called `e-clickable` that you can add to the single editable-text to get this to work.
Here is the modified [plunkr](http://plnkr.co/edit/DBRoey?p=preview) from above that works.
