### ISSUE TITLE
Editable row related select

### ISSUE THREAD

**Issue by serge-jerkezian** [vitalets/angular-xeditable#288]
I have two select input type that are related to each other.
The "item category" select input should filter the "item" select input.

```
<td>
 <span editable-select="saleItem.CategoryId" e-ng-change="itemCategoryChanged(this)"
  e-ng-options="item.Id as item.Name for item in ddlItemCategory"
  e-name="categoryName" e-form="rowform" e-required>
     {{saleItem.CategoryName}}
</span>
</td>

<td>
 <span editable-select="saleItem.ItemId" onshow="loadItem(saleItem.ItemId)"
 e-ng-options="item.Id as item.Name for item in ddlItemName"
 e-name="ItemName" e-form="rowform" e-required>
    {{saleItem.ItemName}}
</span>
</td>
```

When i change "ddlItemCategory" and I update "ddlItemName" all the select that are bind to "ddlItemName" are being updated, which is normal.  But I don't want this result.  I want to rebind the "ddlItemName"  of the row am editing only. 

Anybody has a clue on how I can achieve that ?

**Comment by stillnet** [comment]
This is possible. In my app the value of condition1 causes the condition2 drop down to be filtered. Here's some code, hope this helps.

    // shows the selected condition 1 code
    $scope.showCondition1 = function(line) {
        var selected = [];
        if(line.condition1 != '') {
            selected = $filter('filter')($scope.condition1Options, { code: line.condition1 }, true);
        }else{
            line.condition2 = ''; // make sure condition2 is empty if condition1 is empty
        }
        return selected.length ? selected[0].code : '';
    };    

    // shows the selected condition 2 code
    $scope.showCondition2 = function(line) {
        var selected = [];
        if(line.condition2 != '') {
            selected = $filter('filter')($scope.condition2Options, { code: line.condition2 }, true);
        }
        return selected.length ? selected[0].code : '';
    };     

    // when condition 1 changes, we need to update information on the line
    $scope.changeCondition1 = function(data, line){
        line.condition1 = data;
        if(data === ''){
            var editables = this.$form.$editables;
            for(var i=0; i<=editables.length-1; i++){
                if(editables[i].name == 'condition1value' || editables[i].name == 'condition2value' || editables[i].name == 'condition2'){
                    editables[i].scope.$data = ""; 
                }
            }
        }
    };

    // when condition 2 changes, we need to update information on the line
    $scope.changeCondition2 = function(data, line){
        line.condition2 = data;
        if(data === ''){
            var editables = this.$form.$editables;
            for(var i=0; i<=editables.length-1; i++){
                if(editables[i].name == 'condition2value'){
                    editables[i].scope.$data = ""; 
                    break;
                }
            }
        }
    };

**Comment by ckosloski** [comment]
Is there still an issue here?

**Comment by ckosloski** [comment]
@eugef there is an answer, please close.
