### ISSUE TITLE
e-* attribute bug

### ISSUE THREAD

**Issue by qbunia** [vitalets/angular-xeditable#289]
Hello,
Latelty I tried to create custom xeditable directive that uses Kendo UI. Usage of it looks like this:
<span editable-kendocomplete="viewModelEdit.Prescription" e-k-data-text-field="'Name'">{{ viewModelEdit.Prescription }}</span>

The problem is that "e-k-data-text-field" should be translated into "k-data-text-field" upon edit, but the result is "kdata-text-field" 
I found exact place where it happens:
Its 490 line in xeditable.js ver 0.1.8

I made workaround for that but is it possible for you to fix it? Or maybe I can pull request and fix it on my own?

**Comment by JobaDiniz** [comment]
Great, please create a PR :smile:

**Comment by ckosloski** [comment]
@eugef this was fixed by #544 please close
