### ISSUE TITLE
Editing html

### ISSUE THREAD

**Issue by prototype-59** [vitalets/angular-xeditable#290]
Great module, thank you. Also, it would be nice to be able to edit text with html tags  For example:

`<p  editable-textarea="article" ng-bind-html="article" onbeforesave="updateArticle()"></p>`

where `article` contains some html, e.g. `<strong>Title</strong><p>my text...</p>`

The simple solution is to change the first line of code in xeditable.js from:

`angular.module('xeditable', [])` to 
`angular.module('xeditable', []).config(function($sceProvider) { $sceProvider.enabled(false); })`

but it would be nice to have an "official" configurable option.

**Comment by ckosloski** [comment]
I have verified that with the latest AngularJS and angular-xedtiable, using ng-bind-html shows the tags in the edit link for editable-textarea.

**Comment by ckosloski** [comment]
@eugef please close
