### ISSUE TITLE
Readme update necessary

### ISSUE THREAD

**Issue by dlwhiteman** [vitalets/angular-xeditable#293]
The roadmap at the bottom says that checklist and combodate are in the future, but both of those are 
available as of version 0.1.9.  

I would like to know, however, if there is any plan to support custom editors?  We have a need to edit an object with a composite "widget" that consists of two small input fields and a button to prompt the user for other options.

I'd also like to know when it's expected that select2 will be supported.

**Comment by ckosloski** [comment]
1.  This has been fixed.
2.  I think you could add this yourself.  You could take a look at how ui-select was implemented.
3.  ui-select has been implemented.

**Comment by ckosloski** [comment]
@eugef The roadmap has been already been removed, please close.
