### ISSUE TITLE
Single row editing mode

### ISSUE THREAD

**Issue by neesonqk** [vitalets/angular-xeditable#295]
Is that possible to set the editable table to single row editing mode, which means while one row is under editing, the other rows won't be able to be edited. 

I don't know where to put a flag into $show, $cancel etc. to achieve this, any idea?

**Comment by stillnet** [comment]
I have a similar problem. My approach was to make each row it's own form. Inside an ng-repeat I have many

    <form editable-form name="optionForm" onaftersave="saveOption($index)">
tags. No issues even though every form has the same name.

**Comment by mitcht** [comment]
Use e-single. This should allow this to happen.
