### ISSUE TITLE
Support for Angular 1.3/1.4?

### ISSUE THREAD

**Issue by jaxon** [vitalets/angular-xeditable#297]
What version of Angular does angular-xeditable support and/or have issues with?

I'm currently migrating from Angular 1.2. to 1.3.

**Comment by JobaDiniz** [comment]
+1

**Comment by stillnet** [comment]
I started with Angular 1.3 and have since moved to 1.4 beta 6. I haven't noticed any problems.

**Comment by KatelynL** [comment]
I am attempting to migrate from Angular 1.2 to 1.3 and am having issues.  Has anyone else had issues with 1.3?

**Comment by jmvalencia** [comment]
I'm with angular 1.4 and no issues so far, for the record Im only using basic functionality for now.

**Comment by danielo515** [comment]
It would be useful to specify which angular version is required. I'm trying with angular 1.4.5 and it does not work.

**Comment by danielo515** [comment]
It works flawlessly with angular 1.4.7

**Comment by masitko** [comment]
it works with 1.5 too

**Comment by ckosloski** [comment]
It works with the latest 1.5.3.
