### ISSUE TITLE
Blur breaks on 0.1.9

### ISSUE THREAD

**Issue by paustria** [vitalets/angular-xeditable#303]
When clicking xeditable element and click another xeditable element, both elements show input field. This effects blur functionality not working properly.

See jsfiddle below:
http://jsfiddle.net/NfPcH/8097/

**Comment by hungyc** [comment]
I have faced the same issue, any solution for that?

**Comment by jmvalencia** [comment]
I have sent a PR to handle it take a look:
https://github.com/vitalets/angular-xeditable/pull/311

**Comment by guikubivan** [comment]
Oh you're a life saver @jmvalencia ! Thank you and hope it gets merged in soon, I will apply manually for now.

**Comment by ckosloski** [comment]
@eugef please close, this was fixed in #590
