### ISSUE TITLE
href="#"  taking  homepage

### ISSUE THREAD

**Issue by tojojose** [vitalets/angular-xeditable#306]
I am using angular ui-route , with angular-xeditable , below is the editable-text
    <a href="#" editable-text="profile.firstname">{{ profile.firstname || 'empty' }}</a>
 But when i click the link , insted of showing the text box , it redirects to the home page defined in ui-router.Could you please help

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by gentisaliu** [comment]
@ckosloski YES!

**Comment by gentisaliu** [comment]
Please fix this.

**Comment by gentisaliu** [comment]
If I place the element outside a `form` tag, then it works. I think the `editable-form` controller is responsible for this misbehaviour, somehow related to https://github.com/vitalets/angular-xeditable/pull/414 .

**Comment by ckosloski** [comment]
Can you provide a jsfiddle or plunkr showing your issue?

**Comment by gentisaliu** [comment]
Yes.

JsFiddle with form element: https://jsfiddle.net/tj8j8qrh/23/ (not working)
Same JsFiddle without form element: https://jsfiddle.net/tj8j8qrh/24/ (working)

**Comment by ckosloski** [comment]
When using editable-form, you have to have a button to show the form.  See the [documentation](http://vitalets.github.io/angular-xeditable/#editable-form). 

Here is your updated [jsfiddle](https://jsfiddle.net/ckosloski/hp4utgg6/2/) with the edit button.

Or, I suppose in your case, you could add an on-click event to the href to show the form.

**Comment by ckosloski** [comment]
@eugef The question is answered, please close.
