### ISSUE TITLE
Keep font styles while editing inline

### ISSUE THREAD

**Issue by saswayze** [vitalets/angular-xeditable#309]
First time github user, so I'll apologize ahead of time in case I am committing a faux pas.

I'm using xeditable for multiple pieces of data at different points in the design hierarchy of a page, from small text to major titling on page. I want to keep the font styling the same during the edit part; the font and color already stay the same, but the font size doesn't. 

I was thinking I could put a custom class or ID in the edit-input some how, but I'm not really sure how to go about doing that. A friend suggested to put class/id in the span to be edited and it would get pulled to the edit-input, but that isn't working and I'm not sure where to start looking now. 

All help is greatly appreciated even if it is just a direction to start looking.

**Comment by ckosloski** [comment]
You can either add `e-class` to have classes transferred to the input or override the xeditable classes in your own css file.

**Comment by ckosloski** [comment]
@eugef The question is answered, please close.
