### ISSUE TITLE
Issue with editable-bsdate and UI Bootstrap 0.13.0

### ISSUE THREAD

**Issue by planttheidea** [vitalets/angular-xeditable#312]
With the recent update of UI Bootstrap to 0.13.0, there were several datepicker fixes. I believe some of these fixes may be breaking the assignment in xeditable, because I receive an assign error each time. I also noticed that the date is formatted when you start the edit, but when selecting a new date it reverted to standard JS date.

**Comment by jensenkd** [comment]
@planttheidea any fix for this that you were able to find?

**Comment by asakalou** [comment]
Hello Guys,

Could you please fix bootstrap datepicker attribute issue.
There is a wrong name of the attribute datepicker-append to body:

expected: inputDatePicker.attr('datepicker-append-to-body', this.attrs.eDatepickerAppendToBody || false);

actual: inputDatePicker.attr('date-picker-append-to-body', this.attrs.eDatePickerAppendToBody || false);

**Comment by ckosloski** [comment]
This issue can be closed.
