### ISSUE TITLE
implementation for datepicker in 0.1.9 has some issues

### ISSUE THREAD

**Issue by incadoi** [vitalets/angular-xeditable#317]
2e92aa091203ed6b74d514e9f7d961281130775f

The attributes are mapped two times: the first time in EditableController in render() function and then in  editableBsdate directive also in the render() function.
Because of this there will be two popup's with the calendar.

**Comment by rguldener** [comment]
+1 would be great to get this resolved. If I find time I might create a PR on the weekend but will have to see how easy this is to fix for somebody not familiar with the codebase.

**Comment by eugef** [comment]
Fixed by #443
