### ISSUE TITLE
textarea shows content underneath

### ISSUE THREAD

**Issue by dankahle** [vitalets/angular-xeditable#323]
https://jsfiddle.net/w9fnjehw/1/

Don't really understand what's going on, i.e. if I add: z-index:1000, background:white on the form or it's div child (holding controls) still see through the form/div. Doesn't make sense. If someone sets the textarea's rows/columns big enough, it will escape the confines of the original element it's editing. Fine, but the thing is: it's see through and other stuff is on top of it somehow.

**Comment by ckosloski** [comment]
You need to set the z-index of the "one" class to -1 and then it will be behind the div that contains the expanded text area.

**Comment by ckosloski** [comment]
@eugef please close
