### ISSUE TITLE
Checklist buttons="no" doesn't save changes

### ISSUE THREAD

**Issue by elgs** [vitalets/angular-xeditable#324]
I like to set buttons="no" in html to not show the save/cancel buttons. Normally it works as expected when the control loses focus, the change is saved to the model. However, checklist does not seem to work. When I set buttons="no", it doesn't save changes to the model.

**Comment by borgez** [comment]
change to 
if (self.single) {
                  self.editorEl.attr('editable-form', '$form');
                  // transfer `blur` to form
                  self.editorEl.attr('blur', self.attrs.blur || editableOptions.blurElem);
              }

**Comment by elgs** [comment]
So is it an inconsistency for the behaviors of the controller? Or is there a reason for this one to be different from others?

**Comment by maeishoj** [comment]
I would like to know that too.. Also it doesn't work for text areas! 

Or rather , it would seem to behave like a normal input and would expect to work, except that if I click outside the area the value does not get set! 

Any idea?

**Comment by ckosloski** [comment]
You need to set buttons="no" and blur="submit" in order for this to work correctly with checklist.

**Comment by ckosloski** [comment]
@eugef please close
