### ISSUE TITLE
How to change the input size?

### ISSUE THREAD

**Issue by xinyu7git** [vitalets/angular-xeditable#327]
the  default input text size is to short,how to increase my input text size?

![image](https://cloud.githubusercontent.com/assets/3701997/8302499/6efa2192-19c9-11e5-9ea4-ddadfe62194c.png)

**Comment by m-apsolon** [comment]
not the nicest, but the easiest way would be to use *e-style* attribute.

`<span editable-text="user.name" e-name="name" e-style="width:400px;" onbeforesave="doSomething($data)" </span>`

**Comment by xinyu7** [comment]
@m-apsolon  thank you ~

**Comment by innerpeace0** [comment]
If you're going to do a lot of them and/or several other modifications, you could add a supplemental style sheet. A later style setting will override a previous one of the same weight, so make sure your custom style sheet loads last.

**Comment by seksitha** [comment]
Hi,
 can I make the input size auto upon edit?

**Comment by boubou1030** [comment]
Could we do a responsive size? Thanks.

**Comment by innerpeace0** [comment]
Perhaps a percentage?

**Comment by celsomtrindade** [comment]
I mad this change direct into the css, in this part here: 

	.editable-wrap {
		display:block;
		width: 100%;
		padding-right:10px;
		.editable-controls {
			> input,
			> select,
			> textarea {
				display: inline-block;
				width: 100%;
			}
		}
	}

Hope this is what you are looking for.

**Comment by boubou1030** [comment]
@innerpeace0  I used a percentage and the size can be changed, but however it didn't show a responsive size. @celsomtrindade  I don't have any experience on sass, I'm wondering how could I modify it into css3  between <style></style> directly? Thanks!

**Comment by celsomtrindade** [comment]
It would be something like this:

    .editable-wrap {
        display:block;
        width: 100%;
    }
    .editable-wrap .editable-controls > input
    .editable-wrap .editable-controls > select,
    .editable-wrap .editable-controls > textarea {
        display: inline-block;
        width: 100%;
    }

But like i said, this is the default css and i did this modification to match my layout, maybe you need to change some things to match yours, but you'll get the idea.

**Comment by boubou1030** [comment]
@celsomtrindade  Thank you very much! I'm looking into it.

**Comment by EnsiasStudent** [comment]
Did you try to use the ### inline-size property of an input text in CSS or the ### size property it's doing the effect for me.
