### ISSUE TITLE
editable-form onbeforesave where is the data?

### ISSUE THREAD

**Issue by jdforsythe** [vitalets/angular-xeditable#328]
I have an editable form. I use the onbeforesave of each form input to check the validation. I want to use the onbeforesave of the form itself to do the database update (not onAFTERsave, because I don't want the edit boxes to disappear if there's a server-side error). If I do onbeforesave="check($data)" then $data is an empty object, just like if I access $scope.formName.$data. I can see the values inside of $scope.formName.$success - but they are only populated if there's a change and it's weird logic to read from there for the changes. Is this a bug? I'd think $data would be filled...

**Comment by m-apsolon** [comment]
Pretty sure you forgot to name your fields. Notice the attribute 'e-name'.
http://jsfiddle.net/NfPcH/81/
