### ISSUE TITLE
rowform example doesn't work with version 0.1.9

### ISSUE THREAD

**Issue by AlexSchuetz** [vitalets/angular-xeditable#332]
In version 0.1.9 the rowform example doesn't work anymore.

If a second rowform is shown the first form is partially hidden and there are no submit/cancel-buttons at all.

**Comment by ckosloski** [comment]
Is this still an issue with the latest release?

**Comment by AlexSchuetz** [comment]
I will check this again.

**Comment by ckosloski** [comment]
I have verified that the rowform example works with the latest release.
@eugef please close.
