### ISSUE TITLE
xeditable Grid's drop down values cannot change from the outside dropdown

### ISSUE THREAD

**Issue by Sampath-Lokuge** [vitalets/angular-xeditable#333]
I'm using xeditable angular directive.I need to set the grid's all the drop down values of Status column according to the value of the outside drop down. I have set up the JsFiddle below.But it's not working.Could you tell me Why ? Thanks in advance.

Update: When I click the cancel button then it's updated.Very strange :( Could you tell me how to sort out this issue ?

HTML

    <span editable-select="bulkPaymentType" e-form="tableform" e-ng-options="s.value as s.text for s in statuses" e-ng-change="setBulkPaymentType($data)">
 </span>

JS

     $scope.setBulkPaymentType = function (data) {
        for (var i = $scope.users.length; i--;) {
            var user = $scope.users[i];
            user.status = data;
        };
    };

JsFiddle : http://jsfiddle.net/sampath_lokuge/NfPcH/9130/

**Comment by Sampath-Lokuge** [comment]
I have found the solution.Here it is :clap:

**HTML**

    <span editable-select="bulkPaymentType" e-form="tableform" e-ng-options="s.value as s.text for s in statuses" e-ng-change="setBulkPaymentType($data,tableform)">
 </span>

**JS**

    $scope.setBulkPaymentType = function (data,tableform) {
        for (var i = 0; i < tableform.$editables.length; i++) {
            if (tableform.$editables[i].name === 'user.status') {
                tableform.$editables[i].scope.$data = data;

            }
        }
    };

**Play with it : [JSFiddle](http://jsfiddle.net/sampath_lokuge/NfPcH/9187/)**

**Comment by MuraliM** [comment]
Is it possible to do the same thing from external select box which is not a part of tableform?

I have the similar problem, got two forms one which has normal form controls. Another one is inline editable table. There is a column in inline editable table which depends on the select box available in the form1. 

How to make this work? I tried with 

     $scope.$watch('purchaseHeader.DiscountPercent', function (newValue, oldValue, scope) {
        // get access to the editable form table and set the discount column value
      });

But need to know how to access the table forms?
