### ISSUE TITLE
Question: any way to cancel event bubbling

### ISSUE THREAD

**Issue by okonet** [vitalets/angular-xeditable#335]
I've a editable controls in a container which on its own has mouse event listeners. Is there a way to prevent event bubbling when clicking on editable controls so my wrapper element does not react on these clicks as well?

**Comment by luigimassa** [comment]
+1

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by okonet** [comment]
I don't work on the project that uses that so I guess I'm not :)

**Comment by ckosloski** [comment]
OK, can you please close then :)

**Comment by okonet** [comment]
Keeping in mind the question is still open and some people might be interested in it, I'd prefer not to. But if you insist...
