### ISSUE TITLE
Question: read only mode?

### ISSUE THREAD

**Issue by okonet** [vitalets/angular-xeditable#337]
Is there a way to make controls "read only" (displaying the underling model content without allowing to edit it).

**Comment by eugef** [comment]
Yes, just add `e-disabled` attribute to the input.

**Comment by okonet** [comment]
I don't use `input`. Instead I use `a` as in this example: http://vitalets.github.io/angular-xeditable/#text-simple and it doesn't seem to work with `e-disabled`

**Comment by eugef** [comment]
`e-disabled` attribute works, here is jsfiddle http://jsfiddle.net/NfPcH/9349/

**Comment by okonet** [comment]
Oh now I see there is a misunderstanding happened. What I mean by "read only" mode is that you even can not click the control anymore and it is getting "normal" (not link) styles.

**Comment by dlwhiteman** [comment]
I would like the same feature.  What I believe he is asking for is to not show an editor at all if a certain condition is met.  Maybe you have a table containing employees, and only those employees that are not managers can have their vacation days edited, or something like that.  I want to make it so that conditionally the static text is not changed to an editable element.

**Comment by dlwhiteman** [comment]
OK, here is a workaround within an xeditable table:

    <td>
       <span ng-show="readOnlyMode">{{myValue}}</span>
       <span editable-text="myValue" e-form="myform" e-ng-hide="readOnlyMode" ng-hide="readOnlyMode">{{myValue}}</span>
    </td>

**Comment by innerpeace0** [comment]
> this would be more elegant if there were a built-in directive to conditionally show the editor.

+1

**Comment by okonet** [comment]
@dlwhiteman I use the same "work around" in my code, but as some investigation shows, it's rather unperformant when switching lots of items. IMO internal "readonly" implementation could be much more performant since it would not require completely new DOM and attaching/detaching event listeners. Not sure though it is really so when using angular (not an expert here).

**Comment by eugef** [comment]
As for now there is no built-in directive to do this, I can suggest to use the following workaround:
```
<a href="#" editable-text="user.name" ng-if="enabled">{{ user.name || 'empty' }}</a>
<span ng-if="!enabled">{{ user.name || 'empty' }}</span>
```
Here is jsfiddle http://jsfiddle.net/NfPcH/9360/

Internal implementation could be slightly faster, but until you have couple of thousands elements on the page, you should not notice any performance impact.

**Comment by innerpeace0** [comment]
> I can suggest to use the following workaround ...

Gr8! Thx.

**Comment by eugef** [comment]
BTW, there is a PR #206 that aimed to implement this feature. 
Anytime soon will take a look at it and merge if possible

**Comment by gusreyes01** [comment]
I have another workaround:

Create a function on the row you want to make optional:

     
**template.html**

    ng-click="showRowForm(rowform.$show())"

**controller.js**

            $scope.showRowForm = function(param) {
                if($scope.quote.status != '2'){
                    return param;
                }
            }

**Comment by juanvillegas** [comment]
Another way could be to make a manual button to trigger the editable input, and if certain conditions are met display the button, otherwise hide it

**Comment by ckosloski** [comment]
You could use `edit-disabled=true` and use some css to style the link so that it doesn't appear clickable.  Not sure if this will work, but you could try it:  `a[edit-disabled=true] {
    cursor: default; text-decoration:none;
}`

**Comment by mgohin** [comment]
I have the same problem and asking for the same feature (didn't find your issue before posting) : #496
Using a dynamic `edit-disable` doesn't work

**Comment by ckosloski** [comment]
@eugef I think this can be closed since `edit-disable` is now dynamic and #496 was also closed
