### ISSUE TITLE
How to remove selection from EditableSelect

### ISSUE THREAD

**Issue by rednerus** [vitalets/angular-xeditable#338]
I want to nullify the selection from the Editable Select. I see that I can only select from the list but I cant make it empty. Is there something I can do to remove the selection and make it empty ?

**Comment by ckosloski** [comment]
There is a `e-placeholder` attribute that you can set and it will add the "blank" or "default" selection option to the list.  This should resolve your issue.

**Comment by ckosloski** [comment]
@eugef please close
