### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by MarkHerhold** [vitalets/angular-xeditable#339]
MIT would be nice

**Comment by MarkHerhold** [comment]
Oops. I see that you have "MIT" at the bottom of the README. Please add a LICENSE file. :)

**Comment by eugef** [comment]
Hi @MarkHerhold , would be nice if you could create a PR to fix it.

**Comment by innerpeace0** [comment]
For common licenses like GPL and MIT, links are usually sufficient. There are also some one liners with links that are commonly used and accepted.

**Comment by MarkHerhold** [comment]
@innerpeace0 ok that is fair enough.
@eugef would you like the PR or to close this issue?

**Comment by eugef** [comment]
@MarkHerhold PR with one-line link for readme.md would be nice to have
