### ISSUE TITLE
Validate table row field based on a mask.

### ISSUE THREAD

**Issue by celsomtrindade** [vitalets/angular-xeditable#344]
I'm using a table row editing but can only validate with the `onbeforesave`, like the example on the [docs](http://vitalets.github.io/angular-xeditable/#editable-row). But i tried a lot of things to make it validate the field based on a mask. Without success. Also, i couldn't validate it as `$invalid` because the `ng-model` of the input is always set to `$data` no matter what i name my `e-ng-model` field on the table row. I've tried to open a [question on stackoverflow](http://stackoverflow.com/questions/31542958/angularjs-x-editable-table-row-validation) but no one answered the question.

For example, i wasn't able to validate the field like this:

```
$scope.checkTel = function(data) {
    if (data == null) {
        return "Required field";
    } else if ($scope.rowform.num_tel.$invalid) {
        return "Invalid field";
    }
};
```

**Comment by joelbarba** [comment]
I had the same problem. I couldn't find a way to access the input to check its $invalid property because they are outside the form. I fixed it binding an on-change event and checking it dinamically into a javascript function:

```
<span editable-text="item.name"    e-name="name"    e-form="rowform" e-ng-change="checkInput(rowform, 'name')" ...>{{item.name}}</span>
<span editable-text="item.surname" e-name="surname" e-form="rowform" e-ng-change="checkInput(rowform, 'surname')" ...>{{item.surname}}</span>
<span editable-text="item.address" e-name="address" e-form="rowform" e-ng-change="checkInput(rowform, 'address')" ...>{{item.address}}</span>  

....

// Check the input reactively to turn on/off the save button
$scope.checkInput = function(rowform, currentInputName) {
  var invalid = false;
  var value;

  // Check all inputs
  for (var inputName in this.$form.$data) {

    if (inputName === currentInputName) { // For the current input, the new value is here
      value = this.$data;
    } else {
      value = this.$form.$data[inputName];
    }

    invalid = invalid || (value === undefined);     // Default check: no $data means the input is invalid

    if (invalid) {
      break;
    }
  }

  rowform.noSave = invalid; // Flag to set the Save button disabled
}
```

I know it is not the prettiest way, but it works.

**Comment by ckosloski** [comment]
@eugef a valid answer was given, please close.
