### ISSUE TITLE
Page Opens in Edit Mode

### ISSUE THREAD

**Issue by jongravois** [vitalets/angular-xeditable#345]
Is it possible that using Controller As syntax is causing the page to load with ALL of the tables rows already in Edit Mode ... I am forced to click cancel on each row to get the page to the state it should be when it loads. If Controller As is the culprit, is there a workaround?

**Comment by jongravois** [comment]
I have created a plunker to show my issue -- http://plnkr.co/edit/1jImj2qULqKfQ3pGBzVb?p=preview. I have to click the cancel 'X' of each row before the table is like I need it to be.

**Comment by chisaipete** [comment]
Did you find a solution?  I've got the same issue.

**Comment by ckosloski** [comment]
You need to name your editable form the same as your form name `editable-form="rowform"`.

See this updated [plunker](http://plnkr.co/edit/ArT7EAiVTcEQntLTPQ0k?p=preview)

**Comment by ckosloski** [comment]
@eugef this issue has been answered, please close.
