### ISSUE TITLE
[Question] onbeforesave server validation

### ISSUE THREAD

**Issue by kashcode** [vitalets/angular-xeditable#346]
How can set Error if I from server return object for example:

``` javascript
{
  "Status": "Error",
  "Message": "Server validation error message"
}
```

Now error is set if server response is different then 200.

**Comment by turbosasa** [comment]
I think this sample 'Validate remote' http://jsfiddle.net/NfPcH/36/ is that I need.

**Comment by ckosloski** [comment]
@eugef looks like he answered his own question, please close.
