### ISSUE TITLE
Wrapping textarea template in div causes it not to work

### ISSUE THREAD

**Issue by maeishoj** [vitalets/angular-xeditable#348]
Hey everyone,

so I was trying to modify the template for textarea (inputTpl) and wrap that into a div due to my website template styling, it needs to be inside a certain div.

however this causes it not to work! Meaning that when I edit the text and try to save, the changes do not take effect. The value does not get updated to what I just wrote.

Why is that? and how to go around it?

**Comment by ckosloski** [comment]
Can you provide a plunker or jsfiddle showing your issue?

**Comment by maeishoj** [comment]
1 year old issue, can't recall this anymore nor am i using it anymore, therefore i am closing it.
