### ISSUE TITLE
Form xeditable not working when put it inside form html 

### ISSUE THREAD

**Issue by nuong** [vitalets/angular-xeditable#349]
As the issue title , it have error <code> Form with editable elements should have `editable-form` attribute. <span editable-text="obj.title" class="ng-scope ng-binding editable" ></code> when i put xeditable form in other normal form.
Any suggest please! Thanks all

**Comment by ckosloski** [comment]
Can you provide a plunker or jsfiddle with your issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
