### ISSUE TITLE
onbefore save

### ISSUE THREAD

**Issue by timgarlick11** [vitalets/angular-xeditable#351]
have a form that has multiple types of items  but in each type they can be mapped to certain categories. for example a category of oil with multiple types(flagship, premium, regular etc. you have a editable text that you go through pick your type and you have an option to select a category or make a new one. Problem is if user doesn't select "oil" but just types "oil" and clicks out of editable area it will add a brand new category of "oil" with new product id and everything. Any idea on how you would implement a check for this so if user clicks out of editable text if the category is spelled the same as a previously made category i will not build a brand new one but just map it to that previously made category? hope I am making sense? jumped intp a huge application and the person that built the app moved on and I am just trying to make sense if everything.

**Comment by kashcode** [comment]
You can validate remote category of 'oil' http://jsfiddle.net/NfPcH/36/ and if server return that this new category all ready exist just select it in a list.

**Comment by ckosloski** [comment]
@eugef looks like a valid answer was given.  Please close.
