### ISSUE TITLE
Combodate Options 

### ISSUE THREAD

**Issue by mwalz** [vitalets/angular-xeditable#354]
Combodate is a great new feature, thank you!

I see it can take a number or optional parameters. How are those set on the element?

When I try the snippet below, the minYear does not change:

```html
<span editable-combodate="user.dob" e-name="dob" e-min-year=1900></span>}
```

Are the options configurable at the element level?

**Comment by vjanssens** [comment]
Unfortunately, it seems as if custom options on the element don't get transfered to the combodate element. I could not get the parameters to work.

I didn't have the time to make a pull-request (and am not sure if it will ever be merged) for this problem but a real nasty hack would be to edit xeditable.js (the angular version) on line 231 with the following.

````javascript
var combodate = editableCombodate.getInstance(this.inputEl, {
  value: new Date(this.scope.$data), // should already be in the code
  minYear: 1900 // custom parameter
});
````

**Comment by ckosloski** [comment]
This feature was added with version 0.1.10.  This issue can be closed.
