### ISSUE TITLE
Localization for decimal number

### ISSUE THREAD

**Issue by thedarkdestructor** [vitalets/angular-xeditable#356]
Actually, it seems there is no way to use decimal numbers with localization info. I would like to use the comma instead of the dot as a decimal separator but i was unable to find the way (nor the doc).

Using "editable-number" instead of "editable-text" does not work either.

**Comment by ckosloski** [comment]
I think this is more of an angular issue.  See [this issue](https://github.com/angular/angular.js/issues/10146)

**Comment by ckosloski** [comment]
@eugef please close, this is an angular issue, not a xeditable issue.
