### ISSUE TITLE
How to get computed column values in row onbeforesave

### ISSUE THREAD

**Issue by MuraliM** [vitalets/angular-xeditable#362]
Working in angular x-editable inline table. I would like to have additional columns which are computed values based on other columns.

Once the user added a row, it should be updated to the local scope array based on index. However I could not able to see the computed column MRPVATAmount, COSTVATAmount values. It shows the data that bound only to the x-editable fields.

posted http://stackoverflow.com/questions/32166343/angularjs-x-editable-table-with-computed-column

Working Demo http://plnkr.co/edit/r3KizBEVik4hFkGsdO2r?p=preview

I would like to enter values with computed column, then click each row, do validation like required/computed

Once user added many rows, they click on a global save button to commit all the data to the server.

```
<td>
 <form editable-form name="rowform" onbeforesave="savePurchaseItem($data, order.Id, rowform)" ng-show="rowform.$visible" class="form-buttons form-inline" shown="inserted == order">
              <button type="submit" ng-disabled="rowform.$waiting" class="btn btn-primary btn-xs">
                <em class="fa fa-save"></em>
              </button>
              <button type="button" ng-disabled="rowform.$waiting" ng-click="cancelOrder()" class="btn btn-xs btn-default">
                <em class="fa fa-times"></em>
              </button>
            </form>
</td>
 <td>
     <span ng-model="rowform.$data.MRPVATAmount" style="width:60px" e-name="MRPVATAmount" e-style="width:60px" e-form="rowform">
                    {{ calculateMRPVATAmount(rowform.$data) }}
                </span>
</td>

$scope.calculateMRPVATAmount = function (order) 
 {       
    var amount = (order.Qty *  parseFloat(order.MRP)) * (parseFloat(order.VAT)/100);
    return (isNaN(amount)) ? 0 : amount;
  }

$scope.savePurchaseItem = function(data, id, rowform, idx) {
    //data doesnot have MRPVATAmount, COSTVATAmount property. It has only editable data
 }
```

**Comment by HariBabuThubati** [comment]
Hi , i have the table in edit mode , after if i change that updated values in text field
was not showing in controller. please help how can i get entire table values in controler.

<tr data-ng-repeat="Item in Items | filter: {schdNm: 'A'}">
		<td width="3%"><input type="checkbox" e-form="tableform" data-ng-model="Item.isSelected" data-ng-change="scheduleASelection(Item)"/></td>
	    <td width="3%"><span  e-form="tableform" e-name ="Item.holdingsSeq" e-ng-modal="Item.holdingsSeq">{{ Item.holdingsSeq}}</span></td>
		<td width="20%"><span editable-text="Item.holdingsDesc" e-form="tableform" e-name ="Item.holdingsDesc" e-ng-modal="Item.holdingsDesc" onbeforesave="checkName($data, 'Description')">{{ Item.holdingsDesc}}</span></td>
		<td width="10%"><span editable-text="Item.accuredIncmAm" e-form="tableform" e-name ="Item.accuredIncmAm" e-ng-modal="Item.accuredIncmAm">{{ Item.accuredIncmAm }}</span></td>
		<td width="10%"><span editable-text="Item.altValDt" e-form="tableform" e-name ="Item.altValDt" e-ng-modal="Item.altValDt">{{ Item.altValDt | date:"dd/MM/yyyy" }}</span></td>
		<td width="10%"><span editable-text="Item.altValAm" e-form="tableform" e-name ="Item.altValAm" e-ng-modal="Item.altValAm">{{ Item.altValAm}}</span></td>
		<td width="10%"><span editable-text="Item.valAtDtOfDeath" e-form="tableform" e-name ="Item.valAtDtOfDeath" e-ng-modal="Item.valAtDtOfDeath" onbeforesave="checkName($data, 'Value at DOD')">{{ Item.valAtDtOfDeath }}</span></td>
		<td width="10%"><span e-form="tableform" e-name ="Item.altAccId" e-ng-modal="Item.altAccId">{{ Item.altAccId }}</span></td>
	</tr>

**Comment by MuraliM** [comment]
@HariBabuThubati Check this Plunker link http://plnkr.co/edit/UoXWgnqOVMEwVvHonnqG?p=preview

As of now I have managed to update the object(order) passed to get the computed value

**Comment by HariBabuThubati** [comment]
@MuraliM : Thanks for reply ...but in my case i am using http://vitalets.github.io/angular-xeditable/#editable-table for editing entire table , If table is having two or more rows and click on edit and i updated some values (text values) , on click event i want get those updated values in controller. can you please advise.

**Comment by HariBabuThubati** [comment]
@MuraliM  :  Any advise on the above, i am facing this issue since two days.could not able figure out? on click even the new data is not write to the model.

**Comment by HariBabuThubati** [comment]
@MuraliM : please advise me on the below issue : on click event the update values are populated.
https://jsfiddle.net/0amredgj/

**Comment by ckosloski** [comment]
Is this still an issue?  Did you figure out a solution?

**Comment by ckosloski** [comment]
@eugef it looks like he answered his own question since the plnkr has the computed value.  Please close.
