### ISSUE TITLE
ngTagsInput support question

### ISSUE THREAD

**Issue by kozer** [vitalets/angular-xeditable#365]
Hi!
I try to implement support for ngTagsInput.I follow the code style of the most directives and the code is this.
angular.module('xeditable').directive('editableTag', ['editableDirectiveFactory',
  function(editableDirectiveFactory) {
    var dir= editableDirectiveFactory({
      directiveName: 'editableTag',
      inputTpl: '<tags-input display-property="tag" ></tags-input>',
      render: function() {
       this.parent.render.call(this); 
      }
    }); 
    return dir;
}
]);

Everything works as expected for the first time.
The second time this error occurs:

[$compile:ctreq] Controller 'tagsInput', required by directive 'tiTagItem', can't be found!

Can you please guide me on how i can solve this?

Thanks in advance...

**Comment by kashyp** [comment]
Was facing the same issue, try adding on-tag-added on-tag-removed

**Comment by kashyp** [comment]
Facing similar Issue, were you able to get around this?

**Comment by josoroma** [comment]
Facing similar Issue here too :+1:

**Comment by madhurahuja** [comment]
I was able to have it working. Sharing just in case you have the similar requirement-

`//textarea
angular.module('xeditable').directive('editableTagsinput', ['editableDirectiveFactory',
  function(editableDirectiveFactory) {
    return editableDirectiveFactory({
      directiveName: 'editableTagsinput',
      inputTpl: '<tags-input min-tags="1" max-tags="3" ng-model="tags" display-property="itemDesc" class="ti-input-sm" template="tag-template" add-from-autocomplete-only="true">      <auto-complete source="loadTags($query)" load-on-focus="true" load-on-empty="true" template="autocomplete-template"></auto-complete></tags-input>',
      addListeners: function() {
        var self = this;
        self.parent.addListeners.call(self);
        // submit textarea by ctrl+enter even with buttons
        if (self.single && self.buttons !== 'no') {
          console.log(self);
          self.autosubmit();
        }
      },
      autosubmit: function() {
        var self = this;
        self.inputEl.bind('keydown', function(e) {
          if ((e.ctrlKey || e.metaKey) && (e.keyCode === 13)) {
            self.scope.$apply(function() {
              self.scope.$form.$submit();
            });
          }
        });
      }
    });
  }]);`

**Comment by canivel** [comment]
Thanks madhurahuja, I'm trying to do that with the editable-text fields but I don't know how to add the directive name to it since it's created on the fly... how did you do that?
Thanks!

**Comment by samaksh-vokal** [comment]
Just add `e-add-from-autocomplete-only="true"` to the outer `<span>` like so:

```
<span editable-tags-input="model.tags" 
      e-ng-model="model.tags"
      onaftersave="updateTagsAndSave(model)"
      e-add-from-autocomplete-only="true">
```
