### ISSUE TITLE
JS Errors

### ISSUE THREAD

**Issue by chadpry** [vitalets/angular-xeditable#367]
I've followed the install instructions in detail and I'm getting the following errors

Uncaught SyntaxError: Unexpected token < in xeditable.js on line 1
and
Uncaught Error: [$injector:modulerr]

when I add 'xeditable' to my module declaration

var kbApp = angular.module('kbApp', ['ngResource','ngCookies','xeditable']);

Thanks in advance.

**Comment by ckosloski** [comment]
Have you tried with a more recent version?

**Comment by ckosloski** [comment]
@chadpry are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
