### ISSUE TITLE
Buttonless (Save on mouse out)

### ISSUE THREAD

**Issue by netizen0911** [vitalets/angular-xeditable#368]
Hi,

I really love your work. It's beautiful. Is there any way to have it buttonless with auto-submit on mouse out or focus out? I've seen few web apps that use buttonless editable texts and I find them pretty cool.

Cheers,
Paul G.

**Comment by jasongraff** [comment]
I got around that by modifying line 609:

line in 1.9:
<code>self.editorEl.attr('blur', self.attrs.blur || (self.buttons === 'no' ? 'cancel' : editableOptions.blurElem));</code>

my version:
<code>self.editorEl.attr('blur', self.attrs.blur || (editableOptions.blurElem));</code>

Then set blurElem to 'submit' up in the editableOptions section.

Hope this helps.

Thanks for your work, Vitaly!

**Comment by kkulikowski** [comment]
Or you can just use buttons="no" blur="submit" onbeforesave="someCtrl.updateContact(contact)", it will run submit when you loose focus on form, then it will run function inside your onbeforesave (or onaftersave).
Its easier this way, and you dont have to edit directive.

**Comment by ckosloski** [comment]
This looks to be answered with the last comment.
@eugef please close.
