### ISSUE TITLE
When no buttons shown 'tab' keeps input in editing mode

### ISSUE THREAD

**Issue by rgudkov** [vitalets/angular-xeditable#370]
Click on editable and then tab out of it: input stays in editing mode
http://jsfiddle.net/0s8kmozq/

**Comment by ezk84** [comment]
This happens even with `blur="submit"`, I would've thought the blur even ifres whenever focus is lost in the inpuit.

**Comment by CraigWarford** [comment]
This happens for me as well.  In addition, clicking a different xeditable control leaves the previous ones in an edit state.  I have to click a non-xeditable control to get it to reset them all.

**Comment by chnldw** [comment]
Same issue here...

**Comment by alessandroneri90** [comment]
same here from 0.1.9

**Comment by violetbobo** [comment]
@CraigWarford same issue! Clicking a different xeditable control leaves the previous ones in an edit state.

**Comment by ckosloski** [comment]
This might be fixed by pull request #414

**Comment by eugef** [comment]
Fixed by #414
