### ISSUE TITLE
Edit mode keeps opened when clicking in other field

### ISSUE THREAD

**Issue by icruces** [vitalets/angular-xeditable#371]
This happens in verison 0.1.9:
http://jsfiddle.net/qq628hpm/2/

Click on field 1, then click on field2.

**Comment by alessandroneri90** [comment]
same

**Comment by gs11** [comment]
Same issue here..

**Comment by NickAb** [comment]
Is there any workaround or should we wait for new release for it to be fixed and use 1.8.0 meanwhile?

Any downsides in using 1.8.0?

**Comment by ckosloski** [comment]
Can you try this in the latest release?

**Comment by ckosloski** [comment]
@eugef this should be fixed with the latest release, please close.
