### ISSUE TITLE
Restangular support or examples, problem with remote validation

### ISSUE THREAD

**Issue by heridev** [vitalets/angular-xeditable#372]
I want to make some validations aftersave using Restangular if I use regular http.error it works for instance:
```
return $http.post('/saveUser', $scope.user).error(function(err) {
  $scope.editableForm.$setError('email', 'Unknown error!');
});
```

but it is not working if I use:

```
successCallback = function() {
  $scope.editableForm.$setError('email', 'Unknown error!');
}

errorCallback = function() {
  $scope.editableForm.$setError('email', 'Unknown error!');
}

$http.post('/saveUser', $scope.user).then(successCallback, errorCallback);
```
Even tough the error is added the form is closed.
Why?

And what about Restangular?
As an example:
```
AutoresponderApp
  .factory('SubscriberService', ['Restangular',
                                 function(
                                   Restangular
                                 ) {
    var model;

    model = 'api/v1/subscribers';

    return {
      update: function(subscriberId, extra_params) {
        return Restangular.one(model, subscriberId).get(extra_params);
      },
    };
  }
]);

SubscriberService.update(3000, _data).then(function(subscriber) {
  $scope.editableForm.$setError('email', 'Unknown error!');
}, function(errorResponse) {
  $scope.editableForm.$setError('email', 'Unknown error!');
});
```

It's not working, seems like the error is added but the form is closed, though.

Any ideas? I know that I can use promise and defer but I would like to use Restangular, should I use an interceptor or something like that?

thanks

**Comment by hungdoan2** [comment]
Well, I think you are doing validation in the wrong way.  It won't work with `angular-xeditable` because angular-xeditable will append a new form for each model then do validation him self (his way).
You can take a look at this sample: http://vitalets.github.io/angular-xeditable/#validate-remote

**Comment by heridev** [comment]
That makes sense, based on my needs seems like maybe It is better to not use angular-xeditable, because when I post my form I would receive different kind of errors and I need to have total control on that and I just want to make one post request for the whole form which includes multiple fields and every field would return different kind of validation errors, thanks

**Comment by hungdoan2** [comment]
I finally got you;
1. Can I use Restangular? : yes, for sure you can use any library if they return the "right format" - which will be accepted. (for example: Restangular return a promise).
2. "I just want to make one post request for the whole form which includes multiple fields and every field would return different kind of validation errors" : 
Yes : but you have to do a little "hacking"(actually this is not a good solution, but It makes your work done): 
Change your code: 
````
$scope.editableForm.$setError('email', 'Unknown error!');
````
to 
````
function setError(inputName, errorMsg){
   var elm = angular.element(document.querySelectorAll("[name=inputName]"));  
   return elm.scope().$error = errorMsg;

}
setError('email', 'Unknown error!');
````
Here is an example:
http://jsfiddle.net/5ju0s6kv/1/

**Comment by heridev** [comment]
that's a great example, thanks for pointing out a posible solution, I'll give it a try, thanks

**Comment by heridev** [comment]
@hungdoan2 FYI: I'm trying to make it work using your example but guess what?

When the request returns an error in Restangular seems like the form is already removed(hidden) so not able to find the input. :(

```
SubscriberService.update(myId, _data).then(function(subscriber) {
  // seems like here the form is already hidden or at least not present in the DOM
}, function(errorResponse) {
  // seems like here the form is already hidden or at least not present in the DOM
});
```

In fact, it is working using the example tough:
```
        var d = $q.defer();
        $http.post('/api/v1/subscribers/validate_email', _data).success(function(res) {
          res = res || {};
          if(res.status === 'ok') { // {status: "ok"}
            d.resolve()
          } else { // {status: "error", msg: "Username should be `awesome`!"}
            d.resolve(res.msg)
          }
        }).error(function(e) {
          d.reject(e.error);
        });
        return d.promise;
```

**Comment by hungdoan2** [comment]
@heridev could you give me a live sample ?.
1. You have to use `var d = $q.defer();`  to handle output. Because angular-xeditable itself can't check if there is an `invalid business validation` in `responsed request`
You have to tell him if a model is invalid (by `d.reject(e.error)`).
2. You can use `var d = $q.defer();`  with `Restangular` as well. 
Your code might be like this : 
````
 var d = $q.defer();
 Restangular.one(model, subscriberId).get(extra_params).then(function(res) {
          res = res || {};
          if(res.status === 'ok') { // {status: "ok"}
            d.resolve()
          } else { // {status: "error", msg: "Username should be `awesome`!"}
            d.resolve(res.msg)
          }
        }).error(function(e) {
          d.reject(e.error);
        });
````
(So sorry , I have never used  Restangular before, so I use pseudo code instead)
3. `When the request returns an error in Restangular seems like the form is already removed(hidden) so not able to find the input` : 
Does your query/selector is correct ?
It's hard to figure out what is the problem without a live demo (or at least HTML/JS codes that you implemented).

**Comment by heridev** [comment]
@hungdoan2 I get it, I really apreciate your help and now it is working yaay, let me add the whole example just in case anyone is interested:

The service:
```
AutoresponderApp
  .factory('SubscriberService', ['Restangular',
                                 function(
                                   Restangular
                                 ) {
    var model;

    model = 'api/v1/subscribers';

    return {
      validateEmailSubscriberUpdate: function(params) {
        return Restangular.all(model + '/validate_email').post(params);
      },
    };
  }
]);
```

The controller:
```
var d = $q.defer();

SubscriberService.validateEmailSubscriberUpdate(_data).then(function(successResponse) {
  d.resolve()
}, function(errorResponse) {
  d.reject(errorResponse.data.error);
});

return d.promise;
```

In my case, when there is a validation error the server will respond with 422 status and will return the validation error message as well just like this:
```
{ data: {error: 'validation error'}, status: 422, statusText: "Unprocessable Entity }
```

So there you go, thank you again Hung Doan ,let me know if you want me to add this example in any wiki, readme of something, and feel free to close this issue whenever you want.

**Comment by hungdoan2** [comment]
You are welcome. 
ah, I'm not the collaborator of this project, @vitalets will decide to close issue for you, later ^^.

**Comment by ckosloski** [comment]
@eugef can you close this issue?
