### ISSUE TITLE
Editing Textarea and save when reload page new edits displays

### ISSUE THREAD

**Issue by Ganzman** [vitalets/angular-xeditable#373]
Your app is what i need integrates nicely with Bootstrap.
The issue is - 
I want to have a page with text area that can be edit and updated after edit.
How to i accomplish this.

Thank you
Ganzman

**Comment by hungdoan2** [comment]
I don't get you.  Is there something wrong with texarea (http://jsfiddle.net/NfPcH/32/)

**Comment by Ganzman** [comment]
How can i add more <div id="edit" contenteditable="true">  in another container?

**Comment by Ganzman** [comment]
Sorry I solve that issue but how to disable editable contents after saving?

**Comment by ckosloski** [comment]
You should be able to add a `e-ng-disabled` attribute with a check on your textarea.

**Comment by ckosloski** [comment]
@eugef question is answered, please close.
