### ISSUE TITLE
callbck in Angular

### ISSUE THREAD

**Issue by izzusan83** [vitalets/angular-xeditable#375]
Hi,
I need your help....
in Angular there is any callback when you press the button ok?

I have the html menu with ng-repeat and i need change some value... but there isn't any callback for understand when you press the button ok or cancell..
Thanks

				<ul ng-repeat="parentMenu in menuLev1" repeat-end="onEnd()">
					<li>
						<a ng-click="checkComponentMenu(parentMenu.uuid_parent)" id="{{parentMenu.uuid_parent}}" href="#/" editable-text="parentMenu.res.value">{{parentMenu.res.value}}</a>
						<ul ng-repeat="subMenu in parentMenu.res.child">
							<li>
								<a ng-click="checkComponentMenu(subMenu.uuid_parent)" id="{{subMenu.uuid_parent}}" href="#/" editable-text="subMenu.subRes.value">{{subMenu.subRes.value}}</a>
								<ul ng-repeat="subSubMenu in subMenu.subRes.child">
									<li>
										<a ng-click="checkComponentMenu(subSubMenu.uuid_parent)" class="editMenu" id="{{subSubMenu.uuid_parent}}" href="#/" editable-text="subSubMenu.subSubRes.value">{{subSubMenu.subSubRes.value}}</a>
									</li>
								</ul>
							</li>
						</ul>
					</li>
				</ul>

**Comment by hungdoan2** [comment]
There are `onaftersave` and `oncancel` events (http://vitalets.github.io/angular-xeditable/#ref-element).
Are these events meet your requirements ?

**Comment by izzusan83** [comment]
yes, thanks!
the best solution for me is onaftersave="EditMenu(param)"

Thank you.

**Comment by ckosloski** [comment]
I think this issue can be closed.
