### ISSUE TITLE
Controls lose focus on submit or cancel

### ISSUE THREAD

**Issue by r-coursera** [vitalets/angular-xeditable#376]
Hey, all the controls lose focus when submit or cancel is pressed. 
Please look at the error template you've given on your github page.

http://plnkr.co/edit/BjWwXIlYyyLvRnVwO8m8?p=preview

**Comment by ckosloski** [comment]
Can  you explain your issue some more?  Once you submit or cancel, the fields return back to links.  Are you expecting the link to have the focus?

**Comment by ckosloski** [comment]
@r-coursera are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
