### ISSUE TITLE
Logic inside the eForm

### ISSUE THREAD

**Issue by popsovy** [vitalets/angular-xeditable#379]
I have many editable-select fields in the same editable-form. I need to add logic for hiding / showing selects based on values of other selects while the form is shown. Basically, conditions like ng-show="data.typeID == ###" need to be added throughout the form, where "data" is the model, but that doesn't work because "data" is not updated until the form is saved. 

Which model can I reference to add UI logic while the editable-form is shown? Is there another way to accomplish this? 

Thanks.

**Comment by ckosloski** [comment]
Couldn't you use `e-ng-change` to hide/show the other fields?

**Comment by ckosloski** [comment]
@popsovy are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
