### ISSUE TITLE
How to implement tags mode editable input?

### ISSUE THREAD

**Issue by Cofyc** [vitalets/angular-xeditable#381]
Like this one:

![1](https://cloud.githubusercontent.com/assets/91730/10748431/f7fc3690-7c9a-11e5-8b56-28e2f0bcaf1a.png)

See https://vitalets.github.io/x-editable/demo-bs3.html?c=inline.

**Comment by mitcht** [comment]
This is not an actual issue with the project. Questions such as this are better suited to be posted on sites like stackoverflow.com, using their Q/A format. Thanks.
