### ISSUE TITLE
cannot add onbeforesave to editable-bstime

### ISSUE THREAD

**Issue by debonair** [vitalets/angular-xeditable#384]
I am failing to add an onbeforesave event to an editable-bstime field, is this possible and can I get an example of this. I have 2 field a start time and and end time and I want to validate that the start time is not after the end time before saving the values in the form

**Comment by ckosloski** [comment]
Can you provide a Plunker or JSFiddle showing your issue?

**Comment by ckosloski** [comment]
@debonair are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
