### ISSUE TITLE
Form with editable elements should have `editable-form` attribute.

### ISSUE THREAD

**Issue by b3n01t** [vitalets/angular-xeditable#389]
```Form with editable elements should have `editable-form` attribute.```
Exception raised with the following form element:

```
<form editable-form="editable-form" name="nameform" onaftersave="saveTable()" oncancel="cancel()">
```

it is fine when  **editable-form="editable-form"** is change to  **editable-form**

**Comment by ckosloski** [comment]
Per the documentation, it should be just `editable-form`.
