### ISSUE TITLE
highlighting specific search word 

### ISSUE THREAD

**Issue by kiev78** [vitalets/angular-xeditable#392]
Hi, I have a list of editable text elements. There are about 100 of them so I have a search filter and pagination. I would like to allow the filter to highlight a matched search query in each element in my repeater which is xeditable.

Any help is much appreciated, thank you!

**Comment by ckosloski** [comment]
Are you trying to highlight the text that is displayed when the input field is not displayed, or are you trying to highlight text in the input field?

**Comment by kiev78** [comment]
highlight the text that is displayed, not the input field.

**Comment by ckosloski** [comment]
Here is an example of highlighting text using a client side [function](http://stackoverflow.com/questions/15519713/highlighting-a-filtered-result-in-angularjs).

**Comment by ckosloski** [comment]
@eugef question is answered, please close.
