### ISSUE TITLE
form with editable elements should have `editable-form` error in angular material md-dialogue

### ISSUE THREAD

**Issue by bmrinal** [vitalets/angular-xeditable#393]
The editable elements works fine in the normal template but not inside a modal dialogue. I have passed $scope as the scope option to the mdDialog configuration.

**Comment by ckosloski** [comment]
Can you add a Plunker or JSFiddle showing your issue?

**Comment by ckosloski** [comment]
@bmrinal are you still having issues?

**Comment by bmrinal** [comment]
@ckosloski I used some other control for the same. Didn't checked after that. Closing this issue at this time.
