### ISSUE TITLE
Naming attributes in a non-HTML5 way causes problems

### ISSUE THREAD

**Issue by fixundfertig123** [vitalets/angular-xeditable#394]
Hi everyone,

thanks for this great library. Slim and nice. However, I run in some problems due to the Non-HTML5 attribute naming used by you. You are using angular event-looking names, which do not correspond to the actual events in HTML, e.g. onbeforesave, onaftersave. Since this causes problems when using highly secure web frameworks like liftweb (which partly remove non-conform attributes) it would be great if the attribute names would renamed starting with "data-", as suggested by html5.

Cheers, Fritz

**Comment by ckosloski** [comment]
Using "data-" works fine for me

```html
<span data-editable-text="character.movie" data-e-name="movie" data-e-form="characterform" data-e-readonly>
    {{character.movie}}
 </span>
```

**Comment by fixundfertig123** [comment]
Hi,

I must have been tired. Wrote the solution and did not even tested it myself. You are right, it works. I was blindly trusting the docs, in which the attributes "onbeforesave, onaftersave" where described without "data-" prefix. Adding the prefix solved the problem for me. Howoever, it might me useful to update the docs using the "data-" prefix to be conform to HTML5.

Cheers Fritz

**Comment by ckosloski** [comment]
I have updated some of the documentation in a recent pull request to include the "data-" prefix.  I think this issue can be closed.

**Comment by fixundfertig123** [comment]
@ckosloski Great thanks!
