### ISSUE TITLE
ng-click in editable-text

### ISSUE THREAD

**Issue by itskashi** [vitalets/angular-xeditable#395]
Please see below. I want the editable-text to use 'ng-click' to show a map so that user can select the GPS point and it sends the data back to editable text field. But the ng-click does not work with the editable-text. Is there a way that user can click on the editable-text and fire the event. 

`<span editable-text="node.GPSData" e-name="GPSData" e-form="rowform" onbeforesave="checkGPSData($data)" ng-click="onGWGPS(node.GPSData)"> 24.98, 121.90</span>`

**Comment by nailaandleeb** [comment]
i have same issue with ng-change.

     <td> <a href editable-bsdate="std.payment_date" e-datepicker-popup="dd-MMMM-yyyy" ng-    change="p_date(std)">{{ (std.payment_date| date:"dd/MM/yyyy")||today}}</a></td>

i am trying to get date in controller when one is selected.....
@itskashi have u got it working???

**Comment by nailaandleeb** [comment]
hey got it working by using   "onaftersave="p_date(std)" instead of ng-change or ng-click.

**Comment by ckosloski** [comment]
I believe you have to use `e-ng-click` in order for it to be put on the text field that is created.

**Comment by ckosloski** [comment]
@eugef question is answered, please close.
