### ISSUE TITLE
editable-number allows 'e' to be entered

### ISSUE THREAD

**Issue by jewkesy** [vitalets/angular-xeditable#396]
![screen shot 2015-12-08 at 14 34 12](https://cloud.githubusercontent.com/assets/1673570/11658110/e2de3918-9db8-11e5-96fb-c2191fb8c5b1.png)
An editable-number element allows you to type the character 'e'.

The validation does stop the form submitting, however. 

Happens here: -
http://vitalets.github.io/angular-xeditable/#html5-inputs

and here: -
http://jsfiddle.net/NfPcH/82/

Happens in Chrome / MacOs

**Comment by Sheparzo** [comment]
This is happening to my app too

**Comment by daggmano** [comment]
I'm unable to find any reference to this online, but I expect the 'e' character is required for specifying exponents (2.7e2 = 270).  However, the allowance of repeated 'e' chars doesn't make sense, and xeditable does not seem to interpret the result correctly.  Nonetheless, this may be down to HTML5 ather than an xeditable bug.

**Comment by ckosloski** [comment]
Yes, 'e' is for exponents and is allowed in the input.  This is an HTML5 issue.  If you don't want the 'e', you will have to add a onchange or onbeforsave call to do some validation or to clean the input.
