### ISSUE TITLE
wrap a input without creating a directive

### ISSUE THREAD

**Issue by codigoalvo** [vitalets/angular-xeditable#398]
There is any easy way to wrap an input without creating a custom directive?
I'm using Angular Material, and for inputs take the custom apearance they need to be wraped with  <md-input-container>.
So, I don't wanto to have to create a directive just for a simple wrap.
Can you expose the wrap method that I saw anyway in your code so I can pass wrap tags direc on the span attribut for my xeditable field ?

Thanks in advance.

**Comment by mitcht** [comment]
This is not an actual issue with the project. Questions such as this are better suited to be posted on sites like stackoverflow.com, using their Q/A format. Thanks.
