### ISSUE TITLE
Is it possible to use editable-form on a non-form element? 

### ISSUE THREAD

**Issue by christandy** [vitalets/angular-xeditable#399]
I'd like to have multiple editable-form areas on a single page, and within a single form element. Is it possible to do this using a different element besides form, or otherwise somehow trigger multiple fields to be editable as some sort of group and only have one set of submit/cancel buttons for each group? Thanks for any help.

**Comment by mitcht** [comment]
Question is better suited for sites like stackoverflow.  Not an issue.

**Comment by ckosloski** [comment]
@eugef I think this can be closed
