### ISSUE TITLE
Ability to enable/disable certain table row cells

### ISSUE THREAD

**Issue by zimbiku** [vitalets/angular-xeditable#403]
I have a table that works great; it has 1 date picker, 2 selects, and a text box.  From following the edit table row form example, when I click edit, the entire row gets enabled for edit.  Is there a way to only turn on certain columns?  For instance one of my selects is a status column.  If that value is 'complete' I don't want the user to edit anything except the text box for description.  So basically per row I want to decide which columns to enable.  Is this possible?  (I can provide code examples too if that would help explain)

**Comment by ckosloski** [comment]
Can't you do something like `e-ng-disabled="model.value == 'complete'"`

**Comment by ckosloski** [comment]
@eugef question is answered, please close.
