### ISSUE TITLE
Using filters in editable-text attribute

### ISSUE THREAD

**Issue by koljada** [vitalets/angular-xeditable#409]
I want to deal with encoded/decoded strings in my editable table. So one of my field looks like:

```
<td>
       <span editable-text="item.name | decodeURIComponent" 
                  e-name="name" 
                  e-form="rowform" 
                  e-required>
               {{item.name | decodeURIComponent }}
       </span>
</td>
```

Where decodeURIComponent - is my custom filter. But when I try to save changes the error occurs in save method of EditableController  because in this case valueGetter after calling valueGetter = $parse($attrs[self.directiveName]) doesn't have assign method. 
How can I use filters in editable-text attribute?
Here is the demo: http://jsfiddle.net/NfPcH/12546/

**Comment by ljfolino** [comment]
I am having a similar issue.  I have found a partial work around for this.  If you set a `ng-blur="$data=function($data)"` and have the function return a value it should set it correctly.  The issue I am having is the initial filer on show.  Also you have to set a variable to the filter so you will need something like `var returnVal = $filter('filter')(data,format);`
`return returnVal`
I had issues when trying to use `return $filter('filter')(data,format);`

**Comment by ljfolino** [comment]
So I figured out how to set the initial filter on the data.  I pass the name of the item into a function and pass the form.  I then do a look up for the item using ` var editable = _.find(form.$editables, { name: name });` and then update the data on the element using `editable.scope.$data = value`.  I am using lodash to find the element.

**Comment by markyboryslav** [comment]
my temporary work around
`editable-text="item.filtered_value"   onshow="getFilteredValue(item)"`
and
`
    $scope.getFilteredValue = function(item) {
         item.filtered_value = /*some changes */ ;
    };
`

**Comment by ckosloski** [comment]
The editable is expecting a model,  not a filtered value.  You should be able to apply filters to the editable input or use the work arounds listed above.

@eugef I think this can be closed.
