### ISSUE TITLE
Editable rows with editable-select, on adding new row, how to make the drop down appear automatically

### ISSUE THREAD

**Issue by realisation** [vitalets/angular-xeditable#412]
In the example for this I notice that when you add a row, then immediately the drop down is shown as obviously clickable - basically that the `rowform.show()` function has fired somehow. But I don't see where that's firing in the example upon creating a new row, and therefore in the example's case, a new user object in the repeated array of users.

I solved this with a sort of hacky code where I passed `rowform` through the `showGroup` function and called `rowform.show()` in the case that the group's id is zero, as it is after being created and pushed into the array, awaiting selection in the drop down.

But how is it the example accomplishes this automatically? Here's the JS fiddle: http://jsfiddle.net/NfPcH/93/

**Comment by ckosloski** [comment]
When you click add row, it calls the addUser function which adds a new item to the array. 

Is there a specific issue you are having with this?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
