### ISSUE TITLE
isDefaultPrevented check in editableForm prevents blur when it should occur

### ISSUE THREAD

**Issue by mgerring** [vitalets/angular-xeditable#415]
There's a check in the document click handler for editableForm that prevents the form from being cancelled in many cases where it should be -- for example, clicking links using `ui-sref` from angular ui router, or opening modals in angular ui bootstrap. 
 
In these cases the default behavior of a link is prevented, but form blur still takes place as expected. The editable form is actually blurred and should be cancelled, but the x-editable code bails out anyway because preventDefault was called on the link.

#414 fixes the issue.

**Comment by eugef** [comment]
Fixed by #414
