### ISSUE TITLE
How can I tie two editable texts together

### ISSUE THREAD

**Issue by jlebrech** [vitalets/angular-xeditable#417]
In the following I want it to mutually open the `entry.value` or `entry.name ` together as a pair.

      <table class="table table-striped">
        <tr ng-repeat="entry in entries">
          <td ng-if="entry.deletable"><a href="#" editable-text="entry.name" e-style="width: 100%">{{entry.name}}</a>
          <td>
            <a href="#" editable-text="entry.value" e-style="width: 100%">{{ entry.value || "empty" }}</a>
          </td>
        </tr>
      </table>

I tried with e-form but it's needs a column for the buttons, I just need to open both editables in a row and only display one set of buttons as if it were just one editable.

**Comment by ckosloski** [comment]
Did you check out the editable row example - http://vitalets.github.io/angular-xeditable/#editable-row
You need to set the "e-form" attribute on your editable entries and then wrap your buttons in an editable-form.

**Comment by mitcht** [comment]
This is not an actual issue with the project. Questions such as this are better suited to be posted on sites like stackoverflow.com, using their Q/A format.
