### ISSUE TITLE
xeditable save button not working when used inside ng-repeat

### ISSUE THREAD

**Issue by dasdipankar** [vitalets/angular-xeditable#419]
Here is the template i am using
```

<item ng-repeat="phonenumber in contact.phoneNumbers"  >
	         <a href="#" editable-text="phonenumber.value" > 
	         	{{phonenumber.value}}</a>          
</item>
```
Cancel button works, where as save button doesnt.
PS: outside ng-repeat loop its work perfectly.

**Comment by dasdipankar** [comment]
```
<div ng-repeat="phonenumber in contact.phoneNumbers"  >
             <a href="#" editable-text="phonenumber.value" > 
                {{phonenumber.value}}</a>          
</div>
```
modified 'item' tag with 'div' and it worked

**Comment by mitcht** [comment]
Try implementing e-single, or make sure your item each item has a unique name. I bet if you check your form in bats tang, you will see what I'm talking about.

**Comment by mitcht** [comment]
Batarang. Not bats tang. Stupid autocorrect.
