### ISSUE TITLE
angular xeditable not working for the elements which are nested in form tag

### ISSUE THREAD

**Issue by VidyaPatil** [vitalets/angular-xeditable#421]
I have added 
```

<form name="Myform">
<a href="#" class="pull-left" editable-text="name">{{name || 'empty' }}</a>
</form>
```

Not working

**Comment by ckosloski** [comment]
Did you try calling a function that returns the correct value?

**Comment by VidyaPatil** [comment]
Just updated issue . please check

**Comment by ckosloski** [comment]
What exactly are you trying to do with `{{name || 'empty' }}`?
Are you trying to print "empty" if name is empty?

If so, take a look at this [fiddle](https://jsfiddle.net/ckosloski/rk9qxa12/16/)

**Comment by daggmano** [comment]
Fiddle is broken as xeditable script has incorrect mime type and will not execute.

**Comment by Anto4C** [comment]
It's the same problem of issue [#6](https://github.com/vitalets/angular-xeditable/issues/6) 
in the replies you can find some workarounds but nothing that will work as expected

**Comment by VidyaPatil** [comment]
Yeah exactly same issue. form validation already there in xeditable plugin. But form with xeditable is not working !!

**Comment by tkanapar** [comment]
Workaround add the following into your input elements
`class="editable-click" ng-click="$form.$show()" e-ng-blur="$form.$hide()"`

**Comment by VidyaPatil** [comment]
Yes fixed issue!
