### ISSUE TITLE
x-editable <Select> default option (text) for not selected option.

### ISSUE THREAD

**Issue by RupenAnjaria** [vitalets/angular-xeditable#423]
Please refer to the example provided in angula-xeditable documentation.
http://vitalets.github.io/angular-xeditable/#editable-table

if we click on "Edit" then the **status** column for second row shows blank option (as the value was not selected). I want to show a Text for the not selected option e.g. "-- Please Select --" instead of blank option. 
Kindly note that I would like to avoid to touch data (JS or JSON). It should be straight from HTML like we do for normal "Select" control.

Any reference? Thank you.

**Comment by david12341235** [comment]
+1
It may not make sense as HTML in the element body, since that usually contains the display element (currently selected option). But maybe as an extra attribute like "e-placeholder"?

**Comment by ckosloski** [comment]
This was fixed with pr #429
