### ISSUE TITLE
Option to select the text on focus

### ISSUE THREAD

**Issue by kanakiyajay** [vitalets/angular-xeditable#43]
When the an element is clicked for entering into x-editable mode,
how to select all the text already present ?

There is a native javascript function to do `[input].select()`

I tried putting `onshow="selectText()`

and in `selectText()`

```
$("input).focus(function(){
    this.select();
});
```

But it did not work.

**Comment by dvnrsn** [comment]
Updated @vitalets fiddle to angularjs 1.6 because I'm not exactly following what was made available via those commits. http://jsfiddle.net/NfPcH/21066/
