### ISSUE TITLE
Autocomplete in an editable-text or in a new row

### ISSUE THREAD

**Issue by canivel** [vitalets/angular-xeditable#431]
Hi, I can'f find how to implement a autocomplete in a editable-text or in a new row when added, is that possible? do you have a example?

Thank you.

**Comment by ckosloski** [comment]
Are you referring to something like [this](https://angular-ui.github.io/bootstrap/#/typeahead)?

**Comment by ckosloski** [comment]
@eugef question is answered, please close.
