### ISSUE TITLE
editable text malfunctions inside a form

### ISSUE THREAD

**Issue by tibetty** [vitalets/angular-xeditable#432]
I works pretty well when I put it outside a form, but it's moved in, any click on <a href="#"> will cause a direct jumping to "/#".  Any solution to this issue?

I found somebody reported a similar issue before and went through the entire thread, but unluckily it was sidetracked and I did not find the real solution.

**Comment by ckosloski** [comment]
Can you add a jsFiddle showing this issue?

**Comment by ckosloski** [comment]
@tibetty are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
