### ISSUE TITLE
Typeahead not working with ui-bootstrap > 0.14.3

### ISSUE THREAD

**Issue by SylTi** [vitalets/angular-xeditable#435]
I suppose it's the same thing with other components relying on it.
It probably come from the renaming of the directives from ui-bootstrap: 
typeaheadParser is now deprecated. Use uibTypeaheadParser instead.
typeahead is now deprecated. Use uib-typeahead instead.
typeahead-popup is now deprecated. Use uib-typeahead-popup instead.

Any workaround before the fix ? (linked to that I suppose https://github.com/vitalets/angular-xeditable/pull/406)

**Comment by eugef** [comment]
Fixed by #443
