### ISSUE TITLE
Vertical Scrollbar in Textarea in IE11

### ISSUE THREAD

**Issue by ibirrer** [vitalets/angular-xeditable#439]
The textarea example at https://vitalets.github.io/angular-xeditable/#textarea displays a vertical scrollbar when entering/editing text that is longer than the width of the textarea in IE11. Chrome and Firefox do not show the scrollbar and wrap the text.

I suggest that IE11 should behave the same as Chrome and Firefox.

Changing the white-space css property from `nowrap` to `pre` seems to solve the issue.

**Comment by ckosloski** [comment]
You can always override the css with your own.

**Comment by ibirrer** [comment]
Thanks for your response. That's what I am actually doing. Just wanted to inform you about this glitch in the example code.

**Comment by eugef** [comment]
@ibirrer, would be nice if you create the PR with the css fix.
