### ISSUE TITLE
Repeater seems to repeat on every gui change

### ISSUE THREAD

**Issue by schadedk** [vitalets/angular-xeditable#44]
I'm imlementing an editable row, similar to the demo on JSFiddle.

The repeater seems to be running every time you do a minor change in the gui. This is very heavy, and should not be necessary. 

Example:
1. Choose to edit a row (the repeater is run)
2. If you type something in an input-field, whenever you hit a key, the repeater is executed.

I guess that the repeater should run whenever the model has changes - but during 1. or 2, the model has not changed. 

That seems to be a lot of unnessesary dom updates - especially for large data tables. 

Ive forked the original fiddle and changed a few lines of code (look for my two comments):

http://jsfiddle.net/schade/CuLrm/

Try to edit a row and type something in the "name" field. Whenever you hit a key the status text is changed!

Is this really necessary?

**Comment by mitcht** [comment]
Closed as being too old
