### ISSUE TITLE
How to use async typeahead

### ISSUE THREAD

**Issue by takotuesday** [vitalets/angular-xeditable#445]
I am writing an editible text element that when selected will allow the user to take advantage of typeahead to select other values, which are returned from a search service. With ui-bootstrap typeahead you can do something like this:

``` javascript
uib-typeahead="address for address in getLocation($viewValue)"
```

where the $viewValue (searchTerm) is passed to the async search function getLocation. I'd like to do something similar with xeditable, but I have yet to figure out how to do this, and I havent been able to find anything in the documentation about how to do this. Any help would be greatly appreciated. Thanks!

**Comment by ckosloski** [comment]
Taking a couple of examples I put together a crude example that worked for me (although it did seem slow).

`<div ng-controller="TypeaheadCtrl">
  <a href="#" editable-text="user.state" e-uib-typeahead="state for state in getState($viewValue) | limitTo:8">
    {{ user.state || 'empty' }}
  </a>
</div>`

`app.controller('TypeaheadCtrl', function($scope, $filter, $http, $q) {
  $scope.user = {
    state: 'Arizona'
  };

  $scope.states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Dakota', 'North Carolina', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'];

  $scope.getState = function(item) {
    var d = $q.defer();
    $http.post('/checkName', {value: item}).success(function(res) {
      d.resolve($filter('filter')($scope.states, item));
    }).error(function(e){
      d.reject('Server error!');
    });
    return d.promise;
  };
});`

**Comment by ckosloski** [comment]
@eugef this has been answered, please close.
