### ISSUE TITLE
How do I: create fields that depends on each other

### ISSUE THREAD

**Issue by schadedk** [vitalets/angular-xeditable#45]
Hi,

I have two select local fields, were the content of one of them, should depend on the value of the other.

Eg: select 1: "Letters, "Digits"
Select 2: should contain "A","B","C" when select 1 is "Letters"
Select 2: should contain "1,"2","3" when select 1 is "Digits".

Is that possible to accomplish?

**Comment by ckosloski** [comment]
@pavi95 can you provide a jsfiddle/plunkr showing your issue?

**Comment by ajjublr** [comment]
Yeah, please do so...

**Comment by pavi95** [comment]
@ckosloski  @ajjublr Thanks for your valuable time man. I found this fiddle.. It helps me out.. https://jsfiddle.net/32kzsvve/1/ it may help others
