### ISSUE TITLE
Angular Xeditable Grid is not working with Typeahead

### ISSUE THREAD

**Issue by Sampath-Lokuge** [vitalets/angular-xeditable#453]
Hi,

I have tried as shown below.But it is not working.Could you tell me why ? Thanks.

```
<span editable-select="user.status" e-name="status" e-form="rowform" 
        e-typeahead="s.value as s.text for s in statuses | filter:$viewValue">
          {{ showStatus(user) }}
  </span>
```

Here is the : [Fiddle](http://jsfiddle.net/sampath_lokuge/NfPcH/14612/)

**Comment by ckosloski** [comment]
Have you tried building the latest version?  There were some changes in a recent commit to work with the latest version of ui-bootstrap.

**Comment by Sampath-Lokuge** [comment]
@ckosloski Actually if you see the above example then it uses latest build (2016-03-24).But still it is not working.Am I missing something on the above fiddler ? Thanks.

**Comment by ckosloski** [comment]
You need to download and build it yourself.  The uib changes are merged but not yet released.

**Comment by Sampath-Lokuge** [comment]
@ckosloski Thanks for the info.But could you tell me how to do that ? I'm an Asp.net (C#) developer.So Could you tell me the steps to do so and the editor which I have to use ? At this moment I do have Visual studio 2015.Thanks.

**Comment by eugef** [comment]
@Sampath-Lokuge, new version was just released, so you can instal it with `npm`

**Comment by Sampath-Lokuge** [comment]
@eugef Thanks.But still it is not working with `e-typeahead`.Could you give me a working example ? Thanks.

**Comment by Sampath-Lokuge** [comment]
@ckosloski But still it is not working with `e-typeahead`.Could you give me a working example ? Thanks.

**Comment by ckosloski** [comment]
Look at the examples here - http://vitalets.github.io/angular-xeditable/

It is using editable-text, not editable-select.

You could also try the new ui-select that was added.

**Comment by Sampath-Lokuge** [comment]
@eugef @ckosloski  Here is the updated [Fiddle](http://jsfiddle.net/sampath_lokuge/xo5c92e7/2/) which is not working.

**Comment by Sampath-Lokuge** [comment]
@ckosloski Is that mean can't we use the drop downs with the  `e-typeahead` ? Thanks.

**Comment by ckosloski** [comment]
I haven't tried that, but it sounds like you should try the ui-select.

**Comment by Sampath-Lokuge** [comment]
@ckosloski I have used `typeahead` with the Angular only drop downs. Which are working fine.The only problem is within the Xeditable grid which is not working ? Thanks.

Here is the AngulaJs drop down with the `typeahead`.Which is working.

```
<input name="contactType" id="contactType" type="text" placeholder="@L("OiEnterContactType")"
                           ng-model="vm.occupantDetail.contactType" typeahead="a as a.name for a in vm.contactTypes | filter:$viewValue" class="form-control" required> 
```

**Comment by Sampath-Lokuge** [comment]
@ckosloski The problem on the `ui-select` is, we cannot add a new item to the drop downs if that item is not in the popup list.But with `typeahead` we can do that.My requirement is that.That means,if a particular item was not there on the drop down then user can add it to the drop down.After that app will save that item into the table.Thanks.

**Comment by ckosloski** [comment]
Your AngularJS drop down example is using a text field.  The editable-text and typeahead should work the same.

**Comment by Sampath-Lokuge** [comment]
@ckosloski Very good point.I have done that way.But still it's having issue when user clicks the `Edit` button.When user clicks it shows the id of the property.How can I get rid of this ? Thanks.

```
 <span editable-text="user.status" e-name="status" e-form="rowform" 
        e-typeahead="s as s.text for s in statuses | filter:$viewValue">
          {{ showStatus(user) }}
 </span>
```

Here is the [Fiddle](http://jsfiddle.net/sampath_lokuge/xo5c92e7/5/)

**Comment by ckosloski** [comment]
Here is your [Fiddle](http://jsfiddle.net/ckosloski/8103rdkn/45/) working.

**Comment by Sampath-Lokuge** [comment]
Wow ... Thanks a lot @ckosloski   :smile:

If you don't mind can you put this answer on the [StackOverflow ](http://stackoverflow.com/questions/36623922/angular-xeditable-grid-with-typeahead) also.
