### ISSUE TITLE
X-editable date not working

### ISSUE THREAD

**Issue by afroz786** [vitalets/angular-xeditable#458]
The demo u have given in the website also doesn't work. please help

**Comment by ckosloski** [comment]
Can you be more specific?  What is your error.  I just tried the edtiable date on the demo site in Chrome and it is working for me.

**Comment by afroz786** [comment]
![image](https://cloud.githubusercontent.com/assets/14803995/14629456/7b7c1b4e-0624-11e6-9038-6d9b2e8f1530.png)

as u can see, the pop up button is not proper. and the code is also not complete.

**Comment by ckosloski** [comment]
Yes, the fiddle in the documentation is broken because it is using an older version of ui-bootstrap and thd the current release which requires a more recent version of ui-bootstrap.

The demo in the documentation does work properly - [http://vitalets.github.io/angular-xeditable/#bsdate](http://vitalets.github.io/angular-xeditable/#bsdate)

**Comment by vqanguyen** [comment]
The following code

e-uib-datepicker-popup="yyyy-MM-dd" 

does not work

```
It shows errors:

angular.js:12783 Error: [$compile:ctreq] Controller 'ngModel', required by directive 'uibDatepickerPopup', can't be found!
http://errors.angularjs.org/1.4.10/$compile/ctreq?p0=ngModel&p1=uibDatepickerPopup
    at angular.js:68
    at getControllers (angular.js:8432)
    at getControllers (angular.js:8439)
    at nodeLinkFn (angular.js:8570)
    at compositeLinkFn (angular.js:7965)
    at nodeLinkFn (angular.js:8561)
    at compositeLinkFn (angular.js:7965)
    at compositeLinkFn (angular.js:7968)
    at publicLinkFn (angular.js:7845)
    at c.n.show (xeditable.min.js:6)
```

i have the following versions:

angular 1.4.0, 
bootstrap 3.3.0
angular-bootstrap 1.3.0
angular-xeditable 0.1.12

Please helps. Thanks you.

**Comment by ckosloski** [comment]
Please see #450 and #449 for the missing model error.

**Comment by ckosloski** [comment]
Try using the latest release (0.2.0).  It looks like #489 might have fixed the issues.
