### ISSUE TITLE
Table Form with Date Picker throws errors after submit and re-edit

### ISSUE THREAD

**Issue by ianellis90** [vitalets/angular-xeditable#460]
Hi,

Please checkout my plnkr -> http://plnkr.co/edit/KzAwC1W0S7SZaG0wghl0

I'm trying to implement a table where some of the columns are date pickers but keep getting errors when opening the date picker again after submitting the table form. 

Steps to reproduce:

1. Click Edit button.
2. Open one of the date pickers and choose a date.
3. Click the Save button to submit the form.
4. Repeat steps 1 and 2 and you'll see the errors in the console.

Seems like the ngModelCtrl of the 'UibDatepickerController' is not being set the same second time around as the first.

**Comment by ckosloski** [comment]
Duplicate of #449 and #450

**Comment by ianellis90** [comment]
Excellent thanks for the help @ckosloski.
