### ISSUE TITLE
IE 11: When activationEvent is set to focus, on click event x-editable element blurs out.

### ISSUE THREAD

**Issue by himmittal** [vitalets/angular-xeditable#465]

**Comment by himmittal** [comment]
In IE 11, when activationEvent is set to focus, on click event x-editable element blurs out.

Can we have multiple activationEvent to enable edit mode through events like focus and click. Both would enable edit mode.

**Comment by himmittal** [comment]
Another Issue I found is that when I have editable-select element and any value is selected from drop down it loses its focus and therefore user navigating from keyboard has to tab through all the items again.

**Comment by ckosloski** [comment]
Do you have a jsfiddle or plunker showing this issue?

**Comment by jjreicher** [comment]
Running into the same issue...seems like not much activity here...

**Comment by ckosloski** [comment]
Do you have a plnkr/jsfiddle showing your issue?  This will help others investigate your issue.

I have a Mac, so not easy for me to test with IE11.

**Comment by jjreicher** [comment]
http://plnkr.co/edit/Mn4vnP9vYS9eFiWhaNYQ?p=preview

Works in Chrome. Doesn't work in IE11.

**Comment by ckosloski** [comment]
I couldn't get the plnkr site to load in IE11 ☹️

**Comment by jjreicher** [comment]
Well it's pretty simple anyways. Basically loads up fine. Then when you click on the item, it ONLY remains in the editable state while **actively** holding down the mouse-click. As soon as you let up on the mouse-click, it reverts to text state.

![pic1](https://cloud.githubusercontent.com/assets/13351061/23708717/c5a95920-03cb-11e7-944e-eab117fe1404.PNG)
![pic2](https://cloud.githubusercontent.com/assets/13351061/23708718/c5abe410-03cb-11e7-879b-91faaaceb6ee.png)

**Comment by allisonshaw** [comment]
This seems to be a problem in Chrome now too with a recent Chrome update...

http://jsfiddle.net/L4jnp28a/5/

Expected results: enter edit mode via 'click' or 'focus' (tabbing to element)
Actual results: When clicking, edit mode is active only as long as mouse is down. A single click opens then closes edit mode immediately.

**Comment by jjreicher** [comment]
I see it too in Chrome now. Hack solution has been to instruct users to
right-click first, then type in the field. But would obviously be better to
have a fix.
