### ISSUE TITLE
Controller 'ngModel', required by directive 'uibDatepickerPopup', can't be found!

### ISSUE THREAD

**Issue by kuceram** [vitalets/angular-xeditable#466]
Trying to solve this error https://github.com/vitalets/angular-xeditable/issues/450 by upgrading to latest angular-bootstrap I get a different error.

angular-bootstrap: 1.3.2
angular: 1.4.0
angular-xeditable: 0.1.12

```
<small editable-bsdate="myDate"
       e-name="my-date" e-uib-datepicker-popup="dd/MM/yyyy"
       e-is-open="data.isOpen" e-ng-click="data.isOpen = true" e-on-open-focus="false">
  {{(myDate | date) || 'empty'}}
</small>
```

**Comment by ckosloski** [comment]
Did you see my comments in #450 or the comments in #449?

**Comment by kuceram** [comment]
Well, I did but non of them helps me to solve both issue I rose. It seems to me that there is a bug in xeditable plugin as it doesn't handle the ng-model properly, however I didn't dig deep into the code...

**Comment by ckosloski** [comment]
Can you provide a JSFiddle/Plunker showing your issue?

**Comment by kuceram** [comment]
Sure, here it is: http://plnkr.co/edit/3Z6wvZROmdR6d1uJlRX5?p=preview When you click on the date it throws an error to console...

**Comment by ckosloski** [comment]
Here is your issue `e-uib-datepicker-popup="dd/MM/yyyy"`

It should be `e-datepicker-popup="dd/MM/yyyy"`

Here is a link to the [documentation](http://vitalets.github.io/angular-xeditable/#bsdate)

**Comment by zollinger** [comment]
I experience the same issue. The official demo has the same issue. Just try opening the datepicker twice:
https://vitalets.github.io/angular-xeditable/#bstime

**Comment by Sampath-Lokuge** [comment]
Thanks a lot @ckosloski It works for me  :smile:

**Comment by ckosloski** [comment]
Try using the latest release (0.2.0).  It looks like #489 might have fixed the issues.

**Comment by kuceram** [comment]
This actually fixes it...
