### ISSUE TITLE
textarea background is gray with courier like font - how to change it?

### ISSUE THREAD

**Issue by bojannyc** [vitalets/angular-xeditable#469]
text area (in display mode, before clicked to switch to edit mode) is gray with courier like font (see picture) - the styling is applicable only in edit mode. How to change initial styling (before edit) ?

![capture](https://cloud.githubusercontent.com/assets/18403178/15201454/1dc3eb1a-17bf-11e6-8848-899098c0710e.PNG)

**Comment by ckosloski** [comment]
You would have to create your own css file and create a definition for `pre {}` that defines the `font-family` and `color` that you want to use.

**Comment by bojannyc** [comment]
That works, thank you!
