### ISSUE TITLE
Custom Template

### ISSUE THREAD

**Issue by devmondo** [vitalets/angular-xeditable#47]
Hi, 
first thank you so much for bringing this to angular, it is awesome :)

is there a possibility to have the ability to add custom template? 

right now, i need to add Redactor.js as editor, checklist, radio group, but the current implementation does not allow that. it would be great if we have ability to assign custom template and as long as the controls inside of it have binding to scope of controller, then hitting accept or cancel would just apply the new values.

sorry if i did not explain it well, but i think it should be like when user change values in the custom template controls, no real updates would happen, but if he clicks accept icon, then changes would be propagated, this would give a lot of flexibility and freedom.

thanks in advanced.

**Comment by HariBabuThubati** [comment]
@vitalets  :I  am using http://vitalets.github.io/angular-xeditable/#editable-table for editing entire table , If table is having two or more rows and click on edit and i updated some values (text values) , on click event i want get those updated values in controller. can you please advise.
