### ISSUE TITLE
Add custom label to the edit element

### ISSUE THREAD

**Issue by Strae** [vitalets/angular-xeditable#471]
Would be great to have the possibility to add a label (or a short description) to show above the <input> element;

Sometimes the value that I need to show to "trigger" the edit state is a calculation of another value (the one that will be edited).

Use case: we have 3 values, `quantity`, `item per box` and `number of boxes`
`number of boxes` is dinamycally calculated as `quantity / itemPerBox`
In the HTML, we only want to show `quantity` and `number of boxes`, but clicking on `number of boxes` should let edit the `item per box` value:

`
<a href="#" editable-number="item.itemPerBox" buttons="no" ng-bind-html="item.boxesNum">
  {{item.boxesNum}}
</a>
`

When the edit state is triggered, we need a `<label>` or `<span>` to tell the user the value he is editing is not `boxesNum` but `itemPerBox`

**Comment by ckosloski** [comment]
What about using the [popover](http://angular-ui.github.io/bootstrap/#/popover) as an alternative?

**Comment by Strae** [comment]
@ckosloski to be honest I'll prefer to have a simple `<label>` or `<span class="input-label"></span>`, a popover can be an enhancement but not a replacement..
