### ISSUE TITLE
edit selecct doesn't work

### ISSUE THREAD

**Issue by navinSing** [vitalets/angular-xeditable#475]
```
 <a href="#" editable-select="user.status" e-ng-options="s  in ['a','b'] ">
   {{user.status}}
  </a>
```

**Comment by ckosloski** [comment]
Your ng-options is not correct.  Please take a look at the angular [documentation](https://docs.angularjs.org/api/ng/directive/ngOptions) to figure out the correct syntax you want to use.

**Comment by navinSing** [comment]
thanks !
