### ISSUE TITLE
How to add a class to the editable-text generated form?

### ISSUE THREAD

**Issue by bmwertman** [vitalets/angular-xeditable#476]
I have an editable-text element `<h3 editable-text="user-name" buttons="no ></h3>`. My styling centers the `<h3></h3>` at the bottom of it's parent `<div></div>`. 

When  `<h3></h3>` is selected and becomes editable the generated form pulls the `<h3></h3>` out of it's original position, out of view in my case. All that I can see is the cursor icon. 

setting `e-class` adds a class to the generated input which lets me set styles on it. But I'm restricted by the generated form. 

Adding `margin: 138px auto 0;` to the generated form in chrome inspector puts it back to the desired position.

Is there a way to add a class to the form generated when using ` editable-text`?

**Comment by ckosloski** [comment]
No, there currently is not a way to do this.
