### ISSUE TITLE
How to implement typeahead-loading?

### ISSUE THREAD

**Issue by chedched** [vitalets/angular-xeditable#486]
I'm trying to show a spinner when there is data being fetched in a typeahead.
Bootstrap comes with a function for this: typeahead-loading. I didn't see that anywhere in the code, so I guess that's not part of angular-xeditable (yet). 

What is the most intelligent way to implement this? There is a discussion about something quite similar here: https://github.com/vitalets/angular-xeditable/issues/478. However, I don't see how I could alter the templates of typeahead - I can't find them in the code at all. Can anyone give me a hint?

**Comment by ckosloski** [comment]
Did you try adding `e-typeahead-loading` to your input?

**Comment by chedched** [comment]
Yes, it didn't work. But as said, I can't see anything like that in the code, so I think that functionality is just not implemented.

**Comment by ckosloski** [comment]
There is nothing specifically implemented for the typeahead element in this project.  Do you have a Plunkr or JSFiddle showing your issue?

**Comment by chedched** [comment]
I just created one: http://plnkr.co/edit/l4ewWsVvvAg1OabXm2c3?p=preview. You can see the non-working xeditable at the top and the working typeahead without xeditable at the bottom.

**Comment by ckosloski** [comment]
Here is a working [fiddle](http://plnkr.co/edit/9fdgJTcvjOIf11lsMcKc?p=preview)

It seems to want a "full" object i.e. `user.loading`

**Comment by chedched** [comment]
Yes, that's the solution. Thank you so much for your help, I really appreciate it.

**Comment by ckosloski** [comment]
Sure, np.  You can go ahead and close this issue.
