### ISSUE TITLE
How would I use this in a commonJS environment (node ES6 angular app)

### ISSUE THREAD

**Issue by cliffordfajardo** [vitalets/angular-xeditable#488]
I would like to import this module in a node environement. It appears there is no direct support for this. Any suggestions?

**Comment by ckosloski** [comment]
Is this what you are looking [for](https://www.npmjs.com/package/angular-xeditable)?

**Comment by ckosloski** [comment]
@cliffordfajardo are you still having an issue?

**Comment by cliffordfajardo** [comment]
@ckosloski - not anymore. You can close this out

**Comment by ckosloski** [comment]
@eugef can you please close this issue.
