### ISSUE TITLE
xeditable directive not replacing text with textbox

### ISSUE THREAD

**Issue by StephenStrickland** [vitalets/angular-xeditable#493]
``` HTML
 <a href="#" editable-text="vm.name">{{ vm.name || "empty" }}</a>
```
I cannot get any xeditable directives to work properly.

Even when using the simplest directive, the original `<a> `tags are not replaced with a `<form>`.

The` <form>` is just added next to the `<a>` tag.

Pre Click:
<img width="47" alt="screenshot 2016-06-29 15 22 54" src="https://cloud.githubusercontent.com/assets/6843062/16465607/9cdad336-3e0d-11e6-91fa-4045a52e09ba.png">

Post Click:
<img width="176" alt="screenshot 2016-06-29 15 22 51" src="https://cloud.githubusercontent.com/assets/6843062/16465608/9ce395d4-3e0d-11e6-8783-0b7b72a61cd5.png">

Post Click Code:
``` HTML
<a class="ng-scope ng-binding editable editable-click editable-hide" editable-text="vm.name" href="#">asdf</a>
<form class="form-inline editable-wrap editable-text ng-pristine ng-valid ng-scope" role="form" editable-form="$form" blur="cancel">
<div class="editable-controls form-group" ng-class="{'has-error': $error}">
<input class="editable-has-buttons editable-input form-control ng-pristine ng-valid ng-not-empty ng-touched" type="text" ng-model="$data">
<span class="editable-buttons">
<button class="btn btn-primary" type="submit">
<button class="btn btn-default" ng-click="$form.$cancel()" type="button">
</span>
<div class="editable-error help-block ng-binding ng-hide" ng-bind="$error" ng-show="$error"></div>
</div>
</form>
````

xeditable version
```javascript
/*!
angular-xeditable - 0.2.0
Edit-in-place for angular.js
Build date: 2016-06-28 
*/
```

Any help is appreciated.

**Comment by StephenStrickland** [comment]
I found a temporary fix by adding: ` ng-hide="$form.$visible"` to every tag that is using the `editable` directive. But surely this would be included in the directive.

**Comment by edmedo** [comment]
Are you definitely including `xeditable.css` in your source?

**Comment by StephenStrickland** [comment]
That would be the issue. My path for `xeditable.css` was mispelled.
