### ISSUE TITLE
Is there any way to dynamically see whether radio values have been changed or not? 

### ISSUE THREAD

**Issue by shanahanbaptista** [vitalets/angular-xeditable#494]
I have some content that I wish to show and hide based on the conditions changed in the radiolist. Is there any way I can see the value. (The same way ng-model works)

**Comment by ckosloski** [comment]
Couldn't you use `e-ng-changed` to set some value that could be referenced by a `ng-hide` or `ng-show`?

**Comment by ckosloski** [comment]
@shanahanbaptista are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
