### ISSUE TITLE
Styling Checkboxes

### ISSUE THREAD

**Issue by EvanBurbidge** [vitalets/angular-xeditable#495]
Hey, one thing i've noticed is that the HTML for checkboxes is something like
```
<label>
   <input type='checkbox'>
</label>
```
But with this it makes it impossible to style the checkbox using custom CSS on an application. Is there anyway of updating the HTML to be something more like...
```
<label>
   <input type='checkbox'>
  <span class='editable-styler-span'></span>
</label>
```
This way the checkbox of browsers could be hidden + the span could be styled in order to give the checkbox the look / feel of the applications UI.

**Comment by EvanBurbidge** [comment]
`angular.module('xeditable').directive('editableCheckbox', ['editableDirectiveFactory',
  function(editableDirectiveFactory) {
    return editableDirectiveFactory({
      directiveName: 'editableCheckbox',
      inputTpl: '<input type="checkbox">',
      render: function() {
        this.parent.render.call(this);
        if(this.attrs.eTitle) {
          this.inputEl.wrap('<label></label>');
          this.inputEl.parent().append("<span></span>");
          this.inputEl.parent().append(this.attrs.eTitle);
        }
      },
      autosubmit: function() {
        var self = this;
        self.inputEl.bind('change', function() {
          setTimeout(function() {
            self.scope.$apply(function() {
              self.scope.$form.$submit();
            });
          }, 500);
        });
      }
    });
}]);`

Changing the part of the code to this will allow the span to be present in the HTML for styling.

**Comment by ckosloski** [comment]
Is this what you are looking for?
```html
<label>
  <input type="checkbox" class="editable-has-buttons editable-input ng-pristine ng-valid ng-not-empty ng-touched" title="Remember?" ng-model="$parent.$data">
  <span>Remember?</span>
</label>
```
