### ISSUE TITLE
No update when edit-disabled changed

### ISSUE THREAD

**Issue by mgohin** [vitalets/angular-xeditable#496]
``` javascript
$scope.readOnly = true;
...
callToAsyncResource(function(){
   $scope.readOnly = false;
});
```

``` html
<div edit-disabled="readOnly" editable-text="myproperty">myproperty</div>
```

My div is still editable :/
Angular digest is called because in my `callToAsyncResource` function I'm assigning scope properties and UI is updated.

**Comment by ckosloski** [comment]
You forgot the curly braces.  It should be:

`<div edit-disabled="{{readOnly}}" editable-text="myproperty">myproperty</div>`

**Comment by mgohin** [comment]
I just took a look at the directive, the attribute `editDisabled` isn't watched, so it'll not be updated :/
Any change to make it updatable ?

**Comment by chasingtheflow** [comment]
I'm having a similar issue, I think. Except that for mine the editable vs read-only states seem to be flipped from what I expected / understood from the documentation. Unless I misunderstood. But when I have `edit-disabled="false"` the field _is not editable_ but when I have `edit-disabled="true"` the field _is editable_. I thought that it should be the reverse.

**Comment by ckosloski** [comment]
Yes, if `edit-disabled="true"`, it should disable editing.  Can you provide a plunker/jsfiddle showing your issue?

**Comment by chasingtheflow** [comment]
So when I recreate it with just the bare-bones stuff required it behaves correctly in plunkr (http://plnkr.co/edit/uHnPJ0onnsKW90kzynLK?p=preview), but doing the same thing in my (much larger) app it's doing the opposite. I'm trying to figure out what's wrong, though it's likely on my end...

**Comment by chasingtheflow** [comment]
Source for this particular piece of the template:
<img width="777" alt="bva_tool___unlinked" src="https://cloud.githubusercontent.com/assets/718368/17949063/b6a7066e-6a21-11e6-8fa4-8a83fbd4a0bd.png">

Rendered output:
![servicenow](https://cloud.githubusercontent.com/assets/718368/17949135/04d582d4-6a22-11e6-97b1-b913152c5c63.png)

Not sure if this helps at all, but if you can spot something I'm doing wrong here it would be appreciated.

**Comment by ckosloski** [comment]
As discussed above, there is no watcher on edit-disabled, so if the value changes, it is not reflected in the control.

**Comment by chasingtheflow** [comment]
Yeah, but in this case I did not change the value of the published flag –– it was the same since load time. Also, the reverse is also happening, if I navigate to a model which is not published then I see the opposite:

![servicenow](https://cloud.githubusercontent.com/assets/718368/17949285/b0dd890a-6a22-11e6-965f-2b03178fc0b6.png)

**Comment by chasingtheflow** [comment]
So think I figured this out in the end and it is a result of edit-disabled not being watched. I was thinking that this was set from load time but in fact the value is being updated slightly after the initial load, so I'm consistently getting the behavior from the previously active item. Which makes sense.

I'll resolve by using an approach similar to the `ng-if` approach suggested here https://github.com/vitalets/angular-xeditable/issues/337#issuecomment-123011314

**Comment by fhurta** [comment]
Any plans to make `edit-disabled` watched in the near future? It would be really helpful

**Comment by ckosloski** [comment]
Pull requests are welcome :)

**Comment by ckosloski** [comment]
#282 was created to fix this, but it looks like it was never merged to master.

**Comment by ckosloski** [comment]
I have verified that `edit-disabled` is now watched with the latest build.
@eugef please close.
