### ISSUE TITLE
xeditable for SharePoint

### ISSUE THREAD

**Issue by rzempo** [vitalets/angular-xeditable#497]
Hello, 

I am a SharePoint developer. I've used angularJS for all of my SharePoint projects for the past 3 years. I love it. Looking at inline edit options, angular-xeditable is by far the best solution out there :)

However, SharePoint doesn't allow <form> tags inside custom html :(

Do you guys have any work-around for using xeditable without the <form> tag?

Thanks for your help!
-Ruben

**Comment by ckosloski** [comment]
There isn't any workaround that I know of.  What specifically are you looking for that will work with SharePoint?

**Comment by ehsan-hakimi** [comment]
Hi Ruben,
I am a SharePoint developer as well and use xeditable in my SP hosted app. You can use Angular and xeditable in SP hosted or provider hosted app in SharePoint. Please have a look at this URL
https://www.pluralsight.com/courses/building-sharepoint-apps-spa-angularjs
I have used xeditable within SP and you can see a sample in issue number #540 
Best regards,

**Comment by ckosloski** [comment]
@eugef I think this issue can be closed.
