### ISSUE TITLE
$compile:ctreq Missing Required Controller

### ISSUE THREAD

**Issue by Sampath-Lokuge** [vitalets/angular-xeditable#499]
Hi,

Below mentioned error gives only with the `editable-bsdate` attribute when I used the ` e-ng-change="vm.setVendorOrdered($data)"`.Can you tell me why ?

```
 <td>
   <span editable-bsdate="vendor.dateOrdered" e-datepicker-popup="MM-dd-yyyy" e-ng-click="vm.open($event,'$data')" e-is-open="vm.opened.$data"
    e-name="dateOrdered" e-form="vendorInformationForm" e-readonly="true"
    e-ng-change="vm.setVendorOrdered($data)" e-required>
     {{ vendor.dateOrdered | date:'MM-dd-yyyy' }}
   </span>
 </td>
```

Please click the Error image to see the full details :

![Run Time Error](http://i.imgur.com/krmhQfo.png)

**Comment by Sampath-Lokuge** [comment]
Hi @ckosloski can I have any support for this ? Thanks.

**Comment by ckosloski** [comment]
Are you using the latest version of xeditable?  If so, you need to use `$parent.$data` to access the data instead of `$data`

**Comment by Sampath-Lokuge** [comment]
@ckosloski Nope,I'm using this.Then what should I do ? Thanks.

```
angular-xeditable - 0.1.12
Edit-in-place for angular.js
Build date: 2016-04-14  
```

**Comment by ckosloski** [comment]
Per the change log, the on-change support for bsdate was added in 0.2.0.  Try upgrading to the latest version of xeditable.

**Comment by Sampath-Lokuge** [comment]
@ckosloski Oh..Thanks a lot for the info.If I'll update it to latest version then  will I have lot of braking changes on my app ? If so could you tell me where are the places ? Thanks.

**Comment by ckosloski** [comment]
I don't know of any breaking changes.

**Comment by Sampath-Lokuge** [comment]
OK sure @ckosloski  I'll do that and will let you know if I'll need any help further. Thanks a lot.

**Comment by Sampath-Lokuge** [comment]
Thanks a lot @ckosloski It is working fine  :smile:
