### ISSUE TITLE
$data does not include empty strings in onbeforesave for form

### ISSUE THREAD

**Issue by semaja2** [vitalets/angular-xeditable#501]
Hi Guys,

I have an issue where when a text field is changed to an empty string, $data does not contain the variable, this then means the old data in the text field does not get changed

Is there a way to access all the values on the form?

**Comment by ckosloski** [comment]
Do you have a JSFiddle showing this issue?  I just tried this out on an existing [fiddle](http://jsfiddle.net/ckosloski/g807jm1j/3/) I had and it seems to work.  Delete the text in the first name text field, change the second name text field to "awesome" and save.  The first name field turns into "empty"

**Comment by dunkersa** [comment]
I seem to be having a similar issue.  If $data is null when the form becomes editable, $data never changes no matter what I input.  If there's already a value there, though, $data updates just fine.

**Comment by ckosloski** [comment]
Do you have a JSFiddle or Plunkr showing this issue?  I did some testing locally, setting the starting value of a field to null and when I click save, the onbeforesave validation still displays the correct error.

**Comment by semaja2** [comment]
Sorry I don't have any example code at the moment, but basically if the field has a value say "example" and I change it to "" when I use onbeforesave in a form, the $data does not include the field.

I assume this is due to the field being blank?

**Comment by ckosloski** [comment]
What do you mean by "$data does not include the field".  Is there some specific test you are trying to do in your onbeforesave that is not working?

**Comment by semaja2** [comment]
Apologies I created a quick fiddler and was unable to reproduce my issue, I suspect this may be a issue in my code
