### ISSUE TITLE
How to apply style to the inner text of the date time control

### ISSUE THREAD

**Issue by Sampath-Lokuge** [vitalets/angular-xeditable#503]
Hi,

Can you tell me how to apply style to the inner text of the date time control ? I have tried like below.But it's not working.

```
<span editable-bsdate="user.date" e-datepicker-popup="MM-dd-yyyy" e-style="color: green; background-color: green" e-ng-click="opened = !opened" e-is-open="opened" onbeforesave="vm.checkValidity($data)" e-name="date" e-form="noteInformationForm" e-readonly="true" e-required>
   {{ user.date | date:'MM-dd-yyyy' }}
</span>
```

Here is my Fiddler : **[Fiddler](http://jsfiddle.net/sampath_lokuge/NfPcH/16031/)**

**Comment by Sampath-Lokuge** [comment]
Hi @ckosloski Can I have any support for this ? Thanks.

**Comment by ckosloski** [comment]
Are you trying to style the text in the textbox in your fiddle?

**Comment by Sampath-Lokuge** [comment]
Exactly @ckosloski It is date picker control.I need to give a colour to that date text.

**Comment by ckosloski** [comment]
Currently the bsdate control doesn't support the e-style attribute.
Does the color change per row?  If not, you could setup a css class to style the text.

**Comment by Sampath-Lokuge** [comment]
Actually @ckosloski  I need to give a colour according to the condition as shown below.Could you tell me how to do that ? 

```
 <span ng-if="note.isEmailSent" editable-bsdate="note.date" e-datepicker-popup="MM-dd-yyyy" e-style="color: green; background-color: green"
 e-ng-click="opened = !opened" e-is-open="opened" onbeforesave="vm.checkValidity($data)"
 e-name="date" e-form="noteInformationForm" e-readonly="true" e-required>
       {{ note.date | date:'MM-dd-yyyy' }}
</span>
```

**Comment by ckosloski** [comment]
It's going to require a change to editableBsdate directive to support e-style.

**Comment by Sampath-Lokuge** [comment]
Oh.. OK @ckosloski Then you can mark this issue as an enhancement no ? Hope you'll do that and will let us know.Thanks.

**Comment by Sampath-Lokuge** [comment]
Thanks a lot @ckosloski  Have you released new version or what ?

**Comment by ckosloski** [comment]
I added a fix for your issue.  There has not been a new release.  You would have to build it yourself locally in order to get the latest changes.

**Comment by Sampath-Lokuge** [comment]
Oh..   :open_mouth: Then can you please tell me how to do that or may be a simple reference link about the way how to do that @ckosloski  ?

**Comment by ckosloski** [comment]
- You need to clone the repository locally.
- install npm if you don't have it
- install grunt globally, if you haven't already: `npm install -g grunt-cli`
- `npm install` in the project
- `grunt jade` - to create the test files
- `grunt build` - to build the project files

**Comment by Sampath-Lokuge** [comment]
Thanks  a lot @ckosloski    :thumbsup:  I really appreciate it.I'll try it and will let you know if I'll have any issue.
