### ISSUE TITLE
e-ng-disabled="true" and e-ng-required="true" doesn't work on Date control 

### ISSUE THREAD

**Issue by codeshri** [vitalets/angular-xeditable#505]
Cannot disable Date control using ng-disabled  looks like it is applying disable on a div instead of input  elements.  Following is how i am using it

<span e-ng-disabled="row.IsComplete=='Y'" e-ng-required="att.IsReq=='R'" e-is-open="opened[row.RowId]" e-ng-click="open($event,row.RowId)" e-datepicker-popup="dd/MMMM/yyyy" e-form="tableform" e-ng-change="ontextChange(row,att,$data)">
    {{ att.Value | date:"dd/MM/yyyy"}}
</span>

Also ng-required doesn't work on date.

Thanks!
Shri

**Comment by ckosloski** [comment]
Try `e-dateDisabled` or `e-readonly`.
You could try using `onbeforesave` to check for required fields before submitting.

**Comment by ckosloski** [comment]
@codeshri are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.

**Comment by codeshri** [comment]
Issue is fixed
