### ISSUE TITLE
Modify $data in onbeforesave function

### ISSUE THREAD

**Issue by semaja2** [vitalets/angular-xeditable#506]
Hi Guys,

I need to make changes to the data the user enters in a text field before it is processed, is it possible to alter the $data structure on a field before the onbeforesave function is run for the form?

**Comment by ckosloski** [comment]
Did you try using a blur/change event to change the data?

**Comment by ckosloski** [comment]
@semaja2 are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
