### ISSUE TITLE
Chrome iPhone (eg:6) e-minlength validation not working

### ISSUE THREAD

**Issue by momoadeli** [vitalets/angular-xeditable#508]
(this code segment works for web chrome and android chrome but not on the iPhone (eg 6). I am using xeditable v0.2 and AJS 1.5.8.)

In iPhone the 'normal' HTML validation does not kick off for e-minlength

I have an input field I need to restrict min/max length to 3/20 characters.  I have used e-minlength and e-maxlength as such:

> ```
>           <a  
>                 href='#'
>                 editable-text="displayName" 
>                 e-name="e_DisplayName"
>                 onbeforesave="checkDisplayName($data)"
>                 e-type="text"
>                 e-required
>                 e-placeholder="display name"
>                 e-minlength="{{::cf.CONSTANTS.USER_PROFILE_SETTINGS.MIN_DISPLAY_NAME_LENGTH}}"
>                 e-maxlength="{{::cf.CONSTANTS.USER_PROFILE_SETTINGS.MAX_DISPLAY_NAME_LENGTH}}">
>                 {{displayName || 'empty' }}
>             </a>
> ```

Of course onbeforesave="checkDisplayName($data)" is:

> ```
>           $scope.checkDisplayName = function(data) {
>                 if (data === UserService.userProfile.id)
>                     return "hasn't changed";                
>             };      
> ```

--and in iPhone data is passed as 'undefined' which not unexpected if validation is broken.  

I've currently patched this with a simple extra check:

> ```
>           $scope.checkDisplayName = function(data) {
>                 if (data === UserService.userProfile.id)
>                     return "hasn't changed";    
>                 else if (!cf.Utilities.isDefined(data)) {
>                     return "invalid input";
>                 }               
>             };          
> ```

Please advise.

Many thanks!
Mo

**Comment by ckosloski** [comment]
It's possible the ios version of chrome doesn't support that attribute.  Can you try this [test](http://www.wufoo.com/html5/attributes/18-minlength.html) page on your phone and see if it works?

**Comment by ckosloski** [comment]
@momoadeli are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response
