### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 2947721120** [vitalets/angular-xeditable#510]
![image](https://cloud.githubusercontent.com/assets/13098589/17569243/f354665e-5f79-11e6-92b4-ac1e8b409dc1.png)

**Comment by ckosloski** [comment]
What is wrong with Search?

It appears that browsers have pulled support of the datetime html5 input field and will have to be removed from the project.

**Comment by 2947721120** [comment]
1 did not see the effect of search
![image](https://cloud.githubusercontent.com/assets/13098589/17574414/a63ecd36-5f93-11e6-88fd-dac12ef3cf25.png)

2 date and time can enter additional text
![image](https://cloud.githubusercontent.com/assets/13098589/17574425/b0f76c10-5f93-11e6-8293-31e34a8cfbc7.png)

**Comment by 2947721120** [comment]
https://2947721120.github.io/angular-xeditable/
The url has been translated to Chinese Simplified (zh_cn)
And the way that you say, if there is anything I need to be translated into zh_cn
You can give me!...

**Comment by ckosloski** [comment]
1.  What effect are you expecting from the search field?

2.  The datetime field is no longer supported by current browsers so it's not rendering correctly.  Support for HTML5 datetime field needs to be removed from angular-xeditable.

**Comment by ckosloski** [comment]
If you are referring to the "x" button to clear the search term in the search field, that does not display due to bootstrap [styling](https://github.com/twbs/bootstrap/issues/5624).
