### ISSUE TITLE
identify submit button in $data

### ISSUE THREAD

**Issue by frontendplace** [vitalets/angular-xeditable#512]
I want to be able to submit the editable form with two different submit buttons. And want to identify the button that submitted the form.

If I submit the xeditable form with a submit button I don't see the id of the button I used for submitting the form. In normal forms this is the case.

or can I add values or hidden inputs to $data on before submit?

**Comment by ckosloski** [comment]
You could try adding a `ng-click` to your submit button that sets a scope value that then can be used by your submit function.

**Comment by frontendplace** [comment]
Thanx I did that now. But thought It would be better to mimic the same input submits as a normal form submit and register the name of the submit button.
