### ISSUE TITLE
Can you add conditional fields?

### ISSUE THREAD

**Issue by kas84** [vitalets/angular-xeditable#517]
I was wondering if you could add conditional fields like... in a radio-list if "option 2" is selected, you need to provide Passport ID.

If this was just plain angular I would add a ng-if="model.value==''option_2'" and that would be it. How can I do things like this with angular-xeditable?

**Comment by ckosloski** [comment]
You probably could do this with a flag that gets flipped by an ng-click on the radio button and the ng-if on the second field to look for that flag.

**Comment by ckosloski** [comment]
@kas84 are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response
