### ISSUE TITLE
editable-textarea w/o buttons

### ISSUE THREAD

**Issue by yshinjp** [vitalets/angular-xeditable#518]
Hi,

Like as following code,
div editable-textarea="..." buttons="no">{{ ... }} /div

Edited text was not stored into binded model.
without buttons="no", works fine.

Is that a bug ?

**Comment by ckosloski** [comment]
The code snippet above seems ok.  Can you provide a jsfiddle or plunkr showing your issue?

**Comment by ckosloski** [comment]
@yshinjp are you still having an issue?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response
