### ISSUE TITLE
popover-wrapper a styles

### ISSUE THREAD

**Issue by sudheerDev** [vitalets/angular-xeditable#522]
Is there any particular reason for having this style applied for all child elements in popover-wrapper? 
```
.popover-wrapper a {
    display: inline !important;
}
```
I have a custom template with `a` elements and maintaining styles for these because of added inline styles to override becomes a concern.

Can we just have 

```
.popover-wrapper > a {
    display: inline !important;
}
```
 instead?

**Comment by ckosloski** [comment]
There was no specific reason why the css was setup like that.  I can add a fix for that in my next pull request.

**Comment by sudheerDev** [comment]
@ckosloski that would be great thanks.

**Comment by Moghul** [comment]
Is there a reason in the first place why that has to be !important? I understand the need for it to be inline for functionality reasons, but right now I'm having a hell of a time juggling display values because of this.

I'd appreciate it if you removed the !important and added a note in the documentation that this needs to be inline.

**Comment by ckosloski** [comment]
You can always overwrite the style in your style sheet.
PR's are welcome :)

**Comment by Moghul** [comment]
Perhaps I am missing something. In order for me to override or overwrite this locally don't I either have to: 
a) Edit the css file from your library locally
b) Use more !important tags in my own css files

Is there a third way?

**Comment by ckosloski** [comment]
Would if work if you defined
```
.popover-wrapper > a {
    display: inline;
}
```

In your own css file that is included after the xeditable file so that it will override it?

**Comment by Moghul** [comment]
![selection_010](https://user-images.githubusercontent.com/17046245/49522831-d36b0300-f8a8-11e8-86c5-b1b090ee2d30.png)
