### ISSUE TITLE
is jquery an extra dependency?

### ISSUE THREAD

**Issue by spanevin** [vitalets/angular-xeditable#524]
https://vitalets.github.io/angular-xeditable/ says that it does not depend on anything except angularjs itself. But...
https://github.com/vitalets/angular-xeditable/blob/master/package.json

22   "dependencies": { 
23     "angular": "~1.x", 
24     "bootstrap": "^3.1.1", 
25     "jquery": "^1.11.1", 
26     "moment": "^2.5.0" 
27   }, 

Do we really need all this stuff? Why it doesn't correspond to main site description? It would be great if jquery and other stuff is removed or is made optional.

**Comment by ckosloski** [comment]
jQuery and Moment are not needed for using angular-xeditable.  If you look at this [fiddle](http://jsfiddle.net/NfPcH/25/), it does not have either of those items.

I think those items are needed for building the documentation.

**Comment by spanevin** [comment]
Shouldn't it be in devDependencies section in this case? I thought that dependencies is for runtime deps.

Sorry if it's a stupid question but I'm a very new angular + npm developer. My worries are that if I compile it using webpack, extra code could get into compiled scripts.

**Comment by ckosloski** [comment]
Sorry, I haven't built a site using npm and angular-xeditable.  Maybe just go ahead and compile and see what happens.  If you run into issues, post what you are doing and the error you got and maybe someone else will be able to help you.

**Comment by spanevin** [comment]
I removed angular and moment from dependencies, killed these packages and did recompilation. Result scripts are the same as before. So, I don't see any reason of pulling these packages along with angular-xeditable package. Please remove these dependencies from package.json, dependencies section. I believe that bootstrap can be removed too.
Actually I see optionalDependencies section in the package.json, shouldn't it be declared here? According to project home page, the only required dependency is angular, and there are some optional, like angular-ui bootstrap and ui-select. Nothing is said about jquery and moment at all.

**Comment by spanevin** [comment]
Just read description of optionalDependencies secion in npm documentation https://docs.npmjs.com/files/package.json
It can't be used in the way I thought. So there should be another way to specify optional runtime dependencies, or you can just describe it in readme/documentation.
