### ISSUE TITLE
angular xeditable date do not shows his value entering edit mode

### ISSUE THREAD

**Issue by jjgonver** [vitalets/angular-xeditable#526]
I'm using angular xeditable in my form and I have problems with a date field. This is my HTML code:

```
<span
      e-ng-disabled="!incidence.finish"
      editable-bsdate="incidence.finishDate"
      data-e-name="incidencia.finishDate"
      e-is-open="opened.$data"
      e-ng-click="open($event,'$data')"
      e-datepicker-popup="dd/MM/yyyy"
      e-readonly="true"
      e-starting-day=1
      e-show-calendar-button="false"
      e-current-text="Hoy"
      e-clear-text="Limpiar"
      e-close-text="Hecho"
      e-date-format
      >
    {{ (incidence.finishDate | date:"dd/MM/yyyy") }}
</span>
```

In the form view mode the date field shows his value well, but when entering in edit mode the date field shows an empty value. After I select a date with date picker then the date field show a date value. What am I doing wrong? 
I'm using "angular-xeditable": "^0.2.0"
Thanks

**Comment by ckosloski** [comment]
Not quite sure I understand the issue.
I take it you are using an editable form and when you click to edit, the date field is not showing the date in the textbox?
What version of angular-ui-bootstrap are you using?
What are you trying to do with `e-date-format`?

**Comment by jjgonver** [comment]
1. Yes. that is.
2. "angular-ui-bootstrap-bower": "1.3.3"
3. I'm not sure. I make a copy/paste from an example.

**Comment by ckosloski** [comment]
Are there any errors in your console?
Can you provide a link to a plunkr or jsfiddle showing the issue?

**Comment by ckosloski** [comment]
Are you passing a JS Date object in `incidence.finishDate`?

**Comment by jjgonver** [comment]
No errors in console. 
In the controller I load in $scope.incidence all the fields from incidence database and finishDate is a Date field.
I try to make a plunker.

**Comment by jjgonver** [comment]
Do you have a base plunker with dependencies to put my code?
Thanks

**Comment by ckosloski** [comment]
The [documentation](http://vitalets.github.io/angular-xeditable/) has some links to some JSFiddle's you could start with.

**Comment by ckosloski** [comment]
Can you provide the code that sets the date value of  `incidence.finishDate`?

**Comment by matthew-b-payne** [comment]
I also have a similar issue.   If a hard code the date it works fine. 

$scope.user = {
        dob: new Date(1984, 4, 15)
    };
e.g.

However, if the user is loaded.
$scope.loadUser = function () {
        $scope.user = UserService.get({id: id});
    };
The date in the text box is empty.  The calendar popup is set to the correct date though.

**Comment by ckosloski** [comment]
The date for the popup needs to be a JS date so you probably need to do something like:
`$scope.user.dob = new Date($scope.user.dob );`

**Comment by ckosloski** [comment]
@jjgonver are you still having an issue?

**Comment by Irikos** [comment]
Struggled a bit with this problem as well. It turns out, as mentioned earlier, that you need to conver the data to JS Date.

          campaign.dateStart = new Date(campaign.dateStart);

did it for me.

**Comment by ckosloski** [comment]
@eugef This issue is answered and can be closed.

**Comment by jjgonver** [comment]
Sorry for the late reply. Worked for me!
