### ISSUE TITLE
How do I add my own css class or style without extending .editable and/or .editable-click ?

### ISSUE THREAD

**Issue by jonathankraemer** [vitalets/angular-xeditable#527]
I need to show the text of the editable text in red in some cases, which is not when the value in the model is null. There seems to be no way to add my own class to the final element.

**Comment by ckosloski** [comment]
Are you trying to display the text red in the input field or when it's displayed as a link?

**Comment by jonathankraemer** [comment]
Sorry, I forgot to mention: I am trying to display the link in red, but
like I said: I don't want to change the editable-link css altogether
because it's supposed to be in red only in some cases within a page.

--
Jonathan Kraemer

**Comment by ckosloski** [comment]
Did you try using ng-class?

**Comment by jonathankraemer** [comment]
Hey, I am so sorry I only now realized class="" and ng-class="" were not
working because my code wasn't even running. Bug in our code.

--
Jonathan Kraemer
