### ISSUE TITLE
Local Model is updated when error occurs with onaftersave

### ISSUE THREAD

**Issue by westerncj** [vitalets/angular-xeditable#529]
We wanted to return server side errors to the client so we used `onaftersave` instead of `onbeforesave`. It works as expected for validation except that the local model is updated when you click the Cancel button. Is there a way to not update the local model if there is an error with `onaftersave`?

**Comment by ckosloski** [comment]
I think you would have to save the before values in a temp scope variable and if you click cancel after onaftersave was run, then reset the value.

**Comment by westerncj** [comment]
OK. That's kind of what I ended up doing. Thanks for the quick response.

**Comment by ckosloski** [comment]
OK, should this issue be closed then?

**Comment by westerncj** [comment]
Yes you can close. Thanks!

**Comment by ckosloski** [comment]
You need to close it.
