### ISSUE TITLE
editable-select : how add an empty value choice with e-ng-options ?

### ISSUE THREAD

**Issue by JeremieLAN** [vitalets/angular-xeditable#531]
Hi,

i would like to know how to add easily an empty value choice in a select using e-ng-options.

Thank you for your help.

Jérémie

**Comment by ckosloski** [comment]
Set `e-placeholder="Your Blank Value Text"`.

**Comment by JeremieLAN** [comment]
terrific !
Thank you !

**Comment by ckosloski** [comment]
Your welcome.  If that fixes your issue, please close it.
