### ISSUE TITLE
Typeahead input formatter function firing before onshow

### ISSUE THREAD

**Issue by westerncj** [vitalets/angular-xeditable#533]
I'm trying to use the typeahead editable but I'm running into some problems when using `onshow="vm.loadList()"` and `e-typeahead-input-formatter="vm.formatField($model)"`. The `e-typeahead-input-formatter` function is called before the `onshow` function so my list is blank thus my input is blank when it becomes editable. Does `onshow` not complete before it formats the input?

**Comment by ckosloski** [comment]
Is the onshow list different that the list you are passing into e-uib-typeahead?

**Comment by westerncj** [comment]
No it's the same list. I was loading the list initially when the page loaded, but I'd rather load the list `onshow` because I think it makes more since.

**Comment by westerncj** [comment]
I can close this now if you'd like. I found a workaround by with my `vm.formatField()` function by evaluating if the list is loaded yet. If the list isn't loaded then I'm setting it equal to the local model value in the dataset. Thanks for your help and let me know.

**Comment by ckosloski** [comment]
Yes, if you figured out a solution, go ahead and close the issue.
