### ISSUE TITLE
Removing Underline From the Link

### ISSUE THREAD

**Issue by artforlife** [vitalets/angular-xeditable#536]
Is there an efficient way to get rid of the underline? I tried using `ng-style=" { border-bottom: none; }"` which didnt work. In turn, I am wondering whether x-editable interferes with other Angular directives?

**Comment by ckosloski** [comment]
Where are you placing the ng-style tag?  In theory, that is the correct css to use.
I don't know if it interferes with any or not, which ones are you having issues with?

**Comment by artforlife** [comment]
I figured this out. The issue had to do with quotation marks for the ng-style directive. It worked as expected and rid the link off the bottom border.
