### ISSUE TITLE
Question Template: Add Question Template structure issue.

### ISSUE THREAD

**Issue by NalinSajwan** [vitalets/angular-xeditable#541]
On add Question Template, default template structure issue with 1 category does not gets generated.

**Comment by ckosloski** [comment]
Hi @NalinSajwan can you provide a little more info about your issue?  I'm not following.  Are you referring to live templates listed at the bottom of the readme?

**Comment by NalinSajwan** [comment]
Sorry this was a mistake this got mixed up.
