### ISSUE TITLE
datepicker bsdate broken styles

### ISSUE THREAD

**Issue by afgonzal** [vitalets/angular-xeditable#543]
The example for Controls/date (bsdate) that uses ui-bootstrap  datepicker doesn´t look good.

the popup style looks huge, goes outside it´s borders etc (check attached screenshot)

just check https://vitalets.github.io/angular-xeditable/#bsdate
or this demo http://plnkr.co/edit/12aAwWyDEulaqH4ijsI5?p=preview
(there are 2 datepickers, one regular, the other inside a xeditable

thanks

![broken datepicker](https://cloud.githubusercontent.com/assets/12254371/18719155/8c23e8da-7ffc-11e6-8aa3-384fdbb8dce1.png)

**Comment by ckosloski** [comment]
Yes, I am aware of the issue and it's already been fixed and merged, just not released yet.

**Comment by ckosloski** [comment]
This is fixed in the latest release
