### ISSUE TITLE
no buttons => cancel on blur

### ISSUE THREAD

**Issue by wetternest** [vitalets/angular-xeditable#545]
https://github.com/vitalets/angular-xeditable/blob/master/src/js/editable-element/controller.js#L271

why am i not allowed to set `buttons='no'` AND `blurElem='submit'` via config? how are user supposed to submit then? 
(i know that i can override this option for every editable with the attribute `blur="submit"`, but this option seems not very practical....)

**Comment by ckosloski** [comment]
Not sure what issue you are having, but you can set both buttons and blurElem in the config options, see the [documentation](http://vitalets.github.io/angular-xeditable/#ref-options).

**Comment by wetternest** [comment]
setting buttons = 'no' deactivates `editableOptions.blurElem`
`self.editorEl.attr('blur', self.attrs.blur || (self.buttons === 'no' ? 'cancel' : editableOptions.blurElem));`

see code at https://github.com/vitalets/angular-xeditable/blob/master/src/js/editable-element/controller.js#L283

**Comment by ckosloski** [comment]
What do you think that line of code should be in order for both to work together?

**Comment by ckosloski** [comment]
@wetternest this should be fixed now, can you retest.

**Comment by wetternest** [comment]
thank you for your fix! i will test it as soon as possible, unfortunately i don’t have much time at the moment =(

**Comment by ckosloski** [comment]
@eugef please close, this issue is fixed.
