### ISSUE TITLE
editableOptions.activate = 'select' should fallback on focus when element has no select

### ISSUE THREAD

**Issue by Carnid** [vitalets/angular-xeditable#547]
https://github.com/vitalets/angular-xeditable/blob/master/src/js/editable-element/controller.js#L419

If element has no `select()` function, it should fall back to `focus()`. A common example is `editable-select`, which doesn't have a `select()` method and is no longer focused on activate.

Demo: http://jsfiddle.net/NfPcH/16911/

**Comment by ckosloski** [comment]
Please open a pull request.

**Comment by Carnid** [comment]
Here you go, not sure how to link issues with pull requests...
https://github.com/vitalets/angular-xeditable/pull/548

**Comment by ckosloski** [comment]
What I do is usually just mention the issue that the pull request is for.
