### ISSUE TITLE
uneven typeahead results margin

### ISSUE THREAD

**Issue by pratheekhegde** [vitalets/angular-xeditable#550]
Typeahead results have lots of margin in the top and bottom. It looks ugly.
Playing with `margin-top` and `margin-bottom`  of `uib-typeahead-match` class fixes it.

You can see it in the demo page .
<img width="379" alt="screen shot 2016-10-06 at 1 18 19 am" src="https://cloud.githubusercontent.com/assets/11031124/19128938/fdf1f6ac-8b62-11e6-8dc1-76d049e84ca1.png">

I don't know if it is something to do with my markup or problem with x-editable.

Here is my markup
```html
<span e-placeholder="Type your city" 
    data-e-form="editableForm" 
    editable-text="vm.profile.currentCity" 
    e-uib-typeahead="address for address in vm.getLocation($viewValue) | limitTo:8" 
    e-typeahead-loading="vm.loadingLocations" 
    e-typeahead-no-results="vm.noResults">
    {{ vm.profile.currentCity || 'empty' }}
</span>
<i ng-show="vm.loadingLocations" class="glyphicon glyphicon-refresh"></i>
 <div ng-show="vm.noResults">
    <i class="glyphicon glyphicon-remove"></i> No Results Found
 </div>
```

**Comment by ckosloski** [comment]
fixed in pr #544

**Comment by pratheekhegde** [comment]
I'm using the latest, it still seems to be there. 😕

**Comment by BenevidesLecontes** [comment]
@pratheekhegde `white-space: normal;` on editable-wrap, should fix.

**Comment by pratheekhegde** [comment]
@BenevidesLecontes That does fix ! 😃 .
But, I dont see

```javascript
/* fix padding issue on typeahead */
 .editable-text {
     white-space: nowrap;
 }
````
of #544 
in https://github.com/vitalets/angular-xeditable/blob/master/dist/css/xeditable.css

**Comment by ckosloski** [comment]
It's merged, but not yet built.  You would have to download the code and build yourself to get the latest changes.

**Comment by pratheekhegde** [comment]
Yea, I figured that out. Thanks again @ckosloski .

**Comment by ihorskyi** [comment]
Any plans to release this fix soon?
