### ISSUE TITLE
Typeahead formatting, inappropriate height/spacing

### ISSUE THREAD

**Issue by jjreicher** [vitalets/angular-xeditable#554]
It's right there on the demo page. Huge vertical spacing for no clear reason. Anyone know the reason? Or how to fix it? Figure it's possible to supercede the CSS somewhere, but figured I'd check before I go down that rabbit hole.

![image](https://cloud.githubusercontent.com/assets/13351061/19314941/bd49eaae-9050-11e6-947c-4ea8e210867c.png)

**Comment by ckosloski** [comment]
This is currently fixed, just not yet released.

**Comment by jjreicher** [comment]
Oh awesome. Any way to get hands on the fix? Or when is the release?

**Comment by ckosloski** [comment]
You can always download the code and build the files yourself while we wait for a new release.

**Comment by jjreicher** [comment]
thanks!
