### ISSUE TITLE
[Question] editable-ui-select multiple?

### ISSUE THREAD

**Issue by bORm** [vitalets/angular-xeditable#555]
Subj

**Comment by ckosloski** [comment]
Just add `e-multiple` to your `editable-ui-select` tag

**Comment by bORm** [comment]
Oh, thanks

**Comment by Snippo** [comment]
Thanks for the example. I have spend some time trying to get a (key, value) object working in editable-ui-select. The last problem was making it work with e-multiple, as $select didn't work. Seems I should use $item :).
Here is an example for anyone with the same problem:
http://jsfiddle.net/96nz5gy7/

**Comment by usamakhalil86** [comment]
The fiddle is no more working and also the code does not works with latest  * Version: 0.19.5

**Comment by ckosloski** [comment]
See #647
