### ISSUE TITLE
Can Links inside editable-textarea be followed instead of triggering Form Edit?

### ISSUE THREAD

**Issue by Perseverance** [vitalets/angular-xeditable#557]
Hi Team,

I am binding html inside a editable-textarea using ng-bind-html. In some cases there are links in the html that I would like to be followed instead of triggering open of the input field. I read the lib code and saw that you prevent default no matter what. Is there a workaround in this situation?

Example:

``` javascript
task.description = "<a href='http://example.com/'> Link </a>"

<a href="#" buttons="no" editable-textarea="task.description" e-rows="8" blur="submit" onbeforesave="detailsCtrl.updateDescription($data)">
        <div ng-bind-html="task.description"></div>
</a>

```

**Comment by ckosloski** [comment]
Instead of having the item as an editable element, use an editable form.

**Comment by ckosloski** [comment]
@Perseverance did you solve your problem?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response
