### ISSUE TITLE
Xeditable adds empty class/tag and uncheckes  selected checkbox in the checklist, when values are changed the child model.

### ISSUE THREAD

**Issue by jackts** [vitalets/angular-xeditable#558]
xeditable **adds empty class/tag** and **uncheckes**  selected checkbox in the checklist, when values are changed the child model.

I have created fiddle and added steps to recreate the issue.
[http://jsfiddle.net/etsigankov/0twrL66q/](Fiddle)
Steps:
1. click add shape it will create the model
2. click "no appliances" and add 1 or two items(it adds items to the model and displays them)
3. once you change the measurement W or H( it records changes in the **model** correctly) BUT

Issue: if you go to "add appliance" ( it will uncheck everything that was checked before, thus creating multiple entries).

P.S. Everything works with Select/multi select

**Comment by ckosloski** [comment]
Hi, I took a look and found a problem in the app.  I will have to make a pull request to fix it.  Once my pull request is in, you will need to add the following to your `editable-checklist` : 
 `e-checklist-comparator="compareFn"`

Where `comparFn` is:
```javascript
  $scope.compareFn = function(obj1, obj2) {
    return obj1.v === obj2.v;
  };
```

**Comment by jackts** [comment]
@ckosloski . Thank you for fixing the issue.  Should i wait till your changes will be pushed to the new release of the library to see the fix on my end?

**Comment by ckosloski** [comment]
Yes, you won't see the changes until a new build is released, or you pull down the code and build it yourself.
