### ISSUE TITLE
bstime doesn't work with the current version of angular bootstrap

### ISSUE THREAD

**Issue by B3nCr** [vitalets/angular-xeditable#559]
If you look at the latest version of angular-bootstrap the timepicker element is restricted to only work on attributes.

https://github.com/angular-ui/bootstrap/blob/master/src/timepicker/timepicker.js#L576

The bstime directive is trying to use the uib-timepicker as an element.

https://github.com/vitalets/angular-xeditable/blob/master/src/js/directives/bstime.js#L9

It's also still containing a work around for a bug that was fixed long ago.

https://github.com/vitalets/angular-xeditable/blob/master/src/js/directives/bstime.js#L14

I've forked this repo and have changed the template to use the time picker as an attribute. I need to do some more (manual) testing to make sure it works correctly. Would this be a useful pull request and what level of automated/unit testing does it require?

Thanks
Ben

**Comment by ckosloski** [comment]
Yes this would be a useful pull request.  You might need to update the version of angular-bootstrap in the project for the demo pages.

There are one or two tests you will have to change for this.  All of the tests are docs/demos.

**Comment by B3nCr** [comment]
The tests all pass fine with the change to the template. 

Do you want me to add angular-ui-bootstrap as a bower or npm dependency or an dev-dependency? I'm not sure what the best practice is in this scenario. I can see the old versions of ui-bootsrap in the libs folder, do you just want me to update the js in that folder with a copy of the latest version?

**Comment by ckosloski** [comment]
Add the new version to the lib directory.

**Comment by muten84** [comment]
Hi i just discovered the same issue, can you guys suggest me a workaround?

**Comment by B3nCr** [comment]
I'll push my repo and you can pull it and build it and then use the output.

I've not had chance to update the tests and docs yet.

**Comment by B3nCr** [comment]
Actually i think you could just pull the dist folder.

https://github.com/B3nCr/angular-xeditable/tree/bsdate-ui-bootstrap-update/dist

**Comment by muten84** [comment]
i tried it work, i used same trick with my local copy,  to go on. thx

**Comment by B3nCr** [comment]
@ckosloski I don't think it's necessary to add the `<div class="well"></div>` element around the timepicker any more so this code is un-necessary.

https://github.com/B3nCr/angular-xeditable/blob/bsdate-ui-bootstrap-update/src/js/directives/bstime.js#L13

Removing it would change the look of the control slightly. Is that acceptable?

**Comment by ckosloski** [comment]
Yes that is fine, but add it back in the demo page example.  It does look better on the demo page with the well around it.

**Comment by B3nCr** [comment]
I'll just leave it in. It will ensure that the appearance doesn't suddenly change for anyone using the library. 

I've done the changes, updated angular-bootstrap and bootstrap and the tests all pass but I'm not sure how much I should be adding to the PR.

Looking at old PRs for example they don't include the built output but my commits do (because I didn't know what else to do with it other than commit it). My PR looks massive. Also I'm not sure which branch I should be targeting with the PR?

Sorry for being a bit useless at this.

**Comment by ckosloski** [comment]
You just need to include the files you changed (no generated files) and you should create your pull request against master.  Also make sure to squash your commits.

**Comment by B3nCr** [comment]
Okay, so your master has changed since I created my fork. I've create a pull request to pull those changes into my branch...

![image](https://cloud.githubusercontent.com/assets/1277268/19900337/0be2a1b4-a05b-11e6-8ca1-3eae6265fa3c.png)

Presumably I want to rebase that into my master branch? The other options would make a new commit that I don't want when I merge back into your repo.

![image](https://cloud.githubusercontent.com/assets/1277268/19900367/1fd7f976-a05b-11e6-993d-5c3b9b04593e.png)

Then I'll squash my feature branch into my master branch. That'll hopefully give me the opportunity to remove some of the generated stuff I've committed by mistake. Then I'll create a PR to your repo.

**Comment by ckosloski** [comment]
Yes, do a rebase and merge.

**Comment by carterpayne** [comment]
What is the status of this PR? @muten84, i found another work around for the time being using a decorator:

```
angular.module("app").decorator("editableDirectiveFactory", function ($delegate) {
  return function (overwrites) {
    if (overwrites.directiveName === "editableBstime") {
      overwrites.inputTpl = '<div uib-timepicker></div>';
    }
    return $delegate(overwrites);
  }
});
```

kinda sketch but my only option for the time being. hope that helps.

**Comment by B3nCr** [comment]
Sorry, I've been really lax with this, the work is done I just need to sort out my PR. I'll try and get around to it this week.

**Comment by ckosloski** [comment]
@B3nCr did you get a chance to work on a PR?

**Comment by B3nCr** [comment]
@ckosloski  I can't get my head around git's PR system, only including the bits I need and squashing it into a single commit.

I'll have another go now.

**Comment by ckosloski** [comment]
Let me know if you are having any specific issues and I can try to help.

Here's a good link on [squashing](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit).

**Comment by B3nCr** [comment]
Okay, I've managed to get my commits into a single commit, not by squashing but it's done.

I basically had to re-fork the repo again and re-do my change because I was so out of date and trying to merge all the branches again was causing too much aggravation considering this is basically a three line change.

The problem now is that I'm having problems running the tests. The tests in master don't work either so it's not my change that's broken them so what you do with the PR is now up to you.

**Comment by B3nCr** [comment]
Here's the link to the PR to associate it with this issue. https://github.com/vitalets/angular-xeditable/pull/630
