### ISSUE TITLE
Editable Table in uibModal

### ISSUE THREAD

**Issue by andmattia** [vitalets/angular-xeditable#562]
Hi 
try to edit a table inside a Modal create with uibModal. 

my modal has been defined with a form on top to intercept Save/Close event. So I see in console the edit form event is intercepeted and the span inside table will be dcoreted with ngattribute but on click I cann't edit.

**Comment by ckosloski** [comment]
Can you provide a plunker or jsfiddle showing your issue?

**Comment by ckosloski** [comment]
@andmattia did you solve your problem?

**Comment by ckosloski** [comment]
@eugef Please close due to lack of response.
