### ISSUE TITLE
Editable field not placed on position of the text

### ISSUE THREAD

**Issue by eugenevk** [vitalets/angular-xeditable#565]
I am trying to make an editable table (editable row) in my Inspinia template. When I click the edit button on a row, the editable field is placed just after the original field value in the table. I have no idea what I am doing wrong or how to fix it. Can you advise?

![editing topic](https://cloud.githubusercontent.com/assets/19785727/19806267/0a6d6db2-9d1a-11e6-9304-b48c7dcdbaf0.JPG)

I have the following piece of code in my html:

```
<table class="table table-striped">
    <thead>
        <tr>
            <th>Code</th>
            <th>Title</th>
            <th></th>
        </tr>
    </thead>
    <tr ng-repeat="topic in topics | filter: {title: topic_filter} track by $index" aria-hidden="true">
        <td>
            <span editable-text="topic.code" e-name="code" e-form="rowform" e-placeholder="Enter code">{{ topic.code }}</span>
        </td>
        <td>
            <span editable-text="topic.title" e-name="title" e-form="rowform" e-placeholder="Enter title">{{ topic.title }}</span>
        </td>
        <td>
            <form editable-form name="rowform" onbeforesave="saveTopic($data, topic.code)" ng-show="rowform.$visible" class="form-buttons form-inline" shown="inserted == topic">
                <button type="submit" ng-disabled="rowform.$waiting" class="btn btn-primary btn-xs"><i class="fa fa-check" aria-hidden="true"></i></button>
                <button type="button" ng-disabled="rowform.$waiting" class="btn btn-danger btn-xs"><i ng-click="rowform.$cancel()" class="fa fa-ban" aria-hidden="true"></i></button>
            </form>
            <div class="buttons" ng-show="!rowform.$visible">
                <button class="btn btn-primary btn-xs"><i ng-click="rowform.$show()" class="fa fa-pencil" aria-hidden="true"></i></button>  
                <button class="btn btn-danger btn-xs"><i ng-click="remove(topic, $index)" class="fa fa-trash" aria-hidden="true"></i></button>
            </div>  
        </td>
    </tr>
</table>

<button class="btn btn-primary btn-xs" tooltip-placement="top" uib-tooltip="Add record"><i ng-click="create()" class="fa fa-plus" aria-hidden="true"></i></button>

```

**Comment by ckosloski** [comment]
Are you sure you have the xeditable css deployed with your code?

**Comment by eugenevk** [comment]
You were fully right @ckosloski ! I had to include the css in the default.js file of the MEAN boilerplate of Inspinia. Thanks a lot!

**Comment by eugenevk** [comment]
@ckosloski I do have another question. I have three columns in my table (as in the screenshot). When I switch to 'edit' mode, the column widths change. After clicking 'save' they change back to the initial width. Any idea why that can happen?

**Comment by eugenevk** [comment]
@ckosloski And also: is there a way to use the <TAB> key to add new records when in the last editable field of the table?

**Comment by ckosloski** [comment]
I think it might depend on the styling of your textboxes.  If the columns are smaller than the size of the textbox, they would be expanded.
Not sure about your last comment.  Do you mean that on save you want to display another new entry field?

**Comment by eugenevk** [comment]
Ok, I'll test the first.
And yes, I mean save a record when tabbing out of the field and immediately creating a new record with focus on the first field.

**Comment by ckosloski** [comment]
At the end of your save method you just push another item into the array and then set the focus.

```javascript 
$scope.inserted = {
  movie: $scope.movieCharacterModel.selected,
  characterName: null,
  actor: null
};
$scope.movieCharacterModel.characters = [];
$scope.movieCharacterModel.characters.push($scope.inserted);

$timeout( function() {
  $scope.setFocus('characterName');
}, 50);

$scope.setFocus = function (id) {
  angular.element(document.querySelector("#" + id)).focus();
};`

**Comment by eugenevk** [comment]
@ckosloski  Can you maybe also tell how I could automatically delete a row when the user adds a record and immediately cancels it? Now the record stays but with empty fields.

**Comment by ckosloski** [comment]
You would have to have a method that is called on cancel and determine if anything was entered or not.  If not, then "pop" the last item off your array.

**Comment by eugenevk** [comment]
@ckosloski The issue with the jumping column widths is indeed solved by setting the size of <th>. Thanks.
Regarding your last remark, it looks like onbeforesave is not executed after a rowform.$cancel(). Is that correct? If so, how can execute a function on cancel?

**Comment by ckosloski** [comment]
Just change the ng-click of your cancel button to call a function.  Pass in rowform to the function to perform the cancel on the form and do the pop on the array.

**Comment by ckosloski** [comment]
@eugenevk did you solve your problem?

**Comment by ckosloski** [comment]
@eugef I think we can close this issue due to lack of response.
