### ISSUE TITLE
Unable to show single-minute increments (or seconds) on combodate

### ISSUE THREAD

**Issue by rusackas** [vitalets/angular-xeditable#568]
For some reason, when I set `e-minute-step="1"` on an editable-combodate field/form, the time doesn't show up as one minute increments as I expected, but rather like this:

![screenshot 2016-10-31 14 57 58](https://cloud.githubusercontent.com/assets/812905/19873136/84c00cc0-9f7a-11e6-8b99-c18a7c64c8f2.png)

If I set it to, say 20 minutes, it looks like so:
![screenshot 2016-10-31 15 00 37](https://cloud.githubusercontent.com/assets/812905/19873345/c5136dca-9f7b-11e6-95f1-0d3aee50f13e.png)

The same issue is happening with seconds, when I use `e-second-step="1"`

Thanks!

**Comment by ckosloski** [comment]
I found the issue, I just need some time to get it fixed.
