### ISSUE TITLE
customizing editable-ui-select

### ISSUE THREAD

**Issue by metialb** [vitalets/angular-xeditable#572]
I would like to use "buttons='no'" on a editableUiSelect and basically have the same visual result/effect as in https://vitalets.github.io/angular-xeditable/#select-nobuttons  (opening the ui-select field when clicking on the anchor, and submitting/changing the value when moving the focus away)

What is the right syntax to use to have the same behavior?! So that there is no need for edit/save buttons at all?!

**Comment by ckosloski** [comment]
I think you can use no buttons, but you have to hit enter after your selection in order for the model to be updated.
