### ISSUE TITLE
Radiolist doesn't support boolean as model

### ISSUE THREAD

**Issue by thematho** [vitalets/angular-xeditable#575]
~~Hi.
When editable-radiolist has bind a boolean variable It doesn't reflect the correct value the first time is editing. [JSFiddle](https://jsfiddle.net/dp4j28ua/)
Regards.~~

**Update**
Please close, the issue was fixed on new versions

**Comment by ckosloski** [comment]
Your fiddle is using the wrong angular-xeditable version.  Please see this [fiddle](https://jsfiddle.net/ckosloski/wsv4xwbd/1/)
