### ISSUE TITLE
Add permanent empty value in select dropdown options

### ISSUE THREAD

**Issue by mrcmorales** [vitalets/angular-xeditable#58]
Hello,

How I can add a emtpy value in dropdown list ?

In angular it do this way:

<select id="sel" class="input-block-level" ng-model="list_category" ng-options="obj.id as obj.name for obj in list_categories.data">  
    <option value="">Other</option>
</select>

But Hoy I can do it with xeditable ?

http://jsfiddle.net/NfPcH/358/

Thanks

**Comment by bioform** [comment]
I want to reopen this issue. Above solution is not right since in this case "editable-empty" css class be tot set for the xeditable element
