### ISSUE TITLE
The Js Fiddle Example for the Date Selector does not work

### ISSUE THREAD

**Issue by dadepo** [vitalets/angular-xeditable#580]
The JsFiddle Example here http://jsfiddle.net/NfPcH/23/ included in the documentation for the datetime picker does not work

**Comment by ckosloski** [comment]
That is because it is out of date.
@eugef do you know how to update the fiddle?

**Comment by eugef** [comment]
@ckosloski no, could you create a new fiddle and update link in the readme?

**Comment by ckosloski** [comment]
OK, I'll work on that for my next pull request.

**Comment by ckosloski** [comment]
This can be closed, the fiddle was updated in #583
