### ISSUE TITLE
editable-tags-input Not Working

### ISSUE THREAD

**Issue by wasitaanggara** [vitalets/angular-xeditable#582]
![untitled](https://cloud.githubusercontent.com/assets/11562240/20715071/8eeccdb0-b680-11e6-8dcf-c7a773912e15.png)

Great Work dude, so usefull tools. But i have problem with editable NgTagsInput not working, i just copied all from your documentation https://vitalets.github.io/angular-xeditable/#ngtags but not show.
Thanks, sorry for my bad english.

**Comment by ckosloski** [comment]
Please post your code or a link to a jsfiddle/plunkr.

**Comment by wasitaanggara** [comment]
https://jsfiddle.net/wasita_anggara30/5rk67uqk/ here dude, thanks for your response. i need some help why this code not work.
Regards.

**Comment by wasitaanggara** [comment]
im also change editable-text / editable-dropdown work editable with text and dropdown, but when editable-tags-input its not work.

**Comment by ckosloski** [comment]
Can you update your jsfiddle with the correct JS files?  Currently the only files being included are the ng-tags files, all other files are not found because you are using a relative path and they are not there.

**Comment by wasitaanggara** [comment]
i know the problem dude, i have template urban admin with angular-xeditable version 0.1.9 and the lastest version is 0.5.0 not support NgTagInput. but i just wanna ask some queestion, with v.0.1.9 editable-dropdown work with search data select, but in version 0.5.0  not work?
