### ISSUE TITLE
Date view in combodate

### ISSUE THREAD

**Issue by federicoco** [vitalets/angular-xeditable#585]
hello, I'm using angular Xeditable for my thesis.
`<a href="#" id="dataInizio" editable  editable-combodate="risultato[0].data_inizio" data-pk="1"  data-title="Quando è succcesso?">{{risultato[0].data_inizio }}</a>`
                        
where data_inizio is a date returned from a **query in datetime format (2016-05-05 15:00:00)** .
I would like to display the date in this format (in the `<a> tag` ) 
`1 Febbraio 2016 15:00   `                 where Febbraio is the month in italian .
After I change the date it shows the changed date in this format `2015-03-01T04:00:00.000Z` <br>
so, my problems are : <br>
**1)Show in the a tag a localized italian date
2)when the date is changed, show it in a human comprensive way**
Can you please help me?

**Comment by federicoco** [comment]
I've managed to display it in a human comprensible way, but it is in english : if I want to change the locale to italian ?

**Comment by ckosloski** [comment]
You need to load the translations for [moment.js](http://momentjs.com/docs/#/i18n/) also look [here](http://momentjs.com/docs/#/i18n/loading-into-browser/)

**Comment by federicoco** [comment]
I've included the moment-with-locales.js and in the init function of angular(equivalent of $(function)), I wrote
`moment().locale('it');`

![github](https://cloud.githubusercontent.com/assets/22914696/20795164/f9573a8c-b7cf-11e6-9c07-b87ea78b6b1a.jpg)

if you see the attached images you will understand what I'm trying to achieve

**Comment by ckosloski** [comment]
Do you have Angular setup for [i18n](https://docs.angularjs.org/guide/i18n)?

**Comment by federicoco** [comment]
no, what fix would you suggest me ?

**Comment by ckosloski** [comment]
You need to setup i18N for Angular.  See this [stackoverflow ](http://stackoverflow.com/questions/26216414/angularjs-filter-date-and-locale-service)as an example

**Comment by federicoco** [comment]
hello sorry to annoy you, I've added the libraries like stackoverflow example suggested .
The date is printed in italian locale only when is changed
1) underlined date : In english
2) popup combo date : months in english
3) Change date in Italian locale, but it does not update the old date

**Comment by ckosloski** [comment]
1.  It sounds like Angular isn't setup for localization correctly.  Maybe try this [link](http://tutorials.jenkov.com/angularjs/internationalization.html)
2.  It sounds like Moment is not setup for localization correctly if the combodate dropdown is in English.  Did you set the locale for moment?
3.  Not sure about this, if everything is in english, how are you updating to Italian?

You might need to create a jsfiddle/plunker with your code if you want further specific help.

**Comment by thienedits** [comment]
Hello sorry to hijack this post but I have a question about the displayed datetime value. When testing locally on my machine the displayed valued is shown in UTC. Is this working as should? How do you get the displayed value to show in the users timezone?

**Comment by thienedits** [comment]
hmmm nvm, I don't think our api is correctly returning datetime in UTC format.

**Comment by ckosloski** [comment]
@thienedits should this issue be closed?

**Comment by thienedits** [comment]
Yes my issue has been resolved not sure about original post owner though.
