### ISSUE TITLE
Onchange event for drop-down / editable-select

### ISSUE THREAD

**Issue by paksys** [vitalets/angular-xeditable#59]
working on building a cascading dropdown for country/states but the onchange (ng-change) is not working for the editable-select.

**Comment by pavi95** [comment]
Any update on this? Am stuck with this issue..

**Comment by ckosloski** [comment]
@pavi95 what exactly is your issue?  As far as I know `e-ng-change` should work.  Please provide a jsfiddle/plunkr showing your issue.

**Comment by pavi95** [comment]
@ckosloski Exactly my issue is cascading dropdown. While am selecting dropdown A, it will update the dropdown B like country and state. my scope variable is not updating in my view :(

**Comment by pavi95** [comment]
@ckosloski Thanks for your time man.. I found this [https://jsfiddle.net/32kzsvve/1/](url).. It helps me out..
