### ISSUE TITLE
Add class when xeditable is disabled

### ISSUE THREAD

**Issue by MooDySmiles** [vitalets/angular-xeditable#591]
Hi!

Is it possible to add a "disabled" css class to the Xeditable element (when it is disabled)?
It would be really helpful to have a css class like that in order to adjust the appearance of the element.

Right now the style is the same, whenever it is enabled or disabled.

**Comment by ckosloski** [comment]
It's possible.  Do you need the styles to dynamically change between enabled/disabled?

**Comment by MooDySmiles** [comment]
Yes, something like "editable-disabled" to be added runtime when edit-disable="true" and to be removed when edit-disable="false"

**Comment by ckosloski** [comment]
I tried watching the editable-disabled attribute and changing the classes, but I couldn't get it to work right.
I could give you a one time shot css when the element is loaded the first time.
Or, you could add some styling yourself by adding a class based upon the same criteria you are using for the editable-disabled attribute.

**Comment by MooDySmiles** [comment]
It's pretty useless for us give it css when the element is loaded the firts time.
Right now it isn't a fundamental feature, so we'll work on it when we'll have the time.

Thanks for your time! :smiley:

**Comment by ckosloski** [comment]
@MooDySmiles did you figure out a fix for this?

**Comment by MooDySmiles** [comment]
@ckosloski we hacked that by placing a span (with ngIf) when we want xeditable to be disabled.
We have been moved onto a new whole project, so I don't think we will be able to do any progress on this, sorry :disappointed:

**Comment by ckosloski** [comment]
@MooDySmiles  Do you want to close this issue then?

**Comment by MooDySmiles** [comment]
If it's okay for you, it's okay for me.
