### ISSUE TITLE
angular-xeditable doesn't work well within ui-bootstrap <uib-tabset> element

### ISSUE THREAD

**Issue by LegendOfFire** [vitalets/angular-xeditable#594]
I embed a angualr-xeditable inside a uib-tabset element, however the form can't be submitted.

Please check the code: http://plnkr.co/edit/itDFMD?p=preview

**Comment by ckosloski** [comment]
I think the issue is how uib-tab handles clicks.  Please see #563.  There is a working example there.

**Comment by ckosloski** [comment]
Please close this issue if your issue is solved.
