### ISSUE TITLE
how to edit two resouces

### ISSUE THREAD

**Issue by gerome0123** [vitalets/angular-xeditable#597]
i have two resources leave_credits and leave_credits_summary in my leave_credit im editting a data of leave_credits.no_of_days if that change i want to change the leave_credtis_summary.total_number_of_days without reloading is this possible??? im using editable table

**Comment by ckosloski** [comment]
Did you try using `e-ng-change`?

**Comment by gerome0123** [comment]
@ckosloski no i think my my data update is asynchronous

**Comment by ckosloski** [comment]
What types of inputs are your two fields?
Do you mean you want to update the value on the screen and on the backend when you update the first item?
Do you have any code you could show?

**Comment by gerome0123** [comment]
here's my view(slim format)

`md-content
  div layout="row" layout-sm="column" layout-align="space-around"
  div.md-whiteframe-1dp
    md-toolbar
      div.md-toolbar-tools
        span Leave Credits
        span flex=""
        form editable-form="" name="tableform" onaftersave="saveTable()"
          div class="btn-edit"
            md-button.lc-edit type="button" ng-show="!tableform.$visible" ng-click="tableform.$show()"
              | Edit

            div.lc-btn-form ng-show="tableform.$visible"
              md-button.lc-save type="submit" ng-disabled="tableform.$waiting" class="btn btn-primary" save
              md-button.lc-cancel type="button" ng-disabled="tableform.$waiting" ng-click="tableform.$cancel()" class="btn btn-default" cancel
    md-content layout-padding=""
      table.md-table
        thead
          tr.md-table-headers-row
            th.md-table-header
              | Name
            th.md-table-header ng-repeat="leave in ctrl.leaves | orderBy: 'id'"
              | {{ leave.name }}
          tr.md-table-headers-row
            th.md-table-header
            th.md-table-header ng-repeat="leave in ctrl.leaves | orderBy: 'id'"
              | left / Initial
        tbody
          tr.md-table-content-row ng-repeat="record in ctrl.leave_records | unique: 'employee_id '"
            td style="white-space:nowrap; line-height: 60px"
              | {{ record.name }}
            td align="center" ng-repeat="record in record.leave_credits"
              div.rem-item layout="row" layout-align="center"
                div.remaining
                  | {{record.values.remaining}}/
                div.item-wrapper
                  span ng-hide="tableform.$visible" e-style="width:50px;" editable-text="record.no_of_days" e-form="tableform" onbeforesave="checkRecord($data, record)"
                    | {{ record.no_of_days || 'empty' }}`


and my controller(coffee format)

`#= require ./../../module

class LeaveCreditsIndexCtrl
  constructor: ($scope, $timeout, $location, $window, $route, LeaveType, LeaveCredit)->

    @leaves = LeaveType.query()

    LeaveCredit.summary (data)=>
      @leave_records = data

    nums = []

    $scope.saveTable = () =>

      for data in nums
        LeaveCredit.update(data)

    $scope.checkRecord = (data, record) ->
      if data != record.no_of_days
        nums.push({ id: record.id, no_of_days: data })


LeaveCreditsIndexCtrl.$inject = ["$scope", "$timeout" , "$location", "$window", "$route", "LeaveType", "LeaveCredit"]

angular
.module "CaesApp"
.controller "LeaveCreditsIndexCtrl", LeaveCreditsIndexCtrl`



my resource is in the different directory so i give you an example of a json

LeaveType = [
    "id": 1,
    "name": "Vacation Leave",
    "no_of_days": "15.0",
    "created_at": "2017-01-31T16:36:19.022+08:00",
    "updated_at": "2017-01-31T16:36:19.022+08:00"
  },
  {
    "id": 2,
    "name": "Sick Leave",
    "no_of_days": "15.0",
    "created_at": "2017-01-31T16:36:19.060+08:00",
    "updated_at": "2017-01-31T16:36:19.060+08:00"
  },
  {
    "id": 3,
    "name": "Birthday",
    "no_of_days": "1.0",
    "created_at": "2017-01-31T16:36:19.071+08:00",
    "updated_at": "2017-01-31T16:36:19.071+08:00"
  },
  {
    "id": 4,
    "name": "Maternity",
    "no_of_days": "78.0",
    "created_at": "2017-01-31T16:36:19.082+08:00",
    "updated_at": "2017-01-31T16:36:19.082+08:00"
  }]


LeaveCredit.summary = [
  {
    "id": 1,
    "reference_no": "8424161983",
    "name": "Noah Gleason IV",
    "birth_date": "2015-08-11",
    "date_hired": "2016-11-21",
    "image": {
      "normal": "/assets/caes/employees/avatar/normal/missing.png",
      "thumb": "/assets/caes/employees/avatar/thumb/missing.png"
    },
    "leave_credits": [
      {
        "id": 1,
        "employee_id": 1,
        "leave_type_id": 1,
        "leave_type": {
          "id": 1,
          "name": "Vacation Leave"
        },
        "no_of_days": "16.0",
        "values": {
          "initial": 16.0,
          "remaining": 16.0
        },
        "leave_type_with_days": "Vacation Leave (16.0)",
        "created_at": "2017-01-31T16:36:19.179+08:00",
        "updated_at": "2017-02-01T09:34:44.944+08:00"
      },
      {
        "id": 2,
        "employee_id": 1,
        "leave_type_id": 2,
        "leave_type": {
          "id": 2,
          "name": "Sick Leave"
        },
        "no_of_days": "15.0",
        "values": {
          "initial": 15.0,
          "remaining": 15.0
        },
        "leave_type_with_days": "Sick Leave (15.0)",
        "created_at": "2017-01-31T16:36:19.237+08:00",
        "updated_at": "2017-01-31T16:36:19.237+08:00"
      }]

LeaveCredit =[
  {
    "id": 2,
    "employee_id": 1,
    "leave_type_id": 2,
    "no_of_days": "15.0",
    "year_of_effect": 2017,
    "created_at": "2017-01-31T16:36:19.237+08:00",
    "updated_at": "2017-01-31T16:36:19.237+08:00"
  },
  {
    "id": 3,
    "employee_id": 1,
    "leave_type_id": 3,
    "no_of_days": "1.0",
    "year_of_effect": 2017,
    "created_at": "2017-01-31T16:36:19.247+08:00",
    "updated_at": "2017-01-31T16:36:19.247+08:00"
  },
  {
    "id": 4,
    "employee_id": 1,
    "leave_type_id": 4,
    "no_of_days": "78.0",
    "year_of_effect": 2017,
    "created_at": "2017-01-31T16:36:19.257+08:00",
    "updated_at": "2017-01-31T16:36:19.257+08:00"
  },
  {
    "id": 5,
    "employee_id": 1,
    "leave_type_id": 5,
    "no_of_days": "20.0",
    "year_of_effect": 2017,
    "created_at": "2017-01-31T16:36:19.267+08:00",
    "updated_at": "2017-01-31T16:36:19.267+08:00"
  }]



the one i edit is LeaveCredit and when i and LeaveCredits summary is dependent to leaveCredit when i edit LeaceCredit i need to reload the page to change the value in my LeaveCredit.summary

**Comment by ckosloski** [comment]
The formatting above is a little hard to read.
Couldn't you try an `onaftersave` event to call a function that updates `leave_credtis_summary.total_number_of_days` with the value from `leave_credits.no_of_days after it's edited`?
Maybe a plunker or jsfiddle example would better demonstrate the issue you are having.

**Comment by ckosloski** [comment]
@gerome0123 are you still having an issue?

**Comment by ckosloski** [comment]
@eugef I think we can close this issue due to lack of response.
