### ISSUE TITLE
Can we have two forms in one html page

### ISSUE THREAD

**Issue by UmeshKilkile** [vitalets/angular-xeditable#602]
Can we have two forms in one html page?

Like,
 form1
            ...
            form2
              ...
            /form2
         /form1
            

Kindly help with sample e.g.

**Comment by ckosloski** [comment]
I'm not exactly sure what you would like to do, but looking through the issues I found #234 which said to use an ng-form as the inner form.

**Comment by ckosloski** [comment]
If you are having specific issues, please post a jsfiddle or plunker showing your code

**Comment by ckosloski** [comment]
@UmeshKilkile are you still having an issue?

**Comment by ckosloski** [comment]
@eugef This can be closed due to lack of response
