### ISSUE TITLE
submit on tab vs. blurElem option

### ISSUE THREAD

**Issue by dcardosods** [vitalets/angular-xeditable#604]
With the feature from https://github.com/vitalets/angular-xeditable/pull/590, by default a input is always submitted on tab, and canceled when clicking outside the input.

It would be better to submit on tab only if the `blurElem` option or the `blur` attribute are set to `submit`.

**Comment by ckosloski** [comment]
Can you provide a plunkr/jsfiddle showing the issue?  I am not seeing the form submitted on tab when the blur attribute is not set.

**Comment by ckosloski** [comment]
The only time I see the form being submitted is when ` blur="submit" buttons="no"` is set on a single item.  Can you provide a sample of your code where you are seeing it always submit on tab?

**Comment by dcardosods** [comment]
By submitting, I mean having the new value saved to scope.

Only `buttons="no"` is necessary to reproduce the issue.
http://plnkr.co/edit/uVz5MlcgvLhozswzGetA?p=preview
