### ISSUE TITLE
Set value of amount inside of ng-repeat based off of isActive

### ISSUE THREAD

**Issue by westerncj** [vitalets/angular-xeditable#606]
I have an `ng-repeat` editable form like below. How can I set the value of `amount` to `0` when it's disabled by the editable-checkbox (isActive)? I have to working so it disables the `amount` input when `editableDataForm.$data.isActive`, but I can't set the value to `0`.

```
<tr ng-repeat="row in vm.data">
    <td>
        <span editable-checkbox="row.isActive"
              e-name="isActive" e-form="editableDataForm">
        </span>
    </td>
    <td>
        <span editable-text="row.amount"
              e-name="amount" e-form="editableDataForm" e-ng-disabled="editableDataForm.$data.isActive">{{row.amount}}</span>
    </td>
</tr>
```

**Comment by ckosloski** [comment]
Did you try using an `e-ng-change` on the checkbox to set the row.amount to 0 when it's checked?

**Comment by westerncj** [comment]
If I set `row.amount` using `e-ng-change`, then when the cancel button is clicked the value is set to zero.

**Comment by ckosloski** [comment]
what about also changing `row.amount`?

**Comment by westerncj** [comment]
If I change `row.amount`, the underlying model is changed. I'd like to retain the original values if the **Cancel** button is clicked.

**Comment by ckosloski** [comment]
What happens with this code?
`e-ng-change="editableDataForm.$data.amount = (editableDataForm.$data.isActive) ? '0' : row.amount">`

**Comment by westerncj** [comment]
When using that code, it doesn't change `amount` to `0` in edit mode when I check the box.

**Comment by ckosloski** [comment]
This seems to work, the value is updated and reverted if cancelled...but the ui doesn't seem to reflect the change until after the save/cancel.

`e-ng-change="update(editableDataForm)"`

```
 $scope.update = function (form) {
      form.amount.value = 0;
      form.amount.$viewValue = 0
  }
```

**Comment by westerncj** [comment]
I get this error: `TypeError: Cannot set property 'value' of undefined`

**Comment by ckosloski** [comment]
Then I would need to seem more of your code.
