### ISSUE TITLE
editable-select on select

### ISSUE THREAD

**Issue by takotuesday** [vitalets/angular-xeditable#608]
Using the form example, it appears if there is an editible-select element on the form, there is no way to fire off a function upon selection. This would be great for validation purposes.

**Comment by ckosloski** [comment]
Did you try using a `e-ng-change` to execute your validations on selection?

**Comment by takotuesday** [comment]
@ckosloski thanks for the quick response. Yes I did, but the problem is I cant access whatever the new value being selected is, only the old value that was previously selected.

**Comment by ckosloski** [comment]
Please provide the code you are trying.

**Comment by takotuesday** [comment]
Here is an example in JSFiddle. See the `user.status` editable-select.

http://jsfiddle.net/NfPcH/18046/

**Comment by ckosloski** [comment]
See this updated [fiddle](http://jsfiddle.net/ckosloski/yks94u3u/1/)

**Comment by takotuesday** [comment]
@ckosloski this is awesome, thank you.
