### ISSUE TITLE
editable-checkbox without e-title on editable row

### ISSUE THREAD

**Issue by pdorgambide** [vitalets/angular-xeditable#610]
Using an `editable-checkbox` on a editable row scenario. When the  `e-title` attribute is not defined the input checkbox are wrong aligned.

Tested with boostrap 3.3.7
See: http://jsfiddle.net/pdorgambide/0tcwedtz/

**Comment by ViniciusCPSouza** [comment]
@pdorgambide I've dealt with that before by using `e-title="&zwnj;"`.
