### ISSUE TITLE
Update $data from server

### ISSUE THREAD

**Issue by okezieokpara** [vitalets/angular-xeditable#614]
My onBeforeSave function first updates the data on the server before updating on the local (or create a new record if it doesn't exist before). But I want to use the result data from the server to update the local (the new data from the server has an id primary key field, if the data is new). How can I do this?

**Comment by ckosloski** [comment]
Can you post the code you have so far?

**Comment by ckosloski** [comment]
@okezieokpara are you still having an issue?

**Comment by okezieokpara** [comment]
no thanks

**Comment by ckosloski** [comment]
OK, can you close this issue then?
