### ISSUE TITLE
Not parsing popover options?

### ISSUE THREAD

**Issue by rusackas** [vitalets/angular-xeditable#621]
Maybe I'm just missing something, but I have a popover editable (which is lovely to have, thank you), with HTML like so:

```
<div class="popover-wrapper">
<a href="#" editable-text="name" onbeforesave="update()">{{name || 'Untitled'}}</a>
</div>
```

Presumably, on the wrapper, I'd like to add the following options, which seem to be ignored by 
`popover-append-to-body`
`placement="bottom"`

..which I also tried as
`e-popover-append-to-body`
`e-placement="bottom"`

I also tried them on the `<a>` tag, but alas, no dice. Many thanks to anyone that can point me in the right direction here.

**Comment by ckosloski** [comment]
Hi, there is no directive for the popover, it's a purely css implementation and it's not related to the ui-bootstrap popover.

**Comment by rusackas** [comment]
Thanks... that explains why I couldn't find the code. I guess I'm out of luck if a popover gets cut off when going outside the edge of a containing div with overvlow:hidden? I'll close the issue, but if there's a solution you're aware of, let me know. Thanks again.

**Comment by ckosloski** [comment]
Open an issue with a link to a jsfiddle showing your issue so that someone can look at it.

**Comment by rusackas** [comment]
I whipped up a quick Beatles editor that illustrates the issue. Clicking the names to edit them in a popover, you should see that the popover is cut off on the left and/or top due to it being in a container with overflow:auto; 

http://jsfiddle.net/rusackas/gsrLo40x/6/

I think the popover placement options, or better still, the `popover-append-to-body` option would solve the issue, but I'm open to other suggestions.

**Comment by ckosloski** [comment]
Take a look at this [fiddle](http://jsfiddle.net/ckosloski/sqd3z5wk/1/).  I got it working with a couple css changes:

```css
bandmate{
  margin-bottom: 1rem;
  padding-bottom: 3rem;
  border-bottom: 1px solid #999;
}

.popover-wrapper {
	display: inline;
	position: fixed;
}

**Comment by rusackas** [comment]
That's **_awesome_** for most situations. I used it in my real site (which I wish I could share here) but ran into another wrinkle. If the content area with the editable is a scrolling pane, the fixed elements don't move. 

I think adding some scroll event listeners and adjusting css position according to scroll offset might be the ticket here. I'll play with it. Meanwhile, I tweaked the fiddle with a shorter/scrolling content area to illustrate what I'm talking about.

**Comment by ckosloski** [comment]
Check out this [one](http://jsfiddle.net/ckosloski/q02041g7/26/)

I dynamically change the css based on show/hide so the links still properly scroll.

**Comment by jongunter** [comment]
I'm having this issue, as well.

**Comment by ckosloski** [comment]
Please provide a plunkr or jsfiddle showing your issue.

**Comment by jongunter** [comment]
http://plnkr.co/edit/c5v1PH4uDBpoxuXegtx0?p=preview

As you can see, when the popover opens, it is cut off by the sidebar. Usually I would use the `popover-append-to-body` option with UI bootstrap to prevent this problem, but this popover isn't internally created using ui-boostrap, correct?

Yeah, I could tweak some CSS (I'm adding this plugin a large legacy codebase, which makes that solution a bit more challenging), but if you're already requiring ui-bootstrap for the editable typeahead, it would make sense to use it for the editable popover, so users can have more control.

**Comment by ckosloski** [comment]
Pull requests are welcome :)

**Comment by ckosloski** [comment]
@jongunter Take a look at [this](http://jsfiddle.net/ckosloski/dkbhc9s5/13/) and see if it helps.
