### ISSUE TITLE
Uncaught TypeError: angular.forEach is not a function

### ISSUE THREAD

**Issue by pradyumnad** [vitalets/angular-xeditable#633]
Do you have any specification for angularjs?
I am using it with angularjs 1.5.8

**Comment by ckosloski** [comment]
Can you post a plnkr or jsfiddle showing your error?  I have used 1.5.8 and I'm currently on 1.6.2 with no issues using xeditable.

**Comment by pradyumnad** [comment]
Sorry my bad, I missed the order of scripts included..
