### ISSUE TITLE
Icon inside input field

### ISSUE THREAD

**Issue by sim999** [vitalets/angular-xeditable#634]
Hi,

First thanks for the library !

I would like to include an asterix icon for mandary field inside input like on this demo : 
http://formvalidation.io/addons/mandatoryIcon/. It is very similar to Bootstrap Form Control States 
with the .has-feedback class.

 How can I achieve this ?

**Comment by ckosloski** [comment]
I think the closest thing is to add the [input group](http://vitalets.github.io/angular-xeditable/#text-customize) and style it.

**Comment by sim999** [comment]
thnaks for your answer
