### ISSUE TITLE
empty date issue when using combo date

### ISSUE THREAD

**Issue by opencubicles** [vitalets/angular-xeditable#636]
I am unable to set the combo date input values from non-empty to empty.

http://jsfiddle.net/opencubicles/vu8zLoh3/21/

it's not required input.

**Comment by ckosloski** [comment]
Can you be more specific on what your issue is?

When I go to the jsfiddle, I see a value for User DOB and I can change it.

**Comment by opencubicles** [comment]
If you try to edit the date and leave the values for all the the options as empty for combo-date dropdown and hit save, it will not retain the new empty value.

**Comment by opencubicles** [comment]
Thank you!
