### ISSUE TITLE
How can i get this format using combodate 2017-03-21T01:21:12-07:00

### ISSUE THREAD

**Issue by thienedits** [vitalets/angular-xeditable#639]
I tried using `e-format="YYYY-MM-DD +-HH:mm"` but got error `Uncaught RangeError: Invalid time value` when saving.

`<span editable-combodate="eventCtrl.event.startTime" e-name="startTime" e-format="YYYY-MM-DD +-HH:mm" e-template="YYYY / MM / DD     HH : mm">{{ (eventCtrl.event.startTime |  date:"medium") || 'empty' }}</span>`

any ideas?

**Comment by ckosloski** [comment]
Looking at this I am thinking you don't need `e-format`.  If you are trying to saving the data in the db with that format, then you need to convert it before saving.
The code is always returning the isoString value of the date. I think you just need to take that and format it how you need it.

**Comment by thienedits** [comment]
ok thanks thats what i was thinking of doing.
