### ISSUE TITLE
How can you set combodate to empty value?

### ISSUE THREAD

**Issue by thienedits** [vitalets/angular-xeditable#640]
Selecting the empty values from the select element I get console error `Uncaught RangeError: Invalid time value`. From the current logic it doesn't look likes its possible to set the combodate to an empty or null value.

**Comment by ckosloski** [comment]
This was just [fixed](https://github.com/vitalets/angular-xeditable/pull/638).  There needs to be a new release published or you can build the code your self until a new release is published.

**Comment by thienedits** [comment]
ok thanks.
