### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by joaopgg** [vitalets/angular-xeditable#642]
Guys, when are you planning to release a new version with the merged changes (npm/bower)?

Best regards
João Gomes

**Comment by ckosloski** [comment]
@eugef when do you plan on doing a release?

**Comment by eugef** [comment]
Will do release tomorrow.

**Comment by joaopgg** [comment]
Thanks guys

Cheers.

**Comment by eugef** [comment]
New release 0.7.0 is out
