### ISSUE TITLE
angular-sanitize not found on demo page

### ISSUE THREAD

**Issue by Sharvadze** [vitalets/angular-xeditable#643]
Hi,

This file is missing and demo page doesn't work because of that

https://vitalets.github.io/angular-xeditable/bower_components/angular-sanitize/angular-sanitize.js

**Comment by ckosloski** [comment]
@eugef looks like something didn't build right, can you take a look?

**Comment by eugef** [comment]
Thanks for the quick feedback. I fixed it.
