### ISSUE TITLE
[Help]Custom input, several fields for angular js

### ISSUE THREAD

**Issue by thaodx** [vitalets/angular-xeditable#644]
I found this demo:
http://vitalets.github.io/x-editable/demo-bs3.html?c=popup
With 'Custom input, several fields' in jQuery, anyone can turn into angular js version for this example?

**Comment by ckosloski** [comment]
This is not currently available.  Pull requests are welcome :)

**Comment by ckosloski** [comment]
I came up with an [idea](http://jsfiddle.net/ckosloski/dkbhc9s5/13/), see if it works for you.

**Comment by thaodx** [comment]
Thank you very much @ckosloski

**Comment by ckosloski** [comment]
If that works for you, please close this issue.
