### ISSUE TITLE
update inline file??

### ISSUE THREAD

**Issue by gerome0123** [vitalets/angular-xeditable#645]
is there possible to edit type file in xeditable???

**Comment by ckosloski** [comment]
An input type of file currently isn't supported.  Pull requests are welcome :)

**Comment by gerome0123** [comment]
thanks for the reply i'm new in angularjs lol XD additional question @ckosloski can i run xeditable in mddatatable by iamisti/mdDataTable

**Comment by ckosloski** [comment]
I'm not sure.  You can try and report back your results.  I did find issue #232 which may help.

**Comment by gerome0123** [comment]
ok i will try that one thanks :*

**Comment by ckosloski** [comment]
@gerome0123 I take my comment back, the file input type is supported, it's just not in the documentation.  I'll update the document in a future pull request.

**Comment by gerome0123** [comment]
@ckosloski sweet!!! :)

**Comment by pavi95** [comment]
@ckosloski  Can you please let me know how to handle the uploaded file on update to server? Not able to get the file using scope. Please help me out

**Comment by ckosloski** [comment]
Can you provide code and any errors you are seeing?

**Comment by pavi95** [comment]
@ckosloski  Thanks for your reply. Please find my code

My template:

<td>
			<span  e-ng-file-select="onFileSelect($files)" e-accept=".jpg,.png,.gif,.jpeg" editable-file="item.channel_logo" e-name="channel_logo" e-form="rowform"  e-required>{{item.channel_logo}} </span>
			<img id="loadPic" ng-src="{{picture}}" >
</td>

Form Submit:

 <form editable-form name="rowform" ng-show="rowform.$visible" class="form-buttons form-inline"
            shown="inserted == item" onbeforesave="updateItem($data, $files, item.channel_id, rowform)">
        <button type="submit" ng-disabled="rowform.$waiting" class="btn btn-primary editable-table-button btn-xs">
          Save
        </button>
        <button type="button" ng-disabled="rowform.$waiting" ng-click="cancelData(item, rowform, ((current_page-1)*smartTablePageSize)+$index+1 )"  g-clik="rowform.$cancel($index,item)" class="btn btn-default editable-table-button btn-xs">
          Cancel
        </button>
      </form>

My js:

$scope.updateItem = function (data, file, id, rowform){
		
		return $http.post('/api/updateChannel', {data: data, id:id}).then(
		  function successCallback(response){
			  console.log(response.data);
			
			$scope.alertMessageSuccess = true;
				$timeout( function(){ $scope.callAtTimeout(); }, 5000);
			  
		  }, 
		  function errorCallback(err, status, headers) {
			
				$scope.editableForm.$setError('name', 'Unknown error!');
				$scope.alertMessageWarning = true;
				$timeout( function(){ $scope.callAtTimeout(); }, 5000);
		  }
		);
	}

Error: no data passed through post method for file.
My question: How to send the uploaded formData to api server call? Please help me

**Comment by ckosloski** [comment]
How is updateItem called?

**Comment by pavi95** [comment]
Please find it here

`<form editable-form name="rowform" ng-show="rowform.$visible" class="form-buttons form-inline"
            shown="inserted == item" onbeforesave="updateItem($data, $files, item.channel_id, rowform)">`

**Comment by ckosloski** [comment]
What are you trying to achieve with `$files`?  If you want to get the model, I think it should be `$parent.$data`

**Comment by pavi95** [comment]
Thanks @ckosloski

**Comment by ckosloski** [comment]
@pavi95 did you get your issue resolved?

**Comment by ckosloski** [comment]
@eugef this issue can be closed
