### ISSUE TITLE
editableOptions.blurElem with editableOptions.buttons not working

### ISSUE THREAD

**Issue by Johan-CR** [vitalets/angular-xeditable#646]
The use of the option blurElem = 'submit'; does not work if used with buttons = 'no'

  editableOptions.blurElem = 'submit';
  editableOptions.buttons = 'no';

http://jsfiddle.net/Johan_CR/w3353mhk/

**Comment by ckosloski** [comment]
This is only an issue with the bootstrap datepicker

**Comment by Johan-CR** [comment]
That is not correct, this is a issue with all the inputs, I change the example and add a text input

http://jsfiddle.net/Johan_CR/w3353mhk/2/
