### ISSUE TITLE
All JSFiddle Examples are broken

### ISSUE THREAD

**Issue by calhouncole** [vitalets/angular-xeditable#647]
After the release of 0.7.0, it appears that all of the JSFiddle examples referenced from the documentation [here](https://vitalets.github.io/angular-xeditable/) are broken.

[Broken Example](http://jsfiddle.net/NfPcH/25/)

**Comment by ckosloski** [comment]
I'll see what I can do to get them updated.

**Comment by efsh** [comment]
Try update to latest AngularJS1 version (1.6.4)

[Here an example]( http://jsfiddle.net/jacone/6o775a1f/1/)

**Comment by ckosloski** [comment]
@eugef please close, these are fixed
