### ISSUE TITLE
can i use datepicker without bootstrap?

### ISSUE THREAD

**Issue by gerome0123** [vitalets/angular-xeditable#652]
how to put a simple html date picker?

**Comment by ckosloski** [comment]
There is a [HTML5 ](http://vitalets.github.io/angular-xeditable/#html5-inputs )date picker, but it is not supported by all browsers.  It does work in Chrome.

**Comment by gerome0123** [comment]
@ckosloski can u give a sample of combodate without time

**Comment by ckosloski** [comment]
Try `e-data-template="DD / MM / YYYY"`

**Comment by gerome0123** [comment]
![screen shot 2017-04-25 at 10 23 14 am](https://cloud.githubusercontent.com/assets/20182366/25366252/0eb9b682-29a1-11e7-8341-17691f31a665.png)


didn't work

**Comment by gerome0123** [comment]
i just create my own combodate by using editable-select btw thanks @ckosloski 😘😘😘

**Comment by gerome0123** [comment]
@ckosloski can you give an example for datapicker simple html

**Comment by ckosloski** [comment]
What exactly do you want an example of?  I had previously posted about combodate.  If you are still having issues with combodate, please post a jsfiddle/plunker of your issue.

**Comment by gerome0123** [comment]
@ckosloski  thanks for the feed back i just want a plain date picker with calendar without bootstrap just a simple html

**Comment by ckosloski** [comment]
That is a [jquery](https://jqueryui.com/datepicker/) date picker

**Comment by gerome0123** [comment]
oh i see that make sense now

**Comment by ckosloski** [comment]
@gerome0123 Try using editableUidate.  It exists, but isn't documented.  I haven't used it before so I don't know if it works or not
```
/*
 jQuery UI Datepicker for AngularJS
 https://github.com/angular-ui/ui-date
 */
angular.module('xeditable').directive('editableUidate', ['editableDirectiveFactory',
    function(editableDirectiveFactory) {
        return editableDirectiveFactory({
            directiveName: 'editableUidate',
            inputTpl: '<input class="form-control" />',
            render: function() {
                this.parent.render.call(this);
                this.inputEl.attr('ui-date', this.attrs.eUiDate);
                this.inputEl.attr('placeholder', this.attrs.ePlaceholder);
            }
        });
}]);
```
