### ISSUE TITLE
inline editing cannot post to db, and how to create debug

### ISSUE THREAD

**Issue by ikwijaya** [vitalets/angular-xeditable#655]
dear vitalets,

i have some code below:
dirPagination for paging and xeditable for inline editing, in my case i want just change 1 column if i click the value in column, and save to my db or ldap server in my case. Here the code i was create,
- js file
`var app = angular.module('appRoot',["angularUtils.directives.dirPagination","xeditable"]);
app.controller('ctrlData', function($scope,$http){
        $scope.pageSize = 25;
        $scope.currentPage = 1;
        $scope.dataTable = <?php print $this->json; ?>;
        $scope.sort = function(keyname){
             $scope.sortKey = keyname;
             $scope.reverse = !$scope.reverse;
        }

        $scope.pageChangeHandler = function(num) {
            console.log('Data page changed to ' + num);
        }

        $scope.updateUser = function(){
            $http.post('<?php print Config::get('URL');?>phonebook/modify', 
                {
                    id: $scope.adb.nik, 
                    ipphone: $scope.adb.ipphone
                }
            ).success(function(data, headers, status, config){
                console.log(data);
            }).error(function(data, headers, status, config){
                console.log(data);
            });
        };
    });`

html table 
<div class="container">
    <h2>Phonebook Management</h2>
    <div class="box" ng-controller="ctrlData" id="ctrlData">
        
        <?php $this->renderFeedbackMessages(); ?>
        <label>Search : </label> <input type="text" ng-model="search" placeholder="Type text here.." style="width:60%;" />
        <div class="navigation right">
            <label>Item(s) :</label> 
            <select ng-model="pageSize">
                <option value="10">10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
        </div>
        <div class="navigation right">
            Showing <b>{{ pageSize }}</b> item(s) of <b>{{ dataTable.length }}</b> entries.
        </div>
        <table class="table table-bordered">
            <thead>
                <tr style="font-size:12px;">
                    <th style="text-align: center;">No</th>
                    <th style="text-align: center;" ng-click="sort('nik')">NIK
                        <span class="glyphicon sort-icon" ng-show="sortKey=='nik'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                    </th>
                    <th style="text-align: center;" ng-click="sort('nama_karyawan')">Nama Karyawan
                        <span class="glyphicon sort-icon" ng-show="sortKey=='nama_karyawan'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                    </th>
                    <th style="text-align: center;" ng-click="sort('email')">Email
                        <span class="glyphicon sort-icon" ng-show="sortKey=='email'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                    </th>
                    <th style="text-align: center;" ng-click="sort('department')">Department
                        <span class="glyphicon sort-icon" ng-show="sortKey=='department'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                    </th>
                    <th style="text-align: center;" ng-click="sort('ipphone')">Ext
                        <span class="glyphicon sort-icon" ng-show="sortKey=='ipphone'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr dir-paginate="adb in dataTable | orderBy:sortKey:reverse | filter:search | itemsPerPage: pageSize" pagination-id="listphonebook" style="font-size: 11px;">
                    <td>{{ $index+1 }}</td>
                    <td>{{ adb.nik }}</td>
                    <td>{{ adb.namakaryawan }}</td>
                    <td>{{ adb.email }}</td>
                    <td>{{ adb.department }}</td>
                    <td><a href="#" editable-number="adb.ipphone" onafteresave="updateUser()">{{ adb.ipphone || 'empty' }}</a></td>
                </tr>
            </tbody>
        </table>
    </div>
    <center>
        <div ng-controller="ctrlPagination">
            <dir-pagination-controls pagination-id="listphonebook" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="<?php echo Config::get('URL'); ?>pagination"></dir-pagination-controls>
        </div>
    </center>
</div>

and php 
`public function modify(){
        $postdata = file_get_contents("php://input");
        $data = json_decode($postdata);
        $user = $data->nik;
        $ipphone = $data->ipphone;
        $output = LDAP::changeAttrWithauthForAdmin($user,'ipphone',$ipphone);
        if(!$output){
            Session::add('feedback_negative', Text::get('FEEDBACK_LDAP_IPPHONE_SAVED'));
            return false;
        }
        Redirect::to('phonebook/index');
    }`

and 
![table-02](https://cloud.githubusercontent.com/assets/23114902/25692875/eaa0d150-30cf-11e7-921e-783bddccf9e5.PNG)

![image](https://cloud.githubusercontent.com/assets/23114902/25692914/369410d6-30d0-11e7-8d32-4f134a1ee107.png)

my problem 
i check with chrome xhr-network but not action show,

please admit..
ikwijaya

**Comment by ckosloski** [comment]
The code seems ok.
Are there any errors in the console?
Did you try putting in a console.log in the updateUser function to verify it is being called?

**Comment by ikwijaya** [comment]
here?
![image](https://cloud.githubusercontent.com/assets/23114902/25739284/76414362-31ab-11e7-8459-628e1a8400f1.png)

why not action show in console log in browser?
here my sources included:
![image](https://cloud.githubusercontent.com/assets/23114902/25739339/baf92290-31ab-11e7-9f99-7a5543b143c3.png)

**Comment by ckosloski** [comment]
Are you sure that `$scope.dataTable.nik` has a value?
It looks like dataTable is a list, not an object.
Maybe you need to try `onaftersave="updateUser(adb.nik, adb.ipphone)"` and see if the correct values get passed in to your function.

**Comment by ikwijaya** [comment]
case close sir..
here my last code
![image](https://cloud.githubusercontent.com/assets/23114902/25792661/145b2fac-33f2-11e7-99fd-da342e04abc2.png)

i change some code like updateUser(data,id) in js. So in xeditable use onbeforesave=updateUser($data,adb.nik)
code working perfectly

nuhun pisan..
