### ISSUE TITLE
Option for ng-bind-html

### ISSUE THREAD

**Issue by katsos** [vitalets/angular-xeditable#656]
As you can see in my plunker below I cannot use ng-bind-html with xeditable.
I am using Angular 1.5.5. Is there any way to do it?

Plunker: http://plnkr.co/edit/UOdwEb5DSsXwmSk2MN7F?p=preview

**Comment by ckosloski** [comment]
Your plnkr is using angular 1.0.8, please update it to 1.5.5 and also include angular-sanitize.js.  It is throwing error `Error: Unknown provider: $sceProvider <- $sce`

**Comment by katsos** [comment]
@ckosloski sorry, wrong link. updated.

**Comment by ckosloski** [comment]
I still see an error in the console:
`Error: [$sce:unsafe] http://errors.angularjs.org/1.5.5/$sce/unsafe`
If you are trying to have the html display, I think you need to do something like `$sce.getTrustedHtml`

**Comment by katsos** [comment]
Thank you very much. I updated my code on plunker so anyone with the same problem can find it easy.
