### ISSUE TITLE
How to keep edit mode open if server returns 400

### ISSUE THREAD

**Issue by bokrizan** [vitalets/angular-xeditable#658]
How to keep open edit mode if server response with error? Now, when I click submit and send data to API, my form automatically is close, but I want to close edit mode only if server response with success, and stay opened if a response with an error. Thank you

`

$scope.saveTableConfig = function () {
        var config = {
            headers: {
                'Content-Type': 'application/xml',
                'X-HTTP-Method-Override': 'PUT'
            }
        };

        var configCopy = angular.copy($scope.currentConfig);

        $http.post(serviceBase + 'cd/saa/' + $stateParams.aaaID + '/config', configCopy, config)
                .success(function (data, status, headers, config) {
                    Notification.success({message: $filter('translate')('BENCH_EDITED_SUCCESSFULLY'), delay: 3000, positionY: 'bottom', positionX: 'right'});
                })
                .error(function (data, status, header, config) {
                    Notification.error({message: $filter('translate')('BENCH_EDITED_ERROR'), positionY: 'bottom', positionX: 'right'});
                });

    };

form editable-form name="tableform" onaftersave="saveTableConfig()" oncancel="cancel()">
<span editable-textarea="currentKlupa.description" e-name="description" e-
rows="3">Text</span>
</form`

I ask on [stackowerflow](http://stackoverflow.com/questions/43887096/angular-xeditable-how-to-keep-edit-mode-open-if-server-returns-400), but there is no any reply.

**Comment by ckosloski** [comment]
You need to return a string value in your onaftersave method:

`If you need to send data on server after writing to local model then you should define form's onaftersave.
The result of form's onaftersave is also important for next step:

string: form will not close (e.g. server error)
not string: form will be closed`

**Comment by bokrizan** [comment]
Thank you for your reply. Please could you give me a little more detail to explain this, because I did not quite understand

**Comment by bokrizan** [comment]
I fix this, thanks to @ckosloski
