### ISSUE TITLE
Angular-xeditable row not show every row like saved after load webpage

### ISSUE THREAD

**Issue by mrcmorales** [vitalets/angular-xeditable#66]
Hi,

I have the problem that when load webpage, every row not is saved, is to edit and I want that by default should be saved.

Another problem is that when save, opciones column not show correct value, show id and not value.

Every object in products is a product in a table row, then options is the option selected to this product and in product.product_options i sall options that could be this product.

This is the demo in jsfiddle:

http://jsfiddle.net/86U29/26/

Thanks

**Comment by mitcht** [comment]
Closed as being too old
