### ISSUE TITLE
Cross appears at the end of input text on IE 11

### ISSUE THREAD

**Issue by antjori** [vitalets/angular-xeditable#662]
On IE 11 (version 11.0.9600.18665), after selecting the element to edit, a cross appears at the end of the input text that, when clicked, doesn't do anything.

![untitled](https://cloud.githubusercontent.com/assets/8490141/26624546/1d8d2b44-45e9-11e7-8b13-fc49399aaaf4.png)

Is there a way to remove/hide it on IE? This behavior does not occur on other browsers (Google Chrome and Firefox).

**Comment by ckosloski** [comment]
That x is specific to IE and is supposed to clear the box.

If you want to stop the x from displaying, take a look [here](https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs/14739092#14739092).

**Comment by antjori** [comment]
Hey @ckosloski,

Thank you for your feedback!

It solved my issue :wink: 

Much appreciated!
