### ISSUE TITLE
Listbox custom background

### ISSUE THREAD

**Issue by SebastianCBA** [vitalets/angular-xeditable#663]
I have this editable-select 

`<span editable-select="sectorSheet.economy_id" e-name="economy_id" onshow="loadEconomies()" e-form="rowform" e-ng-options="e.id as e.text for e in economies.concat(emptyVal)" e-ng-change="popNew($data, 'div_economy_name')" ></span> `

and emptyVal is called from scope like:

`$scope.emptyVal = [{id: '0', text: 'Or Add New Value'}]; `

how I can change the background color for this option?

**Comment by ckosloski** [comment]
Try this css:
```
select option[value="0"] { /* value not val */
    background: rgba(200, 200, 200, 0.3);
}
```

Taken from [here](https://stackoverflow.com/questions/12836227/how-to-change-select-box-option-background-color)

**Comment by SebastianCBA** [comment]
perfect! thanks
