### ISSUE TITLE
Prepopulate DateTime fields with todays date and a default time

### ISSUE THREAD

**Issue by kristianharmer** [vitalets/angular-xeditable#665]
Hi,

Great piece of work. Overall I've had no issues implementing this on my AngularJS app. However I have stumbled upon one minor issue and that is prepopulating the datetime fields with todays date and a default time (x hours from now)! 

I am using the popover implementation and have tried adding date and time in several formats and using the attributes of 'value' and 'e-value'. I'm convinced that 'e-value' is the way to go since this worked for setting max years and min years etc.

Could anyone point out how to prepopulate datetime fields based on current date and time and not that of data from the model?

Best regards,
K...

**Comment by ckosloski** [comment]
Looking at the combodate documentation, `value` is the correct attribute to set it's initial value which is actually `e-value` on the editable-combodate component.

**Comment by ckosloski** [comment]
@eugef I think we can close this due to lack of response.
