### ISSUE TITLE
Cancel button does not cancel if currently editing a different field

### ISSUE THREAD

**Issue by Glassig** [vitalets/angular-xeditable#668]
I have two editable textareas next to each other. If I start to edit one of them, then starts to edit the next one, the first is still open for editing (this is okay). However, when I click the cancel button for the first, it just closes the editing without resetting the field. 

Also, for some reason it saves the field without running the "onbeforesave" function, because if I have errors for that field it just ignores it and saves.

**Comment by Glassig** [comment]
It should be noted that if you try to cancel when there are errors, it just saves. It does not call "onbeforesave" or anything, it just stops the editing with the value that is not allowed inside it.

**Comment by ckosloski** [comment]
Can you post a jsfiddle or plunkr showing your issue?

**Comment by Glassig** [comment]
I just figured out what it is. I want to count the amount of characters on the input. So I have the editable field change the value {{ctrl.value}}, and on another place {{ctrl.value.length}}. Then I use e-ng-change to set ctrl.value to the new value. I guess that is why the cancel doesn't work.
My bad. Thanks for answering so quickly anyway!
