### ISSUE TITLE
Changing text on input does not save the changes with buttons = no

### ISSUE THREAD

**Issue by ZivW44** [vitalets/angular-xeditable#673]
I don't want to use buttons and I want the value to be saved.

I have made this [fiddle](http://jsfiddle.net/re342wf5/2)

Supplying buttons: 'no' and submit on blur

When I click on a button element that has ng-click, the value is not changed only after the ng-click has ended.

To replicate - try to change the value on the User.Name and click the button.

Added: If I add a $timeout(...), it will work.

**Comment by ckosloski** [comment]
The reason the select works is because when you select a new item in the list, that is the blur.
What are you trying to do with the button and why is timeout not an option?

**Comment by ZivW44** [comment]
The button is collecting data for later send the server, so if a user press this button, the value will still be the old value.

timeout is an option but I prefer not to use timeout if not needed.
Do you not consider this a bug? basically with button='no' I would expect that the value will be changed on change, not on blur. (the docs states on change)

**Comment by ckosloski** [comment]
The select input is setup so that it saves on change for no buttons, which works well for a select.  A text input is not setup the same way and I'm not sure it would work as well.
I think the best thing to do is use the timeout
