### ISSUE TITLE
use xeditable in bind-html-compile

### ISSUE THREAD

**Issue by harryyuanfeng** [vitalets/angular-xeditable#676]
is it possible to do this:

Html

`<span ng-bind-html="title"></span></span>`

JS

```
scope.name = 'harry';
scope.title = '<a editable-text="scope.name">{{ scope.name || \'empty\' }}</a>';
```

**Comment by ckosloski** [comment]
Is it giving you an error when you try that?

**Comment by harryyuanfeng** [comment]
it shows empty instead of the string 'harry'

**Comment by harryyuanfeng** [comment]
well, I solved this by doing this:

```
.directive("editDeviceName", function() {
    return {
    	scope: {
    		text: '='
    	},
        template : '<a href="#" editable-text="text">{{ text || \'empty\' }}</a>'
    };
})
```
`scope.title = '<edit-device-name text = "baseData.device.name"></edit-device-name>';`

`<span bind-html-compile="title"></span>`

**Comment by ckosloski** [comment]
OK, thanks for providing your solution.  Please close this issue if the solution you provided is satisfactory.
