### ISSUE TITLE
I need apply oi.select

### ISSUE THREAD

**Issue by SebastianCBA** [vitalets/angular-xeditable#677]
Hello! I need apply oi.select (http://tamtakoe.github.io/oi.select/#/select/#multiple)
to a editable-select..

Some tip for that?

Thanks in advance

**Comment by ckosloski** [comment]
You would need to make a new directive similar to [ui-select](https://github.com/vitalets/angular-xeditable/blob/master/src/js/directives/uiselect.js)

**Comment by SebastianCBA** [comment]
great! I applied:

    <div editable-ui-select="sectorSheet.stock_new_format" data-e-form="rowform" 
    data-e-name="stock_new_format" name="stock_new_format" theme="bootstrap" 
    data-e-ng-model="sectorSheet.stock_new_format" data-e-style="width:200px;" e-multiple >
      [[sectorSheet.stock_new_format]]
      <editable-ui-select-match placeholder="Stock">
          [[$item]]
      </editable-ui-select-match>
      <editable-ui-select-choices repeat="state in stockjson | filter: $select.search track by $index">
        [[state]]
      </editable-ui-select-choices>
    </div>

But now, I need add a new value if not exists, to the list

**Comment by SebastianCBA** [comment]
Solved with https://stackoverflow.com/questions/29489821/allow-manually-entered-text-in-ui-select

**Comment by SebastianCBA** [comment]
Everything works fine, but I only have one problem, when uiselect is not in edit mode, the value it displays is:
["<value1>","<value2>","<newvalue>"]

and I would like it to show up like this:
value1, value2, newvalue

without losing the link with the edition, any help out there?

**Comment by ckosloski** [comment]
What does the data in stockjson look like?
If you posted a plunkr or jsfiddle showing your issue, it would make it easier to troubleshoot the issue.

**Comment by SebastianCBA** [comment]
I get the stock json from a laravel function:
I get the stock json from a laravel function:
    $SectorSheets = array();

        $SectorSheets = SectorSheet::where('stock_new_format', 'like', "<%")
                                    ->select('stock_new_format as result')
                                    ->get(); 
        $SectorSheets->each(function($SectorSheets)
                {
                     $texto = $SectorSheets->result; 
                     $divide = explode(">", $texto);
                     $SectorSheets->result  = $divide[0].">"; 

                });
        return Response::json($SectorSheets);

that return:

[{"result":"<Monsanto>"},{"result":"< Yuan Longping High- Tech Agriculture >"},{"result":"<Al Dahra Agriculture>"},{"result":"<Fonterra Co-operative Group>"},{"result":"<Astarta Holding>"},{"result":"<Solazyme>"},{"result":"<Derco Foods>"},{"result":"<Calavo Growers>"},{"result":"<Compagnie Fruiti\u00e8re>"},{"result":"<Compagnie Fruiti\u00e8re>"},{"result":"<Chiquita Fyffes>"},{"result":"<Coop de France>"},{"result":"<Kidman & Co>"},{"result":"<Bigard>"},{"result":"<Dawn Meats>"},{"result":"<Jimmy Dean>"},{"result":"<Jimmy Dean>"},{"result":"<Zambeef>"},{"result":"<Tilray>"},{"result":"<Tikun Olam>"},{"result":"<Bedrocan>"},{"result":"<GW Pharmaceuticals>"},{"result":"<Arena Pharmaceutical>"},{"result":"<Olam>"},{"result":"<InVivo>"},{"result":"<Monsanto>"},{"result":"<L\u00e9gulice>"},{"result":"<Cl\u00e9ment Faugier>"}]

and I load the data from http function:

    $http.get('Stock/json').success(function (data) {
                    var temp = [];
                    for(var key in data){
                      temp.push(data[key].result);
                    }                      
    $scope.stockjson = temp;
    });

I can't upload to jsfiddle because it's a very long project with a big database, roles, login, etc... but I will do if you can't help me...

**Comment by ckosloski** [comment]
The data you pasted has the <> symbols around the values, that would be why they are showing up in the display.

**Comment by SebastianCBA** [comment]
I know, forget the symbols... I store the array in a field using the serialize function:

$sector->stock_new_format = serialize($request->stock_new_format);
$sector->save();

That stores the values ​​perfectly in the database:
a:3:{i:0;s:3:"one";i:1;s:3:"two";i:2;s:5:"three";}

Then, when I read the data and use the unserialize function:

        $SectorSheets->each(function($SectorSheets)
                {
                     if($this->is_serialized($SectorSheets->stock_new_format))
                         {
                         $SectorSheets->stock_new_format = unserialize($SectorSheets->stock_new_format);   
                         }
                });

and also works perfect, but when I show the data in the view, it shows me like this:
["one", "two", "three"]

![image](https://user-images.githubusercontent.com/22308520/28829480-47886228-76aa-11e7-86bf-0575811e390c.png)

but I want them to be used like this:

one, two, three

do you understand?

**Comment by SebastianCBA** [comment]
Sorry, I solved with https://stackoverflow.com/questions/27239754/angular-print-string-array-without-quotes 

thanks anyway, you are the best!

**Comment by ckosloski** [comment]
Can you post what you final ui-select code looks like for others who may have this issue in the future and then please close this issue.

**Comment by SebastianCBA** [comment]
yes!
view:
    <div editable-ui-select="sectorSheet.stock_new_format" data-e-form="rowform" 
    data-e-name="stock_new_format" name="stock_new_format" theme="bootstrap" 
    data-e-ng-model="sectorSheet.stock_new_format" data-e-style="width:200px;" e-multiple >
      
    <span class="list" ng-repeat="thing in sectorSheet.stock_new_format track by $index">
  		[[ thing ]]
	 </span>
      <editable-ui-select-match placeholder="Stock">
          [[$item]]
      </editable-ui-select-match>
      <editable-ui-select-choices repeat="state in getStock($select.search) | filter: $select.search track by $index">
        [[state]]
      </editable-ui-select-choices>
    </div>

function getStock:

$scope.getStock = function(search) {
 var newSupes = $scope.stockjson.slice();
  if (search && newSupes.indexOf(search) === -1) {
    newSupes.unshift(search);
  }
  return newSupes;
}

and options:
app.factory("stockjson", function ($resource) {
    return $resource("Stock/json", //la url donde queremos consumir
        {}, 
        { get: { method: "GET", isArray: true }
    })
});
    $scope.stockjson = stockjson.get();
