### ISSUE TITLE
Words and characters not working  when multiple fields from different forms are open

### ISSUE THREAD

**Issue by BukicMicko** [vitalets/angular-xeditable#684]
When I open one editable-text-angular in some form in all other forms words and characters are not working (only for first form is working).

```
 <div ng-repeat="data in vm.data"
  <ng-form name="findingDetailsForm">
        <form editable-form name="editableUpdateTitleForm">
             <a class="clickable" editable-text-angular="data.title" e-ta-max-text="3000" e-name="title"
                ng-click="editableUpdateTitleForm.$show(); data.changes = true" ng-
               show="!editableUpdateTitleForm.$visible">
        </>
  </>
 </>

```

Strange for me is that when i check in main form findingDetailsForm when editable fields are open from two different forms inside findingDetailsForm  I have only one editableUpdateTitleForm but there should be two with different index or something, right?

**Comment by ckosloski** [comment]
I think you would need to have a dynamic name for the form, something like ```editableUpdateTitleForm{{$index}}```

**Comment by BukicMicko** [comment]
Yeah was thinking same but it is strange for me because in every place on html when I have editableUpdateTitleForm i replace it with editableUpdateTitleForm.{{$index}} and I am getting html error  Syntax Error: Token '.3.' is an unexpected token...

**Comment by BukicMicko** [comment]
Also I just saw in console log it says that editor with that name already exist. $index would help but why i get this error I am confused.

**Comment by BukicMicko** [comment]
Hey @ckosloski I finally resolved $index issue. I am calling function to open form by sending index. But again i cannot get rid of error"

```textAngular Error: An Editor with name "title" already exists <div text-angular="" ta-max-text="3000" name="title" class="editable-input ng-pristine ng-untouched ng-valid ng-isolate-scope ta-root" ng-model="$parent.$data">```

Maybe I can somehow add $index to e-name also or something..

**Comment by BukicMicko** [comment]
Yup I just added {{$index}} to e-name="title{{$index}}" and everything is working good now. Thanks for help!
