### ISSUE TITLE
Having issue in e-formclass with textarea 

### ISSUE THREAD

**Issue by kushal555** [vitalets/angular-xeditable#689]
I am facing an issue in dynamically adding the class name to form. While I am using the `e-formclass` attribute with `input type='text'` its working fine but whenever I used it with text box its giving error.

[Textarea](http://jsfiddle.net/bsbs9zp8/1/)
[Textbox](http://jsfiddle.net/NfPcH/20107/)

**Comment by ckosloski** [comment]
I think I see the issue, I need a few days to get around to doing the fix.
