### ISSUE TITLE
Live templates (for jsFiddle and Plunkr) do not work

### ISSUE THREAD

**Issue by piotr-dobrogost** [vitalets/angular-xeditable#692]
Live templates for [jsFiddle](http://jsfiddle.net/NfPcH/3) and [Plunkr](http://plnkr.co/edit/BjWwXIlYyyLvRnVwO8m8?p=preview) given at https://github.com/vitalets/angular-xeditable/blob/master/CONTRIBUTING.md do not work; `{{ showStatus() }}` string is literally being rendered for example.

**Comment by ckosloski** [comment]
@eugef this was fixed by #693, please close.

**Comment by piotr-dobrogost** [comment]
Thanks!
