### ISSUE TITLE
types date and select2 are not ported to angular yet?

### ISSUE THREAD

**Issue by kumaravnish** [vitalets/angular-xeditable#7]
Was really looking forward for this angular support for a while, so thank you so much. I was wondering if you have plans to port the date and select2 as well in the near future. I have a project where I want to use this plugin to make the table editable and Select2 is a standard for all dropdowns in the application. We also have a date field in one of the columns and wanted to use the bootstrap datepicker as you have in the original x-editable implementation.

**Comment by fntneves** [comment]
+1

**Comment by rigobcastro** [comment]
+1

**Comment by jengwood** [comment]
would love to use select2 with xeditable. does anyone have an example of that?

**Comment by tarlepp** [comment]
+1 for select2, anyone has example for this?

**Comment by davidsielert** [comment]
I added angular-selectize2 element right in easily ,, ~the only problem being you must modify the switch Statement in the postrender~ - nevermind thats for some class changes.. 

my code.. 

    angular.module('xeditable').directive('editableSelectize', ['editableDirectiveFactory',
function(editableDirectiveFactory) {
  return editableDirectiveFactory({
    directiveName: 'editableSelectize',
    inputTpl: '<selectize></selectize>',
    render: function() {
      this.parent.render.call(this);
      this.inputEl.removeAttr('class'); //Dump the form-control and other junk that gets added we don't need
    }
  })
}]);

**Comment by cina2012** [comment]
hi.
i have a problem.
model value is not updated when user select item.
can you help me?
tnx.

**Comment by mitcht** [comment]
Closed as being too old

**Comment by tarlepp** [comment]
And the issue is still open.

**Comment by mitcht** [comment]
Please provide a JS fiddle. I am just starting collaboration and doing a bit of cleanup / damage control. There are 10 pages of issues.  The fact that you just commented on this is a good sign we still have a problem. Thanks.
