### ISSUE TITLE
Editable Forms and Jade.js

### ISSUE THREAD

**Issue by edalorzo** [vitalets/angular-xeditable#70]
I have noticed that when I create an editable form in pure HTML it all works fine, but when I create it with Jade.js it suddenly stops working.

The thing is that Jade.js does not define empty attributes, and so

`form(editable-form)` becomes `<form editable-form="editable-form"/>`

After some experimentation and some reading of the source code I realized that for the editable form to work, the attribute must not have a value, and so I was forced to set it to empty in Jade.js and that did the trick for me.

`form(editable-form="")`

However, ideally this should either be documented or fixed somehow because I have spent several hours trying to figure out what was wrong with my code.

**Comment by kayali** [comment]
+1

**Comment by mitcht** [comment]
Closed as being too old
