### ISSUE TITLE
Typeahead functinality not found

### ISSUE THREAD

**Issue by santilin** [vitalets/angular-xeditable#704]
I'm trying to implement typeahead over an xeditable input control following [the docs](https://vitalets.github.io/angular-xeditable/#typeahead), but I can't. It looks like the properties for the typeahead plugin are not present.

However, searching the code in the path angular-xeditable, I only find a few references to the word typeahead:

```
node-modules/angular-xeditable$ grep typeahead * -R
CHANGELOG.txt:[enh] add typeahead control (vitalets)
dist/css/xeditable.css:/* fix padding issue on typeahead */
```

I have installed xeditable via npm like this:
```
npm install angular-xeditable                 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ angular-xeditable@0.8.1
added 115 packages and updated 1 package in 20.458s
```

Do I need to install any other package?

**Comment by ckosloski** [comment]
Did you include angular-ui-bootstrap as specified by the documentation?

**Comment by santilin** [comment]
I didn't, but I have done now and still I can't find any references to e-uib-typeahead. Is it possible that the 'e-' prefix is added by the xeditable extension?

**Comment by ckosloski** [comment]
Can you post your code you are having an issue with or make a plunkr/jsfiddle so that I can better understand what your issue is?

To run typeahead, you have to include angular-ui-bootstrap and any properties of the bootstrap typeahead should be prefaced with `e-`.
