### ISSUE TITLE
Ui-select on select event

### ISSUE THREAD

**Issue by jmliz** [vitalets/angular-xeditable#710]
Is there a way to use ui-select's `on-select` [event name](https://github.com/angular-ui/ui-select/wiki/ui-select#events) attribute whenever the user changes options? 

Like:

```
<div editable-ui-select="field" data-e-form="myForm" data-e-ng-model="field" data-e-on-select="update($data)">
    (...)
</div>
```

**Comment by ckosloski** [comment]
Yes, adding `e-on-select` should work.
If it's not working for you, can you provide a jsfiddle/plunkr showing your issue?

**Comment by jmliz** [comment]
nvm, it works. thanks.
