### ISSUE TITLE
e-inputgroup two way binding

### ISSUE THREAD

**Issue by dementic** [vitalets/angular-xeditable#713]
It seems that the inputgroups are static and will not update when binding to a value:
`                                            <a editable-number="someScopeValue"
                                                    e-inputgroupleft="{{ someFunctionToCalcNewValue($data) }}">
                                                    {{ someScopeValue }}
                                                </a>`

**Comment by ckosloski** [comment]
Hi @dementic can you describe your error some more, or provide a plnkr or jsfiddle showing your issue?
If I create a function that generates a random number, I see a new number in my input group every time I open it.

**Comment by dementic** [comment]
Here you go:
https://jsfiddle.net/s4qva61w/5/

**Comment by dementic** [comment]
Here is a fiddle, let me know if i got something wrong:
https://jsfiddle.net/s4qva61w/8/
