### ISSUE TITLE
Side by Side forms in Safari 11 won't let go of focus

### ISSUE THREAD

**Issue by logan-jobzmall** [vitalets/angular-xeditable#714]
http://jsfiddle.net/zjtoy868/8/

See my JSFiddle. The behavior is slightly different than what I am seeing on my app (literally I can see the focus going between the first field of each form and I can't remove focus even using `form.blur();` or `input.blur();`. Although the behavior isn't exactly the same you should be able to see that on Safari 11 it is almost impossible to get to another input underneath on either form. Thanks!

**Comment by ckosloski** [comment]
Try setting `editableOptions.activate = 'none';`
It appears that the two forms are competing for the focus since the default `activate` is `focus`
http://vitalets.github.io/angular-xeditable/#ref-options

**Comment by logan-jobzmall** [comment]
Testing now.... Thanks!

**Comment by logan-jobzmall** [comment]
Worked! Thank you
