### ISSUE TITLE
Not Set / Unknown / Unavailable / Not Available

### ISSUE THREAD

**Issue by s2jrchoi** [vitalets/angular-xeditable#720]
Hello,

This isn't really an issue but wanted some guidance on how to change the font style for fields without any data.  I want to put a placeholder such as Not Set, Unknown, Unavailable, or Not Available but I want that to stick out and not blend in with all the other fields.  Can anyone please help me with this?

Thank you!

**Comment by ckosloski** [comment]
You need to override the `editable-empty` css class with what you want.

**Comment by s2jrchoi** [comment]
Thank you!!
