### ISSUE TITLE
How to make editable select readonly/disabled?

### ISSUE THREAD

**Issue by piotr-dobrogost** [vitalets/angular-xeditable#722]
In the docs we read the following:
> To make the input field read-only and force the date to be selected from the popup, add the `e-readonly="true"` attribute.

This works for text input fields but not for select as `<select>` tag does not honor `readonly` attribute (see https://stackoverflow.com/q/11976348/95735). This had been already asked at SO here – https://stackoverflow.com/q/36794664/95735 – and the suggestion is to show editable control conditionally on some flag. Is this workaround the only way?

**Comment by ckosloski** [comment]
Are you trying to use an `editable-select` and make it `read-only` and not disabled?
It so, yes, there is no good way of doing it.
You would have to try one of the suggested options using css/js or both to make it look read-only.

What is your use-case?
Maybe just display a read-only text field if they can't change it and display the select for when it's changeable.

**Comment by piotr-dobrogost** [comment]
> Are you trying to use an editable-select and make it read-only and not disabled?
> It so, yes, there is no good way of doing it.

Well, I hoped that `e-readonly` would be smart enough to use whatever attribute is suitable for specific type of input field which for `<select>` appears to be `disabled`. Now that I know it's not that smart setting `disabled` myself seems like a good option.

> You would have to try one of the suggested options using css/js or both to make it look read-only.

I would like to avoid this extra complexity if I can.

> What is your use-case?

When editing item some fields which are editable during addition are not meant to be editable anymore.

> Maybe just display a read-only text field if they can't change it and display the select for when it's changeable.

That's what I ended up with. It would be nice to have some `e-if` attribute which would do this automatically.
