### ISSUE TITLE
editable-bsdate not working inside form

### ISSUE THREAD

**Issue by kuiperr005** [vitalets/angular-xeditable#726]
The editable-bsdate does not seem to work inside a form. Here's a jsFiddle, toggling the `is-open` attribute does not seem to work:

http://jsfiddle.net/NfPcH/23004/

**Comment by ckosloski** [comment]
You code was incorrect.
Here is a working version of your [fiddle](http://jsfiddle.net/ckosloski/0dfrmm3w/13/)

**Comment by kuiperr005** [comment]
You're right, thanks!
