### ISSUE TITLE
Is there a way to disable all xeditalbe forms?

### ISSUE THREAD

**Issue by lukasz-madon** [vitalets/angular-xeditable#73]
I want to reuse a profile page template. Basically, user can edit his profile page, but others can only view. Is there a way to disable all editing for a page that will not break in the future? I tried 

    editableOptions.activate = 'none';

**Comment by renatomefidf** [comment]
@Nate-Wilkins +1

I was trying to use ng-disabled but the editable form keeps showing!

Is there a more native solution that you found?

**Comment by Nate-Wilkins** [comment]
@renatomefidf 

Unfortunately no - I ended up passing `ng-disabled` down with prefix `e-` and just have the editable form show but disabled.

**Comment by renatomefidf** [comment]
@Nate-Wilkins do you mind to show me this piece of code?

Thanks for your answer!

**Comment by renatomefidf** [comment]
Thank you @Nate-Wilkins 

It worked and I used onshow to control the disabled flow!

**Comment by Nate-Wilkins** [comment]
@renatomefidf No problem!

Now we can just wait for the merge so we can use `ng-disabled`

**Comment by aligajani** [comment]
Doesn't work?

**Comment by mitcht** [comment]
Create new issue.
