### ISSUE TITLE
editable-bsdate doesn't seem to work with ui.bootstrap.popover (ui-popover-wrapper)

### ISSUE THREAD

**Issue by osvathrobi** [vitalets/angular-xeditable#738]
My other controls are working fine within the popover except the date picker. Only the Submit and Cancel buttons appear in the popover. 

```
<div class="ui-popover-wrapper">
  <a href="#" 
       editable-bsdate="startDate" 
       e-name="startdate" 
       e-single 
       e-show-calendar-button="false" 
       e-datepicker-popup="dd.MM.yyyy" 
       e-style="width:auto" 
       e-datepicker-mode="day" 
       e-is-open="true"
       uib-popover-template="'popover.html'"
       popover-is-open="popoverIsOpen"
       popover-append-to-body="true"
       onshow="popoverIsOpen = !popoverIsOpen" 
       onhide="popoverIsOpen = !popoverIsOpen"
       popover="true"
       popover-placement="top"
       popover-title="When should the first payment start"
       onaftersave="myform.$setDirty(true)">Event will start on {{startDate}}</a>
</div>
```

This seems to be the same reason why form-control class isn't added to inputs within a ui-popover. `$templateCache.put('popover.html', self.editorEl[0].outerHTML)` is used in the code to pass it over to the popover but the control hasn't finished  being creating yet. (hacking in a setTimeout for this assignment fixes the issue, so I can confirm it is related to this)

**Comment by osvathrobi** [comment]
One hack-fix is to move this code from the `self.render` method into the `self.show` method right before triggering `self.onshow`:

```
if (self.popover) {
        var wrapper = angular.element('<div></div>');
        wrapper.append(self.editorEl);
        self.editorEl = wrapper;
        $templateCache.put('popover.html', self.editorEl[0].outerHTML);
}
```

This will fix both the missing class names and creating the bsdate controls.

**Comment by ckosloski** [comment]
@osvathrobi what do you mean by "hack-fix".  Do you think this should be fixed in a different way that what you posted?

**Comment by osvathrobi** [comment]
@ckosloski I use this in production for over a year and it seems to be working fine. I meant "hack-fix" as in - it is not an official response from the contributors.
