### ISSUE TITLE
Can't enter space in xeditable in AngularJS 1.7.3

### ISSUE THREAD

**Issue by sherlock1982** [vitalets/angular-xeditable#739]
Switching from AngularJS 1.7.2 to 1.7.3 breaks ability to enter spaces in input fields. 
I have a feeling this is due to this change https://github.com/angular/angular.js/commit/3a517c25f677294a7a9eca1660654a3edcc9e103

**Comment by sherlock1982** [comment]
Workaround: downgrade aria to 1.7.2

**Comment by gkalpak** [comment]
The regression should have been fixed with angular/angular.js#16680. It is not released yet (will happen in the next few days - possibly tomorrow). In the meantime, you can try out the latest version from https://code.angularjs.org/snapshot/ and see if the error goes away 🙏

**Comment by ckosloski** [comment]
Should this be closed now that the issue has been merged?

**Comment by gkalpak** [comment]
For future reference, the fix is included in v1.7.4. @sherlock1982, can you confirm that upgrading to v1.7.4 fixes the issue?
