### ISSUE TITLE
Is there a way to disable a checkboxe inside a checklist?

### ISSUE THREAD

**Issue by lohxx** [vitalets/angular-xeditable#744]
I want to disable some checkboxes based on a condition, but i'm not finding a way to do it. Is there someone that can help me?

version: 0.8.1

code:
```html
<a 
           href="#" 
           onaftersave="updateUser()" 
           editable-checklist="obj.roles" 
           e-ng-options="s.value as s.text for s in userService.all_roles"
     > 
     <span ng-bind-html="showRoles()"></span>
  </a>
```

**Comment by lohxx** [comment]
I find a possible solution to this problem, but i need to send a pull request, can anyone help me with that?

**Comment by ckosloski** [comment]
What do you need help with?

**Comment by lohxx** [comment]
I am having some problems to build and run the tests of the project.

**Comment by ckosloski** [comment]
To build
`grunt clean jade build`

To run
`http-server`

To run the tests:
`http://localhost:8000/test/e2e/dev-test.html`
`http://127.0.0.1:8080/test/e2e/docs-test.html`

To view the site:
`http://localhost:8000`

**Comment by ckosloski** [comment]
Also info is here
https://github.com/vitalets/angular-xeditable/blob/master/CONTRIBUTING.md

**Comment by lohxx** [comment]
Thanks, i will try to run these steps later!
