### ISSUE TITLE
Use editable within form

### ISSUE THREAD

**Issue by TehEbil** [vitalets/angular-xeditable#748]
Hi, is it possible to have an (editable) input field inside my form? I only want this element to be editable and not all the others.

If I add editable-form in the form and edit one of the fields, all elements are being edited. So I just want to use it like the example given, inside a form, is that possible?

**Comment by ckosloski** [comment]
Is this what you are looking for?
http://vitalets.github.io/angular-xeditable/#e-single

**Comment by TehEbil** [comment]
Thank you very much, this was exactly what I was looking for! Sorry for not finding it myself and using your time >.<
