### ISSUE TITLE
Does editable-checklist support e-name?

### ISSUE THREAD

**Issue by sinall** [vitalets/angular-xeditable#769]
When one of checkbox is checked, I want some other elements to show or hide.
So I plan to use `editableForm['some-name']['$viewValue']`, but this is `undefined`.
I checked the html, but it seems that `name` is not added onto `input`.

**Comment by ckosloski** [comment]
Did you try `data-e-name="some-name"` when you defined the checkbox?

**Comment by sinall** [comment]
I made an example on [jsfiddle](http://jsfiddle.net/y4qL3u0m/), but the input element still doesn't have a name:
`<input type="checkbox" checklist-value="s.value" ng-model="checked" class="ng-scope ng-pristine ng-valid ng-not-empty ng-touched" checklist-model="$parent.$parent.$data">`

Ideally, the input should have `name="check_list[]"` in order to hold multiple values as [this thread](https://stackoverflow.com/questions/4997252/get-post-from-multiple-checkboxes) described.

**Comment by ckosloski** [comment]
OK, I think I see the issue.  I'll see if I can come up with a fix.

**Comment by ckosloski** [comment]
I've created a PR for this, please review.
