### ISSUE TITLE
Possible to use typeahead w/ a comprehension expression?

### ISSUE THREAD

**Issue by redterror** [vitalets/angular-xeditable#77]
I'm trying to do approximately:

```
<h2 class="foo.color" editable-text="foo.topicId" e-typeahead="topic.id as topic.name for topic in getTopics($viewValue)" e-typeahead-wait-ms="200" e-form="changeTopic">
    {{topic.name}}
</h2>
```

Is this possible?  It's not clear to me from the docs whether I'm doing something wrong or if this style of operation is not yet supported.

The main issue is that after selection, the id is rendered instead of the topic text as desired.

jsFiddle here, albeit with issues: http://jsfiddle.net/NfPcH/688/

**Comment by MuraliM** [comment]
@redterror  I am also looking to implement something similar. Please inform if you resolve it.

Thanks in advance!

**Comment by redterror** [comment]
We ended up with a different solution.  It's been a while now, so my apologies but I don't recall what we did.

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
See this [thread](https://github.com/angular-ui/bootstrap/issues/981) on your options for for doing this.

**Comment by ckosloski** [comment]
@eugef this question has been answered, please close.
