### ISSUE TITLE
console.log still present

### ISSUE THREAD

**Issue by Gu3** [vitalets/angular-xeditable#771]
Hi ! 
you've got a console.log present in xeditable.js file.
Not on Master but in 0.10.1 release. 

![image](https://user-images.githubusercontent.com/5227741/90416209-792cc880-e0b2-11ea-987e-84b4981904f4.png)

Thanks !

**Comment by ckosloski** [comment]
Yeah, this looks like it should be fixed in 0.10.2
```Version 0.10.2 Nov 1, 2019

[bug] Comment out console.log
```

**Comment by Gu3** [comment]
yep indeed but version 0.10.2 not available on Bower :/

**Comment by ckosloski** [comment]
@eugef can you make version 0.10.2 available on Bower?

**Comment by eugef** [comment]
I've created `0.10.2` tag in Github, hope Bower will pick it up soon

**Comment by Gu3** [comment]
It's all-ready  Done! Thanks you for the quick fix ! 
Have a good one :)
