### ISSUE TITLE
Datepicker Style problem

### ISSUE THREAD

**Issue by sapien99** [vitalets/angular-xeditable#78]
Hi guys, awesome work on this!

I just noticed a little style problem when using the datepicker control when using an inputfield with bootstrap3. The inputfield does not have the same height as the ones of other controls (like  select or input), because the "form-control" class is not set - unlike the other controls.

The reason behind this is on xeditable.js on line 1553 where the directive name is checked to add the form-control class. I just added "case 'editableBsdate':" and everything works (guess "case 'editableDate':" could be removed now)

Switch statement looks now the following:

//apply `form-control` class to std inputs
        switch(this.directiveName) {
          case 'editableText':
          case 'editableSelect':
          case 'editableTextarea':
          case 'editableEmail':
          case 'editableTel':
          case 'editableNumber':
          case 'editableUrl':
          case 'editableSearch':
          case 'editableDate':
          case 'editableBsdate':
          case 'editableDatetime':
          case 'editableTime':
          case 'editableMonth':
          case 'editableWeek':
            this.inputEl.addClass('form-control');

Thanks and Cheer 
Michael

**Comment by ckosloski** [comment]
This has already been fixed, this can be closed.
