### ISSUE TITLE
Popover Control

### ISSUE THREAD

**Issue by xiaogwu** [vitalets/angular-xeditable#81]
Can we add a Popover Editable Control?

**Comment by dbrgn** [comment]
Yeah, would be great :)

Here's another workaround: http://ryanlanciaux.github.io/blog/2013/10/16/fake-popovers-for-angular-xeditable/

**Comment by JobaDiniz** [comment]
+1

**Comment by gabrielchites** [comment]
+1

**Comment by RPGillespie6** [comment]
+1

**Comment by ckosloski** [comment]
@eugef I think this can be closed
