### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by tonyeung** [vitalets/angular-xeditable#83]
http://stackoverflow.com/questions/21689745/auto-open-next-with-angular-and-x-editable

The example for auto open next is using the jquery library.
I'd like to have the same behavior with the angularjs

the below code is how the next field is being opened using jquery:

```
$('#user .editable').on('hidden', function(e, reason){
    if(reason === 'save' || reason === 'nochange') {
        var $next = $(this).closest('tr').next().find('.editable');
        if($('#autoopen').is(':checked')) {
            setTimeout(function() {
                $next.editable('show');
            }, 300); 
        } else {
            $next.focus();
        } 
    }
});
```

The problem is that there doesn't seem to be anything I can use as a trigger to open the next field. In jquery there is the hidden event, and I tried to listen for the $destroy event, but nothing ever seems to happen.

**Comment by ckosloski** [comment]
Here is an idea on how to do it.  That code is very specific to the demo, so I don't think it is something that belongs in the project.

I was playing around in the project and came up with this.  You could pass in  your own onhide function maybe to do something similar.
```
      //Auto open next element if autoOpen is set and no onhide function is already set
      if (!$attrs.onhide && editableOptions.autoOpen) {
          self.onhide = function() {
              var next = self.elem.next('.editable');
              
              if (next) {
                  return $timeout(function () {
                      next.click();
                  }, 300);
              } else {
                  return angular.noop;
              }
          };
      }

**Comment by ckosloski** [comment]
@eugef Please close this issue due to lack of response
