### ISSUE TITLE
Auto open next field like jQuery version

### ISSUE THREAD

**Issue by harveyphan** [vitalets/angular-xeditable#85]
Firstly, I would like to thank you very much for the great plugin. 

So how can i implement auto open next field like jQuery version.
http://vitalets.github.io/x-editable/demo-bs3.html?c=inline

I try to figure out myself but don't know how to do it in angular way, Please have look at my plunker:
http://plnkr.co/edit/a1MmgfojGd1CDzaX8CVK?p=preview

Many thanks

**Comment by ckosloski** [comment]
You can do something like this to open the next field:
```  
<a href="#" class="submit" editable-text="user.name" data-e-label="User Name" blur="submit" buttons="no" onaftersave="nextElement('cancel')">
    {{ user.name }}
  </a>
  &nbsp;
  <a href="#" class="cancel" id="cancel" editable-text="user.name" blur="cancel">
    {{ user.name }}
  </a>

    $scope.nextElement = function(id) {
        $timeout(function() {
            angular.element('#' + id).trigger('click');
        }, 50);
    };

**Comment by ckosloski** [comment]
@eugef This has been answered, please close.
