### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by marisks** [vitalets/angular-xeditable#88]
When I try to use keyboard to navigate through fields, it doesn't work. 
For example, in JsFiddle from readme: http://jsfiddle.net/NfPcH/3/

I can navigate through fields, hit Enter to get into edit mode, then enter to save and tabbing is lost.

In original x-editable samples it works fine:
http://vitalets.github.io/x-editable/demo-bs3.html

**Comment by tallsam** [comment]
+1 tabbing is lost when submitting via the keyboard

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
@eugef There hasn't been an recent follow up on this, please close.
