### ISSUE TITLE
Disable xeditable element while preserving html content functionality

### ISSUE THREAD

**Issue by lanceschi** [vitalets/angular-xeditable#90]
Hi @vitalets,

I was playing around with your impressive module and textarea[s], although I was wondering if it is possible to disable the click/edit action and trigger it for example from an outside button. I read the documentation albeit unsuccessfully.

I was trying to implement a note editor which save in text format but features tags parseable into html anchor tags server side. The text attribute of the note is plain text while the parsed_text attribute is the marked-up version sent by the server after processing.

My goal is for instance to disable the input control while preserving the possibility to click the html anchors parsed from the ng-html-bind. So basically I wrote two directives. The former to stop propagation of mouse click/finger tap:

```
myApp.directive('clickStop', ['$parse', function( $parse ) {
  return {
    restrict: 'A', 
    link: function(scope, element, attrs) {
      if(attrs.clickStop == undefined) return;

      $(element).on("click tap", function(e) {
        e.stopPropagation();
      })      
    }
  }  
}]);
```

... and the latter to redirect mouse click/finger tap:

```
myApp.directive('clickThrough', ['$parse', function( $parse ) {
  return {
    restrict: 'A', 
    link: function(scope, element, attrs) {
      if(attrs.clickThrough == undefined) return;

      $(element).on("click tap", function() {
        $(attrs.clickThrough).click();
      })      
    }
  }  
}]);
```

And here the simplified HTML:

```
<div ng-repeat="item in notes">
  <a id="noteEdit_{{item.id}}" editable-textarea="item.text" e-class="form-control" e-rows="5" buttons="no" blur="submit" onaftersave="updateNote(item)">
    <div ng-bind-html="item.parsed_text" click-stop></div>
  </a>
  <div class="noteBottomBar" click-stop>
    <a href="" class="nbbItem" click-through="#noteEdit_{{item.id}}" role="button">Modify</a>
  </div>
</div>

```

As you can see I stop the click-propagation in the html inner node (content) of the editable-textarea anchor and I activate editing through a the click-through directive.

Am I missing something? Is there a better approach? An official attribute to disable editing would be really appreciated.

Thanks,
Luca

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
@lanceschi is this still an issue?

**Comment by ckosloski** [comment]
@eugef please close due to lack of response
