### ISSUE TITLE
Cancelling a row addition should delete the row

### ISSUE THREAD

**Issue by Woodz** [vitalets/angular-xeditable#92]
As per the SO question http://stackoverflow.com/questions/21336943/customize-the-cancel-code-button-of-the-x-editable-angularjs and demonstrated at http://vitalets.github.io/angular-xeditable/#editable-row

I believe that the correct behaviour on clicking cancel after adding a new row should delete the newly-added row. I have worked around this with a custom function.

**Comment by ckosloski** [comment]
The [editable-table](http://vitalets.github.io/angular-xeditable/#editable-table) example shows on to use an on-cancel event to do this.

**Comment by ckosloski** [comment]
@eugef I think this can be closed.
