### ISSUE TITLE
Date component look and feel irregular

### ISSUE THREAD

**Issue by blevinson** [vitalets/angular-xeditable#93]
Please fix date component. Notice the 17,18,19,20 and the 01, 02, 03, etc, and should the top gray boxes have some kind of navigation image?

![angular-xeditable____edit_in_place_for_angularjs](https://f.cloud.github.com/assets/17077/2389425/92395bb6-a94d-11e3-9677-2bb1efffddc0.png)

**Comment by ckosloski** [comment]
@eugef please close this issue, the current demo is working correctly.
