### ISSUE TITLE
Can't bind the editable-select to a data object using nested JSON objects 

### ISSUE THREAD

**Issue by HollandRisley** [vitalets/angular-xeditable#95]
Hi, I just can't seem to bind the editable-select to the data object using nested JSON objects in my model. The static text populates fine, and the selected item in the dropdown is pre-selected correctly but when I change the select it doesn't bind to the object. Can you kindly point me in the right direction?

In my view:

```
 <span editable-select="Organisation.OrganisationType.Id" e-name="OrganisationType" 
e-ng-options="s.Id as s.Name for s in OrganisationTypes">
            {{Organisation.OrganisationType.Name}}  
        </span>
```

In my controller:

```
 $scope.Organisation = {
    "Id": 5,
    "Name": "Digital Vision",
    "OrganisationType": {
        "Id": 3,
        "Name": "Cold"
    };

    $scope.OrganisationTypes = [{
        "Id": 1,
        "Name": "Client"
    }, {
        "Id": 2,
        "Name": "Internal"
    }, {
        "Id": 3,
        "Name": "Cold"
    }];
```

**Comment by pavi95** [comment]
Did you sort out this @HollandRisley

**Comment by ckosloski** [comment]
@pavi95 what exactly is your issue?

**Comment by pavi95** [comment]
@ckosloski  Thank you very much for your time.. I found this [https://jsfiddle.net/32kzsvve/1/](url) Such an awesome. It may help others :)
