### ISSUE TITLE
How to display and edit HTML text and color at the same time?

### ISSUE THREAD

**Issue by caioc** [vitalets/angular-xeditable#98]
How can I make an HTML completed in json to view in the field of xeditable be displayed without showing the tags, type: 
$ = {scope.user 
name: 'Test of <span style="color: #000"> color </ div>' 
} 
And as I have put a field as text and color and can change both at the same time?

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by caioc** [comment]
yes

**Comment by ckosloski** [comment]
Couldn't you setup a form to edit two different fields?
