### ISSUE TITLE
question: how do I alter things in the outer scope with onaftersave? 

### ISSUE THREAD

**Issue by jcollum-hcg** [vitalets/angular-xeditable#99]
```
a(href="#", editable-text="product.location", e-required, 
e-placeholder="Product location",  
onaftersave="alert(JSON.stringify($scope))" ) {{ product.location }}
```

I'd like to clear out a value in the parent scope after this value is updated. I tried variations on `$scope.$parent.myValue = undefined` but that didn't work. So now I'd like to just alert the current $scope on save, but the $scope is always undefined. I've tried stepping through the code but I'm not getting anywhere. 

Suggestion?

**Comment by ckosloski** [comment]
Is this still an issue?

**Comment by ckosloski** [comment]
@eugef There has been no follow up, please close.
